/**
 * Logical Operations: Constitution
 *
 * Constitution - determination and constitution as moments that pass over into each other,
 * leading to the emergence of limit as the immanent determination that makes something finite.
 *
 * Dialectical Movement:
 * - Determination: affirmative determinateness, in-itself by which something abides
 * - Constitution: external existence, alteration falls on constitution
 * - Limit: immanent determination, contradiction propels beyond itself
 */

import type { LogicalOperation } from '../../../../types';

// ============================================================================
// CONSTITUTION
// ============================================================================

export const constOp1Introduction: LogicalOperation = {
  id: 'const-op-1-introduction',
  chunkId: 'constitution-1',
  label: 'Introduction: in-itself mediated through being-for-other; determinateness existent-in-itself',
  clauses: [
    'theInItself = inWhich',
    'theInItself = theSomething',
    'theInItself = isReflected',
    'theInItself = intoItself',
    'theInItself = fromItsBeingForOther',
    'theInItself = noLongerIs',
    'theInItself = anAbstractInItself',
    'but = asTheNegation',
    'but = ofItsBeingForOther',
    'but = isMediated',
    'but = throughThisLatter',
    'but = whichIsThus',
    'but = itsMoment',
    'it = isNotOnly',
    'it = theImmediateIdentity',
    'it = ofTheSomething',
    'it = withItself',
    'but = theIdentity',
    'but = byVirtueOfWhich',
    'but = theSomething',
    'but = alsoHas',
    'but = presentInIt',
    'but = what',
    'but = itIs',
    'but = inItself',
    'theBeingForOther = isPresent',
    'theBeingForOther = inIt',
    'theBeingForOther = because',
    'theBeingForOther = theInItself',
    'theBeingForOther = isTheSublation',
    'theBeingForOther = ofIt',
    'theBeingForOther = isInItself',
    'theBeingForOther = fromIt',
    'but = because',
    'but = itIsStill',
    'but = abstract',
    'but = andTherefore',
    'but = essentiallyAffected',
    'but = withNegation',
    'it = isEqually',
    'it = affected',
    'it = withBeingForOther',
    'we = haveHere',
    'we = notOnly',
    'we = qualityAndReality',
    'we = existentDeterminateness',
    'but = determinateness',
    'but = existentInItself',
    'and = theDevelopment',
    'and = consistsIn',
    'and = positing',
    'and = suchDeterminateness',
    'and = asThus',
    'and = immanentlyReflected',
  ],
  predicates: [
    { name: 'inItself', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'inItself', to: 'mediatedThroughBeingForOther' },
  ],
  candidateSummary: 'The in-itself, in which the something is reflected into itself from its being-for-other, no longer is an abstract in-itself but, as the negation of its being-for-other, is mediated through this latter, which is thus its moment. It is not only the immediate identity of the something with itself, but the identity by virtue of which the something also has present in it what it is in itself; the being-for-other is present in it because the in-itself is the sublation of it, is in itself from it; but, because it is still abstract, and therefore essentially affected with negation, it is equally affected with being-for-other. We have here not only quality and reality, existent determinateness, but determinateness existent-in-itself; and the development consists in positing such determinateness as thus immanently reflected.',
  provenance: {
    sourceChunk: 'constitution-1',
    sourceOp: 'const-op-1-introduction',
  },
};

export const constOp2DeterminationDefinition: LogicalOperation = {
  id: 'const-op-2-determination-definition',
  chunkId: 'constitution-2',
  label: 'Determination I: definition (affirmative determinateness; in-itself by which something abides)',
  clauses: [
    'theQuality = whichIn',
    'theQuality = theSimpleSomething',
    'theQuality = isAnInItself',
    'theQuality = essentiallyInUnity',
    'theQuality = withTheSomething',
    'theQuality = otherMoment',
    'theQuality = itsBeingInIt',
    'theQuality = canBeNamed',
    'theQuality = itsDetermination',
    'provided = thatThisWord',
    'provided = isDistinguished',
    'provided = inAMore',
    'provided = preciseSignification',
    'provided = fromDeterminateness',
    'provided = inGeneral',
    'determination = isAffirmative',
    'determination = determinateness',
    'it = isTheInItself',
    'it = byWhich',
    'it = aSomething',
    'it = abidesIn',
    'it = itsExistence',
    'it = whileInvolved',
    'it = withAnOther',
    'it = thatWould',
    'it = determineIt',
    'it = byWhich',
    'it = itPreserves',
    'it = itselfIn',
    'it = itsSelfEquality',
    'it = holdingOn',
    'it = toItIn',
    'it = itsBeingForOther',
    'something = fulfills',
    'something = itsDetermination',
    'something = toTheExtent',
    'something = thatTheFurther',
    'something = determinateness',
    'something = whichVariously',
    'something = accruesToIt',
    'something = inTheMeasure',
    'something = ofItsBeingInItself',
    'something = asItRelates',
    'something = toAnOther',
    'something = becomes',
    'something = itsFilling',
    'determination = implies',
    'determination = thatWhat',
    'determination = something',
    'determination = isInItself',
    'determination = isAlso',
    'determination = presentInIt',
  ],
  predicates: [
    { name: 'determination', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'determination', to: 'affirmativeDeterminateness' },
  ],
  candidateSummary: 'The quality which in the simple something is an in-itself essentially in unity with the something\'s other moment, its being-in-it, can be named its determination, provided that this word is distinguished, in a more precise signification, from determinateness in general. Determination is affirmative determinateness; it is the in-itself by which a something abides in its existence while involved with an other that would determine it, by which it preserves itself in its self-equality, holding on to it in its being-for-other. Something fulfills its determination to the extent that the further determinateness, which variously accrues to it in the measure of its being-in-itself as it relates to an other, becomes its filling. Determination implies that what something is in itself is also present in it.',
  provenance: {
    sourceChunk: 'constitution-2',
    sourceOp: 'const-op-2-determination-definition',
  },
};

export const constOp3DeterminationExample: LogicalOperation = {
  id: 'const-op-3-determination-example',
  chunkId: 'constitution-3',
  label: 'Determination II: example (human being; rational thought; still only in itself as ought)',
  clauses: [
    'theDetermination = ofTheHuman',
    'theDetermination = being',
    'theDetermination = itsVocation',
    'theDetermination = isRational',
    'theDetermination = thought',
    'thinking = inGeneral',
    'thinking = isHis',
    'thinking = simpleDeterminateness',
    'by = it',
    'theHuman = being',
    'theHuman = isDistinguished',
    'theHuman = fromTheBrute',
    'he = isThinking',
    'he = inHimself',
    'he = inSoFarAs',
    'he = thisThinking',
    'he = isDistinguished',
    'he = alsoFrom',
    'he = hisBeingForOther',
    'he = fromHisOwn',
    'he = naturalAndSensuous',
    'he = being',
    'he = thatBrings',
    'he = himIn',
    'he = immediateAssociation',
    'he = withTheOther',
    'but = thinking',
    'but = isAlso',
    'but = inHim',
    'but = theHuman',
    'but = being',
    'but = isHimself',
    'but = thinking',
    'but = heExists',
    'but = asThinking',
    'but = thought',
    'but = isHis',
    'but = concreteExistence',
    'but = andActuality',
    'and = further',
    'since = thinking',
    'since = isIn',
    'since = hisExistence',
    'since = andHis',
    'since = existence',
    'since = isIn',
    'since = hisThinking',
    'thinking = isConcrete',
    'thinking = mustBe',
    'thinking = takenAs',
    'thinking = havingContent',
    'thinking = andFilling',
    'it = isRational',
    'it = thought',
    'it = andAsSuch',
    'it = theDetermination',
    'it = ofTheHuman',
    'it = being',
    'but = even',
    'but = thisDetermination',
    'but = isAgain',
    'but = onlyInItself',
    'but = asAnOught',
    'but = thatIsToSay',
    'but = itIs',
    'but = togetherWith',
    'but = theFilling',
    'but = embodiedIn',
    'but = itsInItself',
    'but = inTheForm',
    'but = ofAnInItself',
    'but = inGeneral',
    'but = asAgainst',
    'but = theExistence',
    'but = whichIsNot',
    'but = embodiedInIt',
    'but = butStill',
    'but = liesOutside',
    'but = confrontingIt',
    'but = immediateSensibility',
    'but = andNature',
  ],
  predicates: [
    { name: 'rationalThought', args: ['humanBeing'] },
  ],
  relations: [
    { predicate: 'is', from: 'determination', to: 'rationalThought' },
  ],
  candidateSummary: 'The determination of the human being, its vocation, is rational thought: thinking in general is his simple determinateness; by it the human being is distinguished from the brute; he is thinking in himself, in so far as this thinking is distinguished also from his being-for-other, from his own natural and sensuous being that brings him in immediate association with the other. But thinking is also in him; the human being is himself thinking, he exists as thinking, thought is his concrete existence and actuality; and, further, since thinking is in his existence and his existence is in his thinking, thinking is concrete, must be taken as having content and filling; it is rational thought and as such the determination of the human being. But even this determination is again only in itself, as an ought, that is to say, it is, together with the filling embodied in its in-itself, in the form of an in-itself in general as against the existence which is not embodied in it but still lies outside confronting it, immediate sensibility and nature.',
  provenance: {
    sourceChunk: 'constitution-3',
    sourceOp: 'const-op-3-determination-example',
  },
};

export const constOp4ConstitutionExternal: LogicalOperation = {
  id: 'const-op-4-constitution-external',
  chunkId: 'constitution-4',
  label: 'Constitution I: external existence (not belonging to being-in-itself)',
  clauses: [
    'theFilling = ofTheBeingInItself',
    'theFilling = withDeterminateness',
    'theFilling = isAlso',
    'theFilling = distinctFrom',
    'theFilling = theDeterminateness',
    'theFilling = whichIsOnly',
    'theFilling = beingForOther',
    'theFilling = andRemains',
    'theFilling = outside',
    'theFilling = theDetermination',
    'for = inTheSphere',
    'for = ofTheQualitative',
    'theDistinguished = terms',
    'theDistinguished = areLeft',
    'theDistinguished = inTheir',
    'theDistinguished = sublatedBeing',
    'theDistinguished = alsoWith',
    'theDistinguished = anImmediate',
    'theDistinguished = qualitativeBeing',
    'theDistinguished = contrastingThem',
    'that = which',
    'that = theSomething',
    'that = hasInIt',
    'that = thusSeparates',
    'that = itself',
    'that = andIs',
    'that = fromThisSide',
    'that = theExternalExistence',
    'that = ofTheSomething',
    'that = andAlso',
    'that = itsExistence',
    'but = notAs',
    'but = belongingTo',
    'but = itsBeingInItself',
    'determinateness = isThus',
    'determinateness = constitution',
  ],
  predicates: [
    { name: 'constitution', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'determinateness', to: 'constitution' },
  ],
  candidateSummary: 'The filling of the being-in-itself with determinateness is also distinct from the determinateness which is only being-for-other and remains outside the determination. For in the sphere of the qualitative, the distinguished terms are left, in their sublated being, also with an immediate, qualitative being contrasting them. That which the something has in it thus separates itself and is from this side the external existence of the something and also its existence, but not as belonging to its being-in-itself. Determinateness is thus constitution.',
  provenance: {
    sourceChunk: 'constitution-4',
    sourceOp: 'const-op-4-constitution-external',
  },
};

export const constOp5ConstitutionAlteration: LogicalOperation = {
  id: 'const-op-5-constitution-alteration',
  chunkId: 'constitution-5',
  label: 'Constitution II: external influences; alteration falls on constitution',
  clauses: [
    'constituted = inThis',
    'constituted = orThatWay',
    'theSomething = isCaught',
    'theSomething = upIn',
    'theSomething = externalInfluences',
    'theSomething = andIn',
    'theSomething = externalRelationships',
    'this = externalConnection',
    'this = onWhich',
    'this = theConstitution',
    'this = depends',
    'this = andThe',
    'this = beingDetermined',
    'this = throughAnOther',
    'this = appearAs',
    'this = somethingAccidental',
    'but = itIs',
    'but = theQuality',
    'but = ofTheSomething',
    'but = toBe',
    'but = givenOver',
    'but = toThis',
    'but = externality',
    'but = andTo',
    'but = haveA',
    'but = constitution',
    'in = soFarAs',
    'something = alters',
    'theAlteration = falls',
    'theAlteration = onTheSide',
    'theAlteration = ofItsConstitution',
    'theLatter = isThat',
    'theLatter = inTheSomething',
    'theLatter = which',
    'theLatter = becomesAnOther',
    'theSomething = itself',
    'theSomething = preservesItself',
    'theSomething = inTheAlteration',
    'theLatter = affects',
    'theLatter = only',
    'theLatter = thisUnstable',
    'theLatter = surface',
    'theLatter = ofTheSomething',
    'theLatter = otherness',
    'theLatter = notIts',
    'theLatter = determination',
  ],
  predicates: [
    { name: 'alteration', args: ['constitution'] },
  ],
  relations: [
    { predicate: 'falls', from: 'alteration', to: 'onConstitution' },
  ],
  candidateSummary: 'Constituted in this or that way, the something is caught up in external influences and in external relationships. This external connection on which the constitution depends, and the being determined through an other, appear as something accidental. But it is the quality of the something to be given over to this externality and to have a constitution. In so far as something alters, the alteration falls on the side of its constitution; the latter is that in the something which becomes an other. The something itself preserves itself in the alteration; the latter affects only this unstable surface of the something\'s otherness, not its determination.',
  provenance: {
    sourceChunk: 'constitution-5',
    sourceOp: 'const-op-5-constitution-alteration',
  },
};

export const constOp6DeterminationConstitutionPassOver: LogicalOperation = {
  id: 'const-op-6-determination-constitution-pass-over',
  chunkId: 'constitution-6',
  label: 'Determination and constitution: distinct but connected; pass over into each other',
  clauses: [
    'determination = andConstitution',
    'determination = areThus',
    'determination = distinctFrom',
    'determination = eachOther',
    'something = accordingTo',
    'something = itsDetermination',
    'something = isIndifferent',
    'something = toItsConstitution',
    'but = thatWhich',
    'but = theSomething',
    'but = hasInIt',
    'but = isThe',
    'but = middleTerm',
    'but = ofThis',
    'but = syllogism',
    'but = connecting',
    'but = theTwo',
    'but = determinationAndConstitution',
    'or = rather',
    'theBeingInTheSomething = showed',
    'theBeingInTheSomething = itself',
    'theBeingInTheSomething = toFall',
    'theBeingInTheSomething = apartInto',
    'theBeingInTheSomething = theseTwo',
    'theBeingInTheSomething = extremes',
    'theSimple = middleTerm',
    'theSimple = isDeterminateness',
    'theSimple = asSuch',
    'itsIdentity = belongsTo',
    'itsIdentity = determination',
    'itsIdentity = justAsWell',
    'itsIdentity = asTo',
    'itsIdentity = constitution',
    'but = determination',
    'but = passesOver',
    'but = intoConstitution',
    'but = onItsOwn',
    'but = andConstitution',
    'but = intoDetermination',
    'this = isImplied',
    'this = inWhat',
    'this = hasBeenSaid',
    'theConnection = upon',
    'theConnection = closerConsideration',
    'theConnection = isThis',
    'in = soFarAs',
    'that = which',
    'something = isInItself',
    'something = isAlso',
    'something = inIt',
    'theSomething = isAffected',
    'theSomething = withBeingForOther',
    'determination = isTherefore',
    'determination = open',
    'determination = asSuch',
    'determination = toThe',
    'determination = relation',
    'determination = withOther',
    'determinateness = isAt',
    'determinateness = theSameTime',
    'determinateness = moment',
    'but = itContains',
    'but = atTheSameTime',
    'but = theQualitative',
    'but = distinction',
    'but = ofBeing',
    'but = differentFrom',
    'but = beingInItself',
    'but = ofBeing',
    'but = theNegative',
    'but = ofTheSomething',
    'but = anotherExistence',
    'this = determinateness',
    'this = whichThus',
    'this = holds',
    'this = theOther',
    'this = inItself',
    'this = unitedWith',
    'this = theBeingInItself',
    'this = introduces',
    'this = otherness',
    'this = inTheLatter',
    'this = orIn',
    'this = determination',
    'this = andDetermination',
    'this = isThereby',
    'this = reducedTo',
    'this = constitution',
  ],
  predicates: [
    { name: 'passOver', args: ['determination', 'constitution'] },
  ],
  relations: [
    { predicate: 'passesOver', from: 'determination', to: 'constitution' },
    { predicate: 'passesOver', from: 'constitution', to: 'determination' },
  ],
  candidateSummary: 'Determination and constitution are thus distinct from each other; something, according to its determination, is indifferent to its constitution. But that which the something has in it is the middle term of this syllogism connecting the two, determination and constitution. Or, rather, the being-in-the-something showed itself to fall apart into these two extremes. The simple middle term is determinateness as such; its identity belongs to determination just as well as to constitution. But determination passes over into constitution on its own, and constitution into determination. This is implied in what has been said. The connection, upon closer consideration, is this: in so far as that which something is in itself is also in it, the something is affected with being-for-other; determination is therefore open, as such, to the relation with other. Determinateness is at the same time moment, but it contains at the same time the qualitative distinction of being different from being-in-itself, of being the negative of the something, another existence. This determinateness which thus holds the other in itself, united with the being-in-itself, introduces otherness in the latter or in determination, and determination is thereby reduced to constitution.',
  provenance: {
    sourceChunk: 'constitution-6',
    sourceOp: 'const-op-6-determination-constitution-pass-over',
  },
};

export const constOp7ConstitutionDepends: LogicalOperation = {
  id: 'const-op-7-constitution-depends',
  chunkId: 'constitution-7',
  label: 'Constitution passes over into determination; constitution depends on determination',
  clauses: [
    'conversely = theBeingForOther',
    'conversely = isolatedAs',
    'conversely = constitution',
    'conversely = andPosited',
    'conversely = onItsOwn',
    'conversely = isInIt',
    'conversely = theSameAs',
    'conversely = what',
    'conversely = theOther',
    'conversely = asSuch',
    'conversely = is',
    'conversely = theOther',
    'conversely = inIt',
    'conversely = thatIs',
    'conversely = theOther',
    'conversely = ofItself',
    'but = itConsequently',
    'but = isSelfReferring',
    'but = existence',
    'but = thusBeingInItself',
    'but = withA',
    'but = determinateness',
    'but = therefore',
    'but = determination',
    'consequently = inasmuchAs',
    'consequently = theTwo',
    'consequently = areAlso',
    'consequently = toBe',
    'consequently = heldApart',
    'constitution = which',
    'constitution = appearsToBe',
    'constitution = groundedIn',
    'constitution = somethingExternal',
    'constitution = inAnOther',
    'constitution = inGeneral',
    'constitution = alsoDepends',
    'constitution = onDetermination',
    'and = theDetermining',
    'and = fromOutside',
    'and = isAt',
    'and = theSameTime',
    'and = determinedBy',
    'and = theSomething',
    'and = ownImmanent',
    'and = determination',
    'and = further',
    'constitution = belongsTo',
    'constitution = thatWhich',
    'constitution = something',
    'constitution = isInItself',
    'something = alters',
    'something = alongWith',
    'something = itsConstitution',
  ],
  predicates: [
    { name: 'depends', args: ['constitution', 'determination'] },
  ],
  relations: [
    { predicate: 'depends', from: 'constitution', to: 'determination' },
  ],
  candidateSummary: 'Conversely, the being-for-other, isolated as constitution and posited on its own, is in it the same as what the other as such is, the other in it, that is, the other of itself; but it consequently is self-referring existence, thus being-in-itself with a determinateness, therefore determination. Consequently, inasmuch as the two are also to be held apart, constitution, which appears to be grounded in something external, in an other in general, also depends on determination, and the determining from outside is at the same time determined by the something\'s own immanent determination. And further, constitution belongs to that which something is in itself: something alters along with its constitution.',
  provenance: {
    sourceChunk: 'constitution-7',
    sourceOp: 'const-op-7-constitution-depends',
  },
};

export const constOp8AlterationPosited: LogicalOperation = {
  id: 'const-op-8-alteration-posited',
  chunkId: 'constitution-8',
  label: 'Alteration posited in something; negation immanent',
  clauses: [
    'this = altering',
    'this = ofSomething',
    'this = isNoLonger',
    'this = theFirst',
    'this = alteration',
    'this = ofSomething',
    'this = merelyIn',
    'this = accordanceWith',
    'this = itsBeingForOther',
    'theFirst = wasAn',
    'theFirst = alteration',
    'theFirst = onlyImplicitly',
    'theFirst = present',
    'theFirst = oneThat',
    'theFirst = belongedTo',
    'theFirst = theInner',
    'theFirst = concept',
    'now = theAlteration',
    'now = isAlso',
    'now = positedIn',
    'now = theSomething',
    'theSomething = itself',
    'theSomething = isFurther',
    'theSomething = determined',
    'and = negation',
    'and = isPosited',
    'and = asImmanent',
    'and = toIt',
    'and = asIts',
    'and = developed',
    'and = beingInItself',
  ],
  predicates: [
    { name: 'alteration', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'alteration', to: 'posited' },
  ],
  candidateSummary: 'This altering of something is no longer the first alteration of something merely in accordance with its being-for-other. The first was an alteration only implicitly present, one that belonged to the inner concept; now the alteration is also posited in the something. The something itself is further determined, and negation is posited as immanent to it, as its developed being-in-itself.',
  provenance: {
    sourceChunk: 'constitution-8',
    sourceOp: 'const-op-8-alteration-posited',
  },
};

export const constOp9TransitionSublation: LogicalOperation = {
  id: 'const-op-9-transition-sublation',
  chunkId: 'constitution-9',
  label: 'Transition I: sublation → two somethings; negation immanent',
  clauses: [
    'theTransition = ofDetermination',
    'theTransition = andConstitution',
    'theTransition = intoEachOther',
    'theTransition = isAtFirst',
    'theTransition = theSublation',
    'theTransition = ofTheir',
    'theTransition = distinction',
    'and = existence',
    'and = orSomething',
    'and = inGeneral',
    'and = isThereby',
    'and = posited',
    'moreover = since',
    'moreover = thisSomething',
    'moreover = inGeneral',
    'moreover = resultsFrom',
    'moreover = aDistinction',
    'moreover = thatAlso',
    'moreover = includes',
    'moreover = qualitativeOtherness',
    'moreover = withinIt',
    'there = areTwo',
    'there = somethings',
    'but = these',
    'but = are',
    'but = withRespectTo',
    'but = eachOther',
    'but = notJust',
    'but = othersInGeneral',
    'but = soThat',
    'but = thisNegation',
    'but = wouldStill',
    'but = beAbstract',
    'but = andWould',
    'but = occurOnly',
    'but = inThe',
    'but = comparison',
    'but = ofTheTwo',
    'but = rather',
    'but = theNegation',
    'but = nowIs',
    'but = immanentTo',
    'but = theSomethings',
    'as = existing',
    'they = areIndifferent',
    'they = toEachOther',
    'but = this',
    'but = theirAffirmation',
    'but = isNoLonger',
    'but = immediate',
    'each = refers',
    'each = itselfTo',
    'each = itself',
    'each = throughThe',
    'each = intermediary',
    'each = ofThe',
    'each = sublation',
    'each = ofTheOtherness',
    'each = whichIn',
    'each = determination',
    'each = isReflected',
    'each = intoThe',
    'each = inItselfness',
  ],
  predicates: [
    { name: 'sublation', args: ['distinction'] },
  ],
  relations: [
    { predicate: 'results', from: 'sublation', to: 'twoSomethings' },
  ],
  candidateSummary: 'The transition of determination and constitution into each other is at first the sublation of their distinction, and existence or something in general is thereby posited; moreover, since this something in general results from a distinction that also includes qualitative otherness within it, there are two somethings. But these are, with respect to each other, not just others in general, so that this negation would still be abstract and would occur only in the comparison of the two; rather the negation now is immanent to the somethings. As existing, they are indifferent to each other, but this, their affirmation, is no longer immediate: each refers itself to itself through the intermediary of the sublation of the otherness which in determination is reflected into the in-itselfness.',
  provenance: {
    sourceChunk: 'constitution-9',
    sourceOp: 'const-op-9-transition-sublation',
  },
};

export const constOp10TransitionLimit: LogicalOperation = {
  id: 'const-op-10-transition-limit',
  chunkId: 'constitution-10',
  label: 'Transition II: something behaves to other through itself; negation of other = quality; limit',
  clauses: [
    'something = behaves',
    'something = inThisWay',
    'something = inRelation',
    'something = toTheOther',
    'something = throughItself',
    'since = otherness',
    'since = isPosited',
    'since = inIt',
    'since = asIts',
    'since = ownMoment',
    'itsInItselfness = holds',
    'itsInItselfness = negation',
    'itsInItselfness = inItself',
    'and = itNow',
    'and = hasIts',
    'and = affirmativeExistence',
    'and = throughIts',
    'and = intermediary',
    'and = alone',
    'but = theOther',
    'but = isAlso',
    'but = qualitatively',
    'but = distinguishedFrom',
    'but = thisAffirmative',
    'but = existence',
    'but = andIs',
    'but = thusPosited',
    'but = outside',
    'but = theSomething',
    'theNegation = ofItsOther',
    'theNegation = isOnly',
    'theNegation = theQuality',
    'theNegation = ofTheSomething',
    'for = itIs',
    'for = inThis',
    'for = sublation',
    'for = ofItsOther',
    'for = thatIt',
    'for = isSomething',
    'theOther = forItsPart',
    'theOther = truly',
    'theOther = confronts',
    'theOther = anExistence',
    'theOther = onlyWith',
    'theOther = thisSublation',
    'it = confronts',
    'it = theFirst',
    'it = something',
    'it = onlyExternally',
    'or = since',
    'theTwo = areIn',
    'theTwo = fact',
    'theTwo = inherently',
    'theTwo = joinedTogether',
    'that = is',
    'that = accordingTo',
    'that = theirConcept',
    'their = connectedness',
    'their = consistsIn',
    'their = this',
    'that = existence',
    'that = hasPassed',
    'that = overInto',
    'that = otherness',
    'that = something',
    'that = intoOther',
    'that = something',
    'that = isJust',
    'that = asMuch',
    'that = anOther',
    'that = asTheOther',
    'that = is',
    'now = inSoFarAs',
    'now = theInItselfness',
    'now = isThe',
    'now = nonBeing',
    'now = ofTheOtherness',
    'now = thatIs',
    'now = containedInIt',
    'now = butIs',
    'now = atTheSameTime',
    'now = alsoDistinct',
    'now = asExistent',
    'something = isItself',
    'something = negation',
    'something = theCeasing',
    'something = toBe',
    'something = ofAnOther',
    'something = inIt',
    'it = isPosited',
    'it = asBehaving',
    'it = negatively',
    'it = inRelation',
    'it = toTheOther',
    'it = andIn',
    'it = soDoing',
    'it = preservingItself',
    'this = other',
    'this = theInItselfness',
    'this = ofTheSomething',
    'this = asNegation',
    'this = ofTheNegation',
    'this = isThe',
    'this = something',
    'this = beingInItself',
    'and = thisSublation',
    'and = isAs',
    'and = simpleNegation',
    'and = atTheSameTime',
    'and = inIt',
    'and = namely',
    'and = asIts',
    'and = negation',
    'and = ofTheOther',
    'and = something',
    'and = externalToIt',
    'it = isOne',
    'it = determinateness',
    'it = ofTheTwo',
    'it = somethings',
    'it = that',
    'it = onThe',
    'it = oneHand',
    'it = asNegation',
    'it = ofTheNegation',
    'it = isIdentical',
    'it = withThe',
    'it = inItselfness',
    'it = ofThe',
    'it = somethings',
    'it = andAlso',
    'it = onThe',
    'it = otherHand',
    'it = since',
    'it = theseNegations',
    'it = areTo',
    'it = eachOther',
    'it = asOther',
    'it = somethings',
    'it = joins',
    'it = themTogether',
    'it = ofTheir',
    'it = ownAccord',
    'it = and',
    'it = since',
    'it = eachNegation',
    'it = negates',
    'it = theOther',
    'it = equally',
    'it = separates',
    'it = them',
    'this = determinateness',
    'this = isLimit',
  ],
  predicates: [
    { name: 'limit', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'determinateness', to: 'limit' },
  ],
  candidateSummary: 'Something behaves in this way in relation to the other through itself; since otherness is posited in it as its own moment, its in-itselfness holds negation in itself, and it now has its affirmative existence through its intermediary alone. But the other is also qualitatively distinguished from this affirmative existence and is thus posited outside the something. The negation of its other is only the quality of the something, for it is in this sublation of its other that it is something. The other, for its part, truly confronts an existence only with this sublation; it confronts the first something only externally, or, since the two are in fact inherently joined together, that is, according to their concept, their connectedness consists in this, that existence has passed over into otherness, something into other; that something is just as much an other as the other is. Now in so far as the in-itselfness is the non-being of the otherness that is contained in it but is at the same time also distinct as existent, something is itself negation, the ceasing to be of an other in it; it is posited as behaving negatively in relation to the other and in so doing preserving itself. This other, the in-itselfness of the something as negation of the negation, is the something\'s being-in-itself, and this sublation is as simple negation at the same time in it, namely, as its negation of the other something external to it. It is one determinateness of the two somethings that, on the one hand, as negation of the negation, is identical with the in-itselfness of the somethings, and also, on the other hand, since these negations are to each other as other somethings, joins them together of their own accord and, since each negation negates the other, equally separates them. This determinateness is limit.',
  provenance: {
    sourceChunk: 'constitution-10',
    sourceOp: 'const-op-10-transition-limit',
  },
};

export const constOp11LimitNonBeing: LogicalOperation = {
  id: 'const-op-11-limit-non-being',
  chunkId: 'constitution-11',
  label: 'Limit I: non-being of other and of something; mediation',
  clauses: [
    'something = isTherefore',
    'something = immediate',
    'something = selfReferring',
    'something = existence',
    'something = andAtFirst',
    'something = itHas',
    'something = aLimit',
    'something = withRespectTo',
    'something = anOther',
    'limit = isThe',
    'limit = nonBeing',
    'limit = ofTheOther',
    'limit = notOf',
    'limit = theSomething',
    'limit = itself',
    'in = limit',
    'something = marks',
    'something = theBoundary',
    'something = ofItsOther',
    'but = other',
    'but = isItself',
    'but = aSomething',
    'but = inGeneral',
    'theLimit = thatSomething',
    'theLimit = hasWith',
    'theLimit = respectTo',
    'theLimit = anOther',
    'theLimit = is',
    'theLimit = therefore',
    'theLimit = alsoThe',
    'theLimit = limit',
    'theLimit = ofTheOther',
    'theLimit = asA',
    'theLimit = something',
    'it = isThe',
    'it = limit',
    'it = ofThis',
    'it = something',
    'it = inVirtue',
    'it = ofWhich',
    'it = theSomething',
    'it = holds',
    'it = theFirst',
    'it = something',
    'it = asIts',
    'it = other',
    'it = awayFrom',
    'it = itself',
    'it = orIs',
    'it = aNonBeing',
    'it = ofThat',
    'it = something',
    'theLimit = isThus',
    'theLimit = notOnly',
    'theLimit = theNonBeing',
    'theLimit = ofTheOther',
    'theLimit = butOf',
    'theLimit = theOne',
    'theLimit = something',
    'theLimit = justAs',
    'theLimit = ofTheOther',
    'theLimit = andConsequently',
    'theLimit = ofTheSomething',
    'theLimit = inGeneral',
  ],
  predicates: [
    { name: 'limit', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'limit', to: 'nonBeingOfOther' },
    { predicate: 'is', from: 'limit', to: 'nonBeingOfSomething' },
  ],
  candidateSummary: 'Something is therefore immediate, self-referring existence and at first it has a limit with respect to an other; limit is the non-being of the other, not of the something itself; in limit, something marks the boundary of its other. But other is itself a something in general. The limit that something has with respect to an other is, therefore, also the limit of the other as a something; it is the limit of this something in virtue of which the something holds the first something as its other away from itself, or is a non-being of that something. The limit is thus not only the non-being of the other, but of the one something just as of the other, and consequently of the something in general.',
  provenance: {
    sourceChunk: 'constitution-11',
    sourceOp: 'const-op-11-limit-non-being',
  },
};

export const constOp12LimitMediation: LogicalOperation = {
  id: 'const-op-12-limit-mediation',
  chunkId: 'constitution-12',
  label: 'Limit II: through limit something is; limit = mediation',
  clauses: [
    'but = theLimit',
    'but = isEqually',
    'but = essentially',
    'but = theNonBeing',
    'but = ofTheOther',
    'thus = through',
    'thus = itsLimit',
    'thus = something',
    'thus = atTheSameTime',
    'thus = is',
    'in = limiting',
    'something = isOf',
    'something = course',
    'something = thereby',
    'something = reducedTo',
    'something = beingLimited',
    'something = itself',
    'but = asThe',
    'but = ceasing',
    'but = ofTheOther',
    'but = inIt',
    'but = itsLimit',
    'but = isAt',
    'but = theSameTime',
    'but = itselfOnly',
    'but = theBeing',
    'but = ofTheSomething',
    'this = something',
    'this = isWhat',
    'this = itIs',
    'this = byVirtue',
    'this = ofIt',
    'this = hasIts',
    'this = qualityInIt',
    'this = relation',
    'this = isThe',
    'this = external',
    'this = appearance',
    'this = ofTheFact',
    'this = thatLimit',
    'this = isSimple',
    'this = negation',
    'this = orThe',
    'this = firstNegation',
    'this = whereas',
    'this = theOther',
    'this = isAt',
    'this = theSameTime',
    'this = theNegation',
    'this = ofTheNegation',
    'this = theInItselfness',
    'this = ofTheSomething',
    'something = asAn',
    'something = immediateExistence',
    'something = isTherefore',
    'something = theLimit',
    'something = withRespectTo',
    'something = anotherSomething',
    'but = itHas',
    'but = thisLimit',
    'but = inIt',
    'but = andIs',
    'but = something',
    'but = throughThe',
    'but = mediation',
    'but = ofThat',
    'but = limit',
    'but = whichIs',
    'but = justAsMuch',
    'but = itsNonBeing',
    'theLimit = isThe',
    'theLimit = mediation',
    'theLimit = inVirtue',
    'theLimit = ofWhich',
    'theLimit = something',
    'theLimit = andOther',
    'theLimit = each',
    'theLimit = both',
    'theLimit = is',
    'theLimit = andIs',
    'theLimit = not',
  ],
  predicates: [
    { name: 'mediation', args: ['limit'] },
  ],
  relations: [
    { predicate: 'is', from: 'limit', to: 'mediation' },
  ],
  candidateSummary: 'But the limit is equally, essentially, the non-being of the other; thus, through its limit, something at the same time is. In limiting, something is of course thereby reduced to being limited itself; but, as the ceasing of the other in it, its limit is at the same time itself only the being of the something; this something is what it is by virtue of it, has its quality in it. This relation is the external appearance of the fact that limit is simple negation or the first negation, whereas the other is, at the same time, the negation of the negation, the in-itselfness of the something. Something, as an immediate existence, is therefore the limit with respect to another something; but it has this limit in it and is something through the mediation of that limit, which is just as much its non-being. The limit is the mediation in virtue of which something and other each both is and is not.',
  provenance: {
    sourceChunk: 'constitution-12',
    sourceOp: 'const-op-12-limit-mediation',
  },
};

export const constOp13LimitMiddlePoint: LogicalOperation = {
  id: 'const-op-13-limit-middle-point',
  chunkId: 'constitution-13',
  label: 'Limit III: existence outside/inside limit; limit as middle point',
  clauses: [
    'now = inSoFarAs',
    'now = something',
    'now = inItsLimit',
    'now = bothIs',
    'now = andIsNot',
    'now = andThese',
    'now = moments',
    'now = areAn',
    'now = immediate',
    'now = qualitativeDistinction',
    'theNonExistence = andThe',
    'theNonExistence = existence',
    'theNonExistence = ofTheSomething',
    'theNonExistence = fallOutside',
    'theNonExistence = eachOther',
    'something = hasIts',
    'something = existence',
    'something = outside',
    'something = itsLimit',
    'something = or',
    'something = asRepresentation',
    'something = wouldAlso',
    'something = haveIt',
    'something = insideIt',
    'in = theSameWay',
    'theOther = too',
    'theOther = since',
    'theOther = itIs',
    'theOther = something',
    'theOther = hasIt',
    'theOther = outsideIt',
    'theLimit = isThe',
    'theLimit = middlePoint',
    'theLimit = between',
    'theLimit = theTwo',
    'theLimit = atWhich',
    'theLimit = theyLeave',
    'theLimit = off',
    'they = haveExistence',
    'they = beyond',
    'they = eachOther',
    'they = beyond',
    'they = theirLimit',
    'theLimit = asThe',
    'theLimit = nonBeing',
    'theLimit = ofEach',
    'theLimit = isThe',
    'theLimit = other',
    'theLimit = ofBoth',
    'it = isIn',
    'it = accordanceWith',
    'it = thisDifference',
    'it = ofTheSomething',
    'it = fromItsLimit',
    'it = thatThe',
    'it = line',
    'it = appearsAs',
    'it = line',
    'it = outside',
    'it = itsLimit',
    'it = thePoint',
    'thePlane = asPlane',
    'thePlane = outside',
    'thePlane = theLine',
    'theSolid = asSolid',
    'theSolid = only',
    'theSolid = outside',
    'theSolid = itsLimiting',
    'theSolid = plane',
    'this = isThe',
    'this = aspect',
    'this = ofLimit',
    'this = thatFirst',
    'this = occursTo',
    'this = figurative',
    'this = representation',
    'this = theSelfExternalBeing',
    'this = ofTheConcept',
    'this = andIs',
    'this = alsoMost',
    'this = commonly',
    'this = assumed',
    'this = inThe',
    'this = context',
    'this = ofSpatial',
    'this = objects',
  ],
  predicates: [
    { name: 'middlePoint', args: ['limit'] },
  ],
  relations: [
    { predicate: 'is', from: 'limit', to: 'middlePoint' },
  ],
  candidateSummary: 'Now in so far as something in its limit both is and is not, and these moments are an immediate, qualitative distinction, the non-existence and the existence of the something fall outside each other. Something has its existence outside its limit (or, as representation would also have it, inside it); in the same way the other, too, since it is something, has it outside it. The limit is the middle point between the two at which they leave off. They have existence beyond each other, beyond their limit; the limit, as the non-being of each, is the other of both. It is in accordance with this difference of the something from its limit that the line appears as line outside its limit, the point; the plane as plane outside the line; the solid as solid only outside its limiting plane. This is the aspect of limit that first occurs to figurative representation (the self-external-being of the concept) and is also most commonly assumed in the context of spatial objects.',
  provenance: {
    sourceChunk: 'constitution-13',
    sourceOp: 'const-op-13-limit-middle-point',
  },
};

export const constOp14LimitPrinciple: LogicalOperation = {
  id: 'const-op-14-limit-principle',
  chunkId: 'constitution-14',
  label: 'Limit IV: something outside limit = existence in general; limit as principle',
  clauses: [
    'but = further',
    'something = asItIs',
    'something = outside',
    'something = theLimit',
    'something = asThe',
    'something = unlimitedSomething',
    'something = isOnly',
    'something = existence',
    'something = inGeneral',
    'as = such',
    'it = isNot',
    'it = distinguishedFrom',
    'it = itsOther',
    'it = isOnly',
    'it = existence',
    'it = and',
    'it = therefore',
    'it = itAnd',
    'it = itsOther',
    'it = haveThe',
    'it = sameDetermination',
    'each = isOnly',
    'each = something',
    'each = inGeneral',
    'each = orEach',
    'each = isOther',
    'each = andSo',
    'each = both',
    'each = areThe',
    'each = same',
    'but = this',
    'but = theirAt',
    'but = first',
    'but = immediateExistence',
    'but = isNow',
    'but = positedIn',
    'but = them',
    'but = asLimit',
    'in = it',
    'both = are',
    'both = what',
    'both = theyAre',
    'both = distinctFrom',
    'both = eachOther',
    'but = it',
    'but = isAlso',
    'but = equally',
    'but = their',
    'but = common',
    'but = distinguishedness',
    'but = theUnity',
    'but = andThe',
    'but = distinguishedness',
    'but = ofBoth',
    'but = justLike',
    'but = existence',
    'this = double',
    'this = identity',
    'this = ofTheTwo',
    'this = existence',
    'this = andLimit',
    'this = contains',
    'this = this',
    'that = something',
    'that = hasExistence',
    'that = onlyIn',
    'that = limit',
    'that = andThat',
    'that = since',
    'that = limit',
    'that = andImmediate',
    'that = existence',
    'that = areEach',
    'that = atThe',
    'that = sameTime',
    'that = theNegative',
    'that = ofEachOther',
    'theSomething = which',
    'theSomething = isNow',
    'theSomething = onlyIn',
    'theSomething = itsLimit',
    'theSomething = equally',
    'theSomething = separates',
    'theSomething = itselfFrom',
    'theSomething = itself',
    'theSomething = points',
    'theSomething = beyond',
    'theSomething = itselfTo',
    'theSomething = itsNonBeing',
    'theSomething = andDeclares',
    'theSomething = itTo',
    'theSomething = beIts',
    'theSomething = being',
    'theSomething = andSo',
    'theSomething = itPasses',
    'theSomething = overInto',
    'theSomething = it',
    'to = apply',
    'to = this',
    'to = toThe',
    'to = preceding',
    'to = example',
    'the = one',
    'the = determination',
    'the = isThis',
    'that = something',
    'that = isWhat',
    'that = itIs',
    'that = onlyIn',
    'that = itsLimit',
    'therefore = thePoint',
    'therefore = isThe',
    'therefore = limit',
    'therefore = ofLine',
    'therefore = notBecause',
    'therefore = theLatter',
    'therefore = just',
    'therefore = ceases',
    'therefore = atThe',
    'therefore = point',
    'therefore = andHas',
    'therefore = existence',
    'therefore = outsideIt',
    'the = line',
    'the = isThe',
    'the = limit',
    'the = ofPlane',
    'the = notBecause',
    'the = plane',
    'the = just',
    'the = ceases',
    'the = atIt',
    'the = andThe',
    'the = same',
    'the = goesFor',
    'the = plane',
    'the = asThe',
    'the = limit',
    'the = ofSolid',
    'rather = atThe',
    'rather = point',
    'rather = theLine',
    'rather = alsoBegins',
    'rather = thePoint',
    'rather = isIts',
    'rather = absoluteBeginning',
    'rather = andIf',
    'rather = theLine',
    'rather = isRepresented',
    'rather = asUnlimited',
    'rather = onBoth',
    'rather = itsTwo',
    'rather = sides',
    'rather = or',
    'rather = asIs',
    'rather = said',
    'rather = asExtended',
    'rather = toInfinity',
    'rather = thePoint',
    'rather = still',
    'rather = constitutes',
    'rather = itsElement',
    'just = asThe',
    'just = line',
    'just = constitutes',
    'just = theElement',
    'just = ofThe',
    'just = plane',
    'just = andThe',
    'just = plane',
    'just = that',
    'just = ofThe',
    'just = solid',
    'these = limits',
    'these = areThe',
    'these = principle',
    'these = ofThat',
    'these = which',
    'these = theyDelimit',
    'just = asOne',
    'just = forInstance',
    'just = isAs',
    'just = hundredth',
    'just = theLimit',
    'just = butAlso',
    'just = theElement',
    'just = ofThe',
    'just = whole',
    'just = hundred',
  ],
  predicates: [
    { name: 'principle', args: ['limit'] },
  ],
  relations: [
    { predicate: 'is', from: 'limit', to: 'principle' },
  ],
  candidateSummary: 'But further, something as it is outside the limit, as the unlimited something, is only existence in general. As such, it is not distinguished from its other; it is only existence and, therefore, it and its other have the same determination; each is only something in general or each is other; and so both are the same. But this, their at first immediate existence, is now posited in them as limit: in it both are what they are, distinct from each other. But it is also equally their common distinguishedness, the unity and the distinguishedness of both, just like existence. This double identity of the two, existence and limit, contains this: that something has existence only in limit, and that, since limit and immediate existence are each at the same time the negative of each other, the something, which is now only in its limit, equally separates itself from itself, points beyond itself to its non-being and declares it to be its being, and so it passes over into it. To apply this to the preceding example, the one determination is this: that something is what it is only in its limit. Therefore, the point is the limit of line, not because the latter just ceases at the point and has existence outside it; the line is the limit of plane, not because the plane just ceases at it; and the same goes for the plane as the limit of solid. Rather, at the point the line also begins; the point is its absolute beginning, and if the line is represented as unlimited on both its two sides, or, as is said, as extended to infinity, the point still constitutes its element, just as the line constitutes the element of the plane, and the plane that of the solid. These limits are the principle of that which they delimit; just as one, for instance, is as hundredth the limit, but also the element, of the whole hundred.',
  provenance: {
    sourceChunk: 'constitution-14',
    sourceOp: 'const-op-14-limit-principle',
  },
};

export const constOp15LimitUnrest: LogicalOperation = {
  id: 'const-op-15-limit-unrest',
  chunkId: 'constitution-15',
  label: 'Limit V: unrest/contradiction; dialectic of point/line/plane',
  clauses: [
    'the = other',
    'the = determination',
    'the = isThe',
    'the = unrest',
    'the = ofTheSomething',
    'the = inItsLimit',
    'the = inWhich',
    'the = itIs',
    'the = immanent',
    'the = theContradiction',
    'the = thatPropels',
    'the = itBeyond',
    'the = itself',
    'thus = thePoint',
    'thus = isThis',
    'thus = dialectic',
    'thus = ofItself',
    'thus = becomingLine',
    'the = line',
    'the = theDialectic',
    'the = ofBecoming',
    'the = plane',
    'the = plane',
    'the = ofBecoming',
    'the = totalSpace',
    'a = second',
    'a = definition',
    'a = isGiven',
    'a = ofLine',
    'a = plane',
    'a = andWhole',
    'a = space',
    'a = which',
    'a = hasThe',
    'a = line',
    'a = comeToBe',
    'a = throughThe',
    'a = movement',
    'a = ofThePoint',
    'the = plane',
    'the = throughThe',
    'the = movement',
    'the = ofThe',
    'the = line',
    'the = andSoForth',
    'this = movement',
    'this = ofThePoint',
    'this = theLine',
    'this = andSoForth',
    'this = isHowever',
    'this = viewedAs',
    'this = somethingAccidental',
    'this = orAs',
    'this = movement',
    'this = onlyIn',
    'this = figurative',
    'this = representation',
    'in = fact',
    'however = this',
    'however = view',
    'however = isTaken',
    'however = backBy',
    'however = supposing',
    'however = thatThe',
    'however = determinations',
    'however = fromWhich',
    'however = theLine',
    'however = andSoForth',
    'however = originate',
    'however = areTheir',
    'however = elements',
    'however = andPrinciples',
    'however = andThese',
    'however = areAt',
    'however = theSameTime',
    'however = nothingElse',
    'however = butTheir',
    'however = limits',
    'the = coming',
    'the = toBe',
    'the = isNot',
    'the = considered',
    'the = asAccidental',
    'the = orOnly',
    'the = asRepresented',
    'that = thePoint',
    'that = theLine',
    'that = thePlane',
    'that = arePer',
    'that = se',
    'that = selfContradictory',
    'that = beginnings',
    'that = whichOn',
    'that = theirOwn',
    'that = repel',
    'that = themselvesFrom',
    'that = themselves',
    'that = andConsequently',
    'that = thatThe',
    'that = point',
    'that = passesOver',
    'that = fromItself',
    'that = intoThe',
    'that = line',
    'that = throughIts',
    'that = concept',
    'that = movesIn',
    'that = itself',
    'that = andMakes',
    'that = theLine',
    'that = comeToBe',
    'that = andSoOn',
    'all = this',
    'all = liesIn',
    'all = theConcept',
    'all = ofTheLimit',
    'all = whichIs',
    'all = immanentIn',
    'all = theSomething',
    'the = application',
    'the = itself',
    'the = however',
    'the = belongsTo',
    'the = theTreatment',
    'the = ofSpace',
    'as = an',
    'as = indication',
    'as = ofIt',
    'as = here',
    'we = canSay',
    'we = thatThe',
    'we = point',
    'we = isThe',
    'we = totallyAbstract',
    'we = limit',
    'we = butIn',
    'we = aDeterminate',
    'we = existence',
    'this = existence',
    'this = isStill',
    'this = takenIn',
    'this = totalAbstraction',
    'this = itIs',
    'this = theSoCalled',
    'this = absolute',
    'this = thatIs',
    'this = abstractSpace',
    'this = theAbsolutely',
    'this = continuous',
    'this = beingOutside',
    'this = oneAnother',
    'inasmuch = as',
    'inasmuch = theLimit',
    'inasmuch = isNot',
    'inasmuch = abstractNegation',
    'inasmuch = butIs',
    'inasmuch = ratherIn',
    'inasmuch = thisExistence',
    'inasmuch = inasmuchAs',
    'inasmuch = itIs',
    'inasmuch = spatialDeterminateness',
    'the = point',
    'the = isSpatial',
    'the = isThe',
    'the = contradiction',
    'the = ofAbstract',
    'the = negation',
    'the = andContinuity',
    'the = andIs',
    'the = forThatReason',
    'the = theTransition',
    'the = asIt',
    'the = occurs',
    'the = andHas',
    'the = alreadyOccurred',
    'the = intoThe',
    'the = line',
    'the = andSoForth',
    'and = so',
    'there = isNo',
    'there = point',
    'there = justAs',
    'there = thereIs',
    'there = noLine',
    'there = orPlane',
  ],
  predicates: [
    { name: 'unrest', args: ['limit'] },
    { name: 'contradiction', args: ['limit'] },
  ],
  relations: [
    { predicate: 'propels', from: 'contradiction', to: 'beyondItself' },
  ],
  candidateSummary: 'The other determination is the unrest of the something in its limit in which it is immanent, the contradiction that propels it beyond itself. Thus the point is this dialectic of itself becoming line; the line, the dialectic of becoming plane; the plane, of becoming total space. A second definition is given of line, plane, and whole space which has the line come to be through the movement of the point; the plane through the movement of the line, and so forth. This movement of the point, the line, and so forth, is however viewed as something accidental, or as movement only in figurative representation. In fact, however, this view is taken back by supposing that the determinations from which the line, and so forth, originate are their elements and principles, and these are, at the same time, nothing else but their limits; the coming to be is not considered as accidental or only as represented. That the point, the line, the plane, are per se self-contradictory beginnings which on their own repel themselves from themselves, and consequently that the point passes over from itself into the line through its concept, moves in itself and makes the line come to be, and so on all this lies in the concept of the limit which is immanent in the something. The application itself, however, belongs to the treatment of space; as an indication of it here, we can say that the point is the totally abstract limit, but in a determinate existence; this existence is still taken in total abstraction, it is the so-called absolute, that is, abstract space, the absolutely continuous being-outside-one-another. Inasmuch as the limit is not abstract negation but is rather in this existence, inasmuch as it is spatial determinateness, the point is spatial, is the contradiction of abstract negation and continuity and is, for that reason, the transition as it occurs and has already occurred into the line, and so forth. And so there is no point, just as there is no line or plane.',
  provenance: {
    sourceChunk: 'constitution-15',
    sourceOp: 'const-op-15-limit-unrest',
  },
};

export const constOp16Conclusion: LogicalOperation = {
  id: 'const-op-16-conclusion',
  chunkId: 'constitution-16',
  label: 'Conclusion: something with immanent limit = finite',
  clauses: [
    'theSomething = posited',
    'theSomething = withIts',
    'theSomething = immanentLimit',
    'theSomething = asThe',
    'theSomething = contradiction',
    'theSomething = ofItself',
    'theSomething = byVirtue',
    'theSomething = ofWhich',
    'theSomething = itIs',
    'theSomething = directed',
    'theSomething = andDriven',
    'theSomething = outAnd',
    'theSomething = beyondItself',
    'theSomething = theFinite',
  ],
  predicates: [
    { name: 'finite', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'finite' },
  ],
  candidateSummary: 'The something, posited with its immanent limit as the contradiction of itself by virtue of which it is directed and driven out and beyond itself, the finite.',
  provenance: {
    sourceChunk: 'constitution-16',
    sourceOp: 'const-op-16-conclusion',
  },
};

export const constitutionOperations: LogicalOperation[] = [
  constOp1Introduction,
  constOp2DeterminationDefinition,
  constOp3DeterminationExample,
  constOp4ConstitutionExternal,
  constOp5ConstitutionAlteration,
  constOp6DeterminationConstitutionPassOver,
  constOp7ConstitutionDepends,
  constOp8AlterationPosited,
  constOp9TransitionSublation,
  constOp10TransitionLimit,
  constOp11LimitNonBeing,
  constOp12LimitMediation,
  constOp13LimitMiddlePoint,
  constOp14LimitPrinciple,
  constOp15LimitUnrest,
  constOp16Conclusion,
];

