/**
 * Logical Operations: Existence
 *
 * Existence - the determinate being that emerges from Becoming.
 * This is the CPU's first concrete moment: Being → Nothing → Becoming → Existence.
 *
 * Dialectical Movement:
 * - Existence from becoming: simple oneness, immediate
 * - Dasein: being with non-being, determinateness as such
 * - Quality: reality and negation
 * - Something: negation of negation, beginning of subject
 */

import type { LogicalOperation } from '../../../../types';

// ============================================================================
// EXISTENCE
// ============================================================================

export const existOp1Outline: LogicalOperation = {
  id: 'exist-op-1-outline',
  chunkId: 'existence-1',
  label: 'Outline: determinateness → quality (reality|negation) → something (existent)',
  clauses: [
    'inExistence = asSuch',
    'itsDeterminateness = isFirst',
    'itsDeterminateness = toBeDistinguished',
    'itsDeterminateness = asQuality',
    'theLatter = however',
    'theLatter = isToBeTaken',
    'theLatter = inBoth',
    'theLatter = twoDeterminations',
    'theLatter = ofExistence',
    'theLatter = asRealityAndNegation',
    'in = theseDeterminacies',
    'however = existence',
    'however = isEquallyReflected',
    'however = intoItself',
    'and = asSoReflected',
    'it = isPositedAs',
    'it = something',
    'it = anExistent',
  ],
  predicates: [
    { name: 'outline', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'existence', to: 'determinateness' },
  ],
  candidateSummary: 'In existence (a) as such, its determinateness is first (b) to be distinguished as quality. The latter, however, is to be taken in both the two determinations of existence as reality and negation. In these determinacies, however, existence is equally reflected into itself, and, as so reflected, it is posited as (c) something, an existent.',
  provenance: {
    sourceChunk: 'existence-1',
    sourceOp: 'exist-op-1-outline',
  },
};

export const existOp2ExistenceFromBecoming: LogicalOperation = {
  id: 'exist-op-2-existence-from-becoming',
  chunkId: 'existence-2',
  label: 'Existence from becoming: simple oneness; immediate (becoming behind it)',
  clauses: [
    'existence = proceedsFromBecoming',
    'it = isTheSimpleOneness',
    'it = ofBeingAndNothing',
    'onAccount = ofThisSimplicity',
    'it = hasTheForm',
    'it = ofAnImmediate',
    'itsMediation = theBecoming',
    'itsMediation = liesBehindIt',
    'it = hasSublatedItself',
    'existence = thereforeAppears',
    'existence = asAFirst',
    'existence = fromWhich',
    'existence = theForwardMove',
    'existence = isMade',
    'it = isAtFirst',
    'it = inTheOneSidedDetermination',
    'it = ofBeing',
    'theOtherDetermination = whichItContains',
    'theOtherDetermination = nothing',
    'theOtherDetermination = willLikewiseComeUp',
    'theOtherDetermination = inIt',
    'theOtherDetermination = inContrastToTheFirst',
  ],
  predicates: [
    { name: 'simpleOneness', args: ['existence'] },
  ],
  relations: [
    { predicate: 'proceeds', from: 'existence', to: 'fromBecoming' },
  ],
  candidateSummary: 'Existence proceeds from becoming. It is the simple oneness of being and nothing. On account of this simplicity, it has the form of an immediate. Its mediation, the becoming, lies behind it; it has sublated itself, and existence therefore appears as a first from which the forward move is made. It is at first in the one-sided determination of being; the other determination which it contains, nothing, will likewise come up in it, in contrast to the first.',
  provenance: {
    sourceChunk: 'existence-2',
    sourceOp: 'exist-op-2-existence-from-becoming',
  },
};

export const existOp3Dasein: LogicalOperation = {
  id: 'exist-op-3-dasein',
  chunkId: 'existence-3',
  label: '"Da"-sein: being with non-being; determinateness as such (in form of being)',
  clauses: [
    'it = isNotMereBeing',
    'it = butExistence',
    'it = orDasein',
    'according = toItsEtymology',
    'it = isBeing',
    'it = sein',
    'it = inACertainPlace',
    'it = da',
    'but = theRepresentation',
    'but = ofSpace',
    'but = doesNotBelongHere',
    'as = itFollowsUponBecoming',
    'existence = isInGeneral',
    'existence = beingWithANonBeing',
    'so = thatThisNonBeing',
    'so = isTakenUp',
    'so = intoSimpleUnity',
    'so = withBeing',
    'nonBeing = thusTakenUp',
    'nonBeing = intoBeing',
    'nonBeing = withTheResult',
    'nonBeing = thatTheConcreteWhole',
    'nonBeing = isInTheForm',
    'nonBeing = ofBeing',
    'nonBeing = ofImmediacy',
    'nonBeing = constitutesDeterminateness',
    'nonBeing = asSuch',
  ],
  predicates: [
    { name: 'dasein', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'existence', to: 'dasein' },
  ],
  candidateSummary: 'It is not mere being but existence, or Dasein [in German]; according to its [German] etymology, it is being (Sein) in a certain place (da). But the representation of space does not belong here. As it follows upon becoming, existence is in general being with a non-being, so that this non-being is taken up into simple unity with being. Non-being thus taken up into being with the result that the concrete whole is in the form of being, of immediacy, constitutes determinateness as such.',
  provenance: {
    sourceChunk: 'existence-3',
    sourceOp: 'exist-op-3-dasein',
  },
};

export const existOp4ReflectionVsPosited: LogicalOperation = {
  id: 'exist-op-4-reflection-vs-posited',
  chunkId: 'existence-4',
  label: 'Reflection vs posited I: being-as-moment (for us) vs determinateness-posited (in it)',
  clauses: [
    'theWhole = isLikewise',
    'theWhole = inTheForm',
    'theWhole = orDeterminateness',
    'theWhole = ofBeing',
    'since = inBecoming',
    'being = hasLikewiseShownItself',
    'being = toBeOnlyAMoment',
    'being = somethingSublated',
    'being = negativelyDetermined',
    'it = isSuch',
    'however = forUs',
    'however = inOurReflection',
    'notYet = asPositedInIt',
    'what = isPosited',
    'however = isTheDeterminateness',
    'however = asSuch',
    'however = ofExistence',
    'as = isAlsoExpressed',
    'as = byTheDa',
    'as = orThere',
    'as = ofTheDasein',
    'theTwo = areAlways',
    'theTwo = toBeClearlyDistinguished',
  ],
  predicates: [
    { name: 'reflectionVsPosited', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'theWhole', to: 'inFormOfBeing' },
  ],
  candidateSummary: 'The whole is likewise in the form or determinateness of being, since in becoming being has likewise shown itself to be only a moment: something sublated, negatively determined. It is such, however, for us, in our reflection; not yet as posited in it. What is posited, however, is the determinateness as such of existence, as is also expressed by the da (or "there") of the Dasein. The two are always to be clearly distinguished.',
  provenance: {
    sourceChunk: 'existence-4',
    sourceOp: 'exist-op-4-reflection-vs-posited',
  },
};

export const existOp5ReflectionVsPositedII: LogicalOperation = {
  id: 'exist-op-5-reflection-vs-posited-ii',
  chunkId: 'existence-5',
  label: 'Reflection vs posited II: scope of commentary vs moments of the fact itself',
  clauses: [
    'only = thatWhich',
    'only = isPosited',
    'only = inAConcept',
    'only = belongs',
    'only = inTheCourse',
    'only = ofTheElaboration',
    'only = ofTheLatter',
    'only = toItsContent',
    'any = determinateness',
    'any = notYetPosited',
    'any = inTheConceptItself',
    'any = belongsInstead',
    'any = toOurReflection',
    'whether = thisReflection',
    'whether = isDirected',
    'whether = toTheNature',
    'whether = ofTheConceptItself',
    'whether = orIsAMatter',
    'whether = ofExternalComparison',
    'to = remarkOn',
    'to = aDeterminateness',
    'to = ofThisLastKind',
    'to = canOnlyBe',
    'to = forTheClarification',
    'to = orAnticipation',
    'to = ofTheWhole',
    'to = thatWillTranspire',
    'to = inTheCourse',
    'to = ofTheDevelopmentItself',
    'that = theWhole',
    'that = theUnity',
    'that = ofBeingAndNothing',
    'that = isInTheOneSidedDetermination',
    'that = ofBeing',
    'that = isAnExternalReflection',
    'but = inNegation',
    'but = inSomethingAndOther',
    'but = andSoForth',
    'but = itWillBecomePosited',
    'it = wasNecessary',
    'it = here',
    'it = toCallAttention',
    'it = toTheDistinction',
    'it = justGiven',
    'but = toCommentOn',
    'but = allThatReflection',
    'but = canAllowItself',
    'but = toGiveAnAccount',
    'but = ofIt',
    'but = wouldLead',
    'but = toALongWindedAnticipation',
    'but = ofWhatMustTranspire',
    'but = inTheFactItself',
    'although = suchReflections',
    'although = mayServe',
    'although = toFacilitate',
    'although = aGeneralOverview',
    'although = andThusFacilitate',
    'although = understanding',
    'they = alsoBring',
    'they = theDisadvantage',
    'they = ofBeingSeen',
    'they = asUnjustifiedAssertions',
    'they = unjustifiedGrounds',
    'they = andFoundations',
    'they = ofWhatIsToFollow',
    'they = shouldBeTaken',
    'they = forNoMore',
    'they = thanWhatTheyAre',
    'they = supposedToBe',
    'they = andShouldBeDistinguished',
    'they = fromWhat',
    'they = constitutesAMoment',
    'they = inTheAdvance',
    'they = ofTheFactItself',
  ],
  predicates: [
    { name: 'reflectionVsPositedII', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'only', to: 'positedInConcept' },
  ],
  candidateSummary: 'Only that which is posited in a concept belongs in the course of the elaboration of the latter to its content. Any determinateness not yet posited in the concept itself belongs instead to our reflection, whether this reflection is directed to the nature of the concept itself or is a matter of external comparison. To remark on a determinateness of this last kind can only be for the clarification or anticipation of the whole that will transpire in the course of the development itself. That the whole, the unity of being and nothing, is in the one-sided determinateness of being is an external reflection; but in negation, in something and other, and so forth, it will become posited. It was necessary here to call attention to the distinction just given; but to comment on all that reflection can allow itself, to give an account of it, would lead to a long-winded anticipation of what must transpire in the fact itself. Although such reflections may serve to facilitate a general overview and thus facilitate understanding, they also bring the disadvantage of being seen as unjustified assertions, unjustified grounds and foundations, of what is to follow. They should be taken for no more than what they are supposed to be and should be distinguished from what constitutes a moment in the advance of the fact itself.',
  provenance: {
    sourceChunk: 'existence-5',
    sourceOp: 'exist-op-5-reflection-vs-posited-ii',
  },
};

export const existOp6Correspondence: LogicalOperation = {
  id: 'exist-op-6-correspondence',
  chunkId: 'existence-6',
  label: 'Correspondence: being (indeterminate) vs existence (determinate being, concrete)',
  clauses: [
    'existence = correspondsToBeing',
    'existence = inThePrecedingSphere',
    'but = being',
    'but = isTheIndeterminate',
    'there = areNoDeterminations',
    'there = thatThereforeTranspire',
    'there = inIt',
    'but = existence',
    'but = isDeterminateBeing',
    'but = somethingConcrete',
    'consequently = severalDeterminations',
    'consequently = severalDistinctRelations',
    'consequently = ofItsMoments',
    'consequently = immediatelyEmerge',
    'consequently = inIt',
  ],
  predicates: [
    { name: 'correspondence', args: ['existence', 'being'] },
  ],
  relations: [
    { predicate: 'corresponds', from: 'existence', to: 'being' },
  ],
  candidateSummary: 'Existence corresponds to being in the preceding sphere. But being is the indeterminate; there are no determinations that therefore transpire in it. But existence is determinate being, something concrete; consequently, several determinations, several distinct relations of its moments, immediately emerge in it.',
  provenance: {
    sourceChunk: 'existence-6',
    sourceOp: 'exist-op-6-correspondence',
  },
};

export const existOp7QualityImmediacy: LogicalOperation = {
  id: 'exist-op-5-quality-immediacy',
  chunkId: 'existence-7',
  label: 'Quality I: immediacy of unity (existent ↔ non-being); no posited differentiation',
  clauses: [
    'onAccount = ofTheImmediacy',
    'withWhich = beingAndNothing',
    'withWhich = areOneInExistence',
    'neither = overstepsTheOther',
    'toTheExtent = thatExistence',
    'toTheExtent = isExistent',
    'toThatExtent = itIsNonBeing',
    'it = isDetermined',
    'being = isNotTheUniversal',
    'determinateness = notTheParticular',
    'determinateness = hasYetToDetachItself',
    'determinateness = fromBeing',
    'nor = willItEverDetachItself',
    'nor = fromIt',
    'since = theNowUnderlyingTruth',
    'since = isTheUnity',
    'since = ofNonBeingWithBeing',
    'allFurtherDeterminations = willTranspire',
    'allFurtherDeterminations = onThisBasis',
    'but = theConnection',
    'but = whichDeterminateness',
    'but = nowHasWithBeing',
    'but = isOne',
    'but = ofTheImmediateUnity',
    'but = ofTheTwo',
    'so = thatAsYet',
    'so = noDifferentiation',
    'so = betweenTheTwo',
    'so = isPosited',
  ],
  predicates: [
    { name: 'quality', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'determinateness', to: 'quality' },
  ],
  candidateSummary: 'On account of the immediacy with which being and nothing are one in existence, neither oversteps the other; to the extent that existence is existent, to that extent it is non-being; it is determined. Being is not the universal, determinateness not the particular. Determinateness has yet to detach itself from being; nor will it ever detach itself from it, since the now underlying truth is the unity of non-being with being; all further determinations will transpire on this basis. But the connection which determinateness now has with being is one of the immediate unity of the two, so that as yet no differentiation between the two is posited.',
  provenance: {
    sourceChunk: 'existence-7',
    sourceOp: 'exist-op-5-quality-immediacy',
  },
};

export const existOp6QualityDefinition: LogicalOperation = {
  id: 'exist-op-6-quality-definition',
  chunkId: 'existence-8',
  label: 'Quality II: definition (existent determinateness; simple, immediate)',
  clauses: [
    'determinateness = thusIsolated',
    'determinateness = byItself',
    'determinateness = asExistentDeterminateness',
    'determinateness = isQuality',
    'something = totallySimple',
    'something = immediate',
    'determinateness = inGeneral',
    'determinateness = isTheMoreUniversal',
    'determinateness = which',
    'determinateness = furtherDetermined',
    'determinateness = canBe',
    'determinateness = somethingQuantitative',
    'determinateness = asWell',
    'onAccount = ofThisSimplicity',
    'there = isNothingFurther',
    'there = toSayAboutQuality',
    'there = asSuch',
  ],
  predicates: [
    { name: 'quality', args: ['determinateness'] },
  ],
  relations: [
    { predicate: 'is', from: 'determinateness', to: 'quality' },
  ],
  candidateSummary: 'Determinateness thus isolated by itself, as existent determinateness, is quality: something totally simple, immediate. Determinateness in general is the more universal which, further determined, can be something quantitative as well. On account of this simplicity, there is nothing further to say about quality as such.',
  provenance: {
    sourceChunk: 'existence-8',
    sourceOp: 'exist-op-6-quality-definition',
  },
};

export const existOp9QualityRealityAndNegation: LogicalOperation = {
  id: 'exist-op-9-quality-reality-and-negation',
  chunkId: 'existence-9',
  label: 'Quality III: reality and negation; reflection; limit/restriction',
  clauses: [
    'existence = however',
    'existence = inWhich',
    'existence = nothingAndBeing',
    'existence = areEquallyContained',
    'existence = isItselfTheMeasure',
    'existence = ofTheOneSidedness',
    'existence = ofQuality',
    'existence = asAnOnlyImmediate',
    'existence = orExistentDeterminateness',
    'quality = isEqually',
    'quality = toBePosited',
    'quality = inTheDetermination',
    'quality = ofNothing',
    'and = theResult',
    'and = isThat',
    'and = theImmediate',
    'and = orExistentDeterminateness',
    'and = isPositedAsDistinct',
    'and = reflected',
    'and = andTheNothing',
    'and = asThusTheDeterminateElement',
    'and = ofDeterminateness',
    'and = willEquallyBe',
    'and = somethingReflected',
    'and = aNegation',
    'quality = inTheDistinctValue',
    'quality = ofExistent',
    'quality = isReality',
    'when = affectedByANegating',
    'it = isNegationInGeneral',
    'still = aQuality',
    'but = oneThatCounts',
    'but = asALack',
    'but = andIsFurtherDetermined',
    'but = asLimit',
    'but = restriction',
  ],
  predicates: [
    { name: 'reality', args: ['quality'] },
    { name: 'negation', args: ['quality'] },
  ],
  relations: [
    { predicate: 'is', from: 'quality', to: 'reality' },
    { predicate: 'is', from: 'quality', to: 'negation' },
  ],
  candidateSummary: 'Existence, however, in which nothing and being are equally contained, is itself the measure of the one-sidedness of quality as an only immediate or existent determinateness. Quality is equally to be posited in the determination of nothing, and the result is that the immediate or existent determinateness is posited as distinct, reflected, and the nothing, as thus the determinate element of determinateness, will equally be something reflected, a negation. Quality, in the distinct value of existent, is reality; when affected by a negating, it is negation in general, still a quality but one that counts as a lack and is further determined as limit, restriction.',
  provenance: {
    sourceChunk: 'existence-9',
    sourceOp: 'exist-op-9-quality-reality-and-negation',
  },
};

export const existOp10QualityValuation: LogicalOperation = {
  id: 'exist-op-10-quality-valuation',
  chunkId: 'existence-10',
  label: 'Quality IV: valuation of reality vs negation (both are existence)',
  clauses: [
    'both = areAnExistence',
    'but = inReality',
    'but = asQuality',
    'but = withTheAccent',
    'but = onBeingAnExistent',
    'but = thatItIsDeterminateness',
    'but = andHenceAlsoNegation',
    'but = isConcealed',
    'reality = onlyHas',
    'reality = therefore',
    'reality = theValue',
    'reality = ofSomethingPositive',
    'reality = fromWhich',
    'reality = negating',
    'reality = restriction',
    'reality = lack',
    'reality = areExcluded',
    'negation = forItsPart',
    'negation = takenAsMereLack',
    'negation = wouldBe',
    'negation = whatNothingIs',
    'but = itIsAnExistence',
    'but = aQuality',
    'but = onlyDetermined',
    'but = withANonBeing',
  ],
  predicates: [
    { name: 'valuation', args: ['reality', 'negation'] },
  ],
  relations: [
    { predicate: 'is', from: 'both', to: 'existence' },
  ],
  candidateSummary: 'Both are an existence, but in reality, as quality with the accent on being an existent, that it is determinateness and hence also negation is concealed; reality only has, therefore, the value of something positive from which negating, restriction, lack, are excluded. Negation, for its part, taken as mere lack, would be what nothing is; but it is an existence, a quality, only determined with a non-being.',
  provenance: {
    sourceChunk: 'existence-10',
    sourceOp: 'exist-op-10-quality-valuation',
  },
};

export const existOp11SomethingRealityAndNegation: LogicalOperation = {
  id: 'exist-op-11-something-reality-and-negation',
  chunkId: 'existence-11',
  label: 'Something I: reality ∧ negation as existences; quality unseparated from existence',
  clauses: [
    'in = existence',
    'itsDeterminateness = hasBeenDistinguished',
    'itsDeterminateness = asQuality',
    'in = thisQuality',
    'in = asSomethingExisting',
    'theDistinction = exists',
    'theDistinction = ofRealityAndNegation',
    'now = though',
    'theseDistinctions = arePresent',
    'theseDistinctions = inExistence',
    'they = areJustAsMuch',
    'they = nullAndSublated',
    'reality = itself',
    'reality = containsNegation',
    'reality = itIsExistence',
    'reality = notIndeterminate',
    'reality = orAbstractBeing',
    'negation = isForItsPart',
    'negation = equallyExistence',
    'negation = notTheSupposed',
    'negation = abstractNothing',
    'negation = butPositedHere',
    'negation = asItIsInItself',
    'negation = asExistent',
    'negation = asBelongingToExistence',
    'thus = quality',
    'thus = isInGeneral',
    'thus = unseparatedFromExistence',
    'and = theLatter',
    'and = isOnly',
    'and = determinate',
    'and = qualitativeBeing',
  ],
  predicates: [
    { name: 'something', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'existence', to: 'something' },
  ],
  candidateSummary: 'In existence its determinateness has been distinguished as quality; in this quality as something existing, the distinction exists: the distinction of reality and negation. Now though these distinctions are present in existence, they are just as much null and sublated. Reality itself contains negation; it is existence, not indeterminate or abstract being. Negation is for its part equally existence, not the supposed abstract nothing but posited here as it is in itself, as existent, as belonging to existence. Thus quality is in general unseparated from existence, and the latter is only determinate, qualitative being.',
  provenance: {
    sourceChunk: 'existence-11',
    sourceOp: 'exist-op-11-something-reality-and-negation',
  },
};

export const existOp12SomethingSublation: LogicalOperation = {
  id: 'exist-op-12-something-sublation',
  chunkId: 'existence-12',
  label: 'Something II: sublation (not omission) → simplicity mediated → being-in-itself',
  clauses: [
    'this = sublating',
    'this = ofTheDistinction',
    'this = isMoreThan',
    'this = theMereRetraction',
    'this = andExternalReOmission',
    'this = ofIt',
    'or = aSimpleReturn',
    'or = toTheSimpleBeginning',
    'or = toExistence',
    'or = asSuch',
    'theDistinction = cannotBeLeftOut',
    'theDistinction = forItIs',
    'therefore = what',
    'therefore = deFacto',
    'therefore = isAtHand',
    'therefore = isThis',
    'therefore = existenceInGeneral',
    'therefore = distinctionInIt',
    'therefore = andTheSublation',
    'therefore = ofThisDistinction',
    'theExistence = notVoid',
    'theExistence = ofDistinctions',
    'theExistence = asAtTheBeginning',
    'but = asAgainSelfEqual',
    'but = throughTheSublation',
    'but = ofTheDistinction',
    'theSimplicity = ofExistence',
    'theSimplicity = mediated',
    'theSimplicity = throughThisSublation',
    'thisState = ofSublation',
    'thisState = ofTheDistinction',
    'thisState = isExistence',
    'thisState = ownDeterminateness',
    'existence = isThus',
    'existence = beingInItself',
    'it = isExistent',
    'it = something',
  ],
  predicates: [
    { name: 'sublation', args: ['distinction'] },
  ],
  relations: [
    { predicate: 'is', from: 'existence', to: 'beingInItself' },
  ],
  candidateSummary: 'This sublating of the distinction is more than the mere retraction and external re-omission of it, or a simple return to the simple beginning, to existence as such. The distinction cannot be left out, for it is. Therefore, what de facto is at hand is this: existence in general, distinction in it, and the sublation of this distinction; the existence, not void of distinctions as at the beginning, but as again self-equal through the sublation of the distinction; the simplicity of existence mediated through this sublation. This state of sublation of the distinction is existence\'s own determinateness; existence is thus being-in-itself; it is existent, something.',
  provenance: {
    sourceChunk: 'existence-12',
    sourceOp: 'exist-op-12-something-sublation',
  },
};

export const existOp13SomethingNegationOfNegation: LogicalOperation = {
  id: 'exist-op-13-something-negation-of-negation',
  chunkId: 'existence-13',
  label: 'Something III: negation of negation; beginning of the subject',
  clauses: [
    'something = isTheFirstNegation',
    'something = ofNegation',
    'something = asSimpleExistent',
    'something = selfReference',
    'existence = life',
    'existence = thought',
    'existence = andSoForth',
    'existence = essentiallyTakeOn',
    'existence = theDetermination',
    'existence = ofAnExistentBeing',
    'existence = aLivingThing',
    'existence = aThinkingMind',
    'existence = i',
    'existence = andSoForth',
    'thisDetermination = isOfTheHighestImportance',
    'if = weDoNotWish',
    'if = toHaltAtExistence',
    'if = life',
    'if = thought',
    'if = andSoForth',
    'if = asGeneralities',
    'also = notAtGodhood',
    'instead = ofGod',
    'in = commonRepresentation',
    'something = rightlyCarries',
    'something = theConnotation',
    'something = ofARealThing',
    'yet = itStillIs',
    'yet = aVerySuperficialDetermination',
    'just = asRealityAndNegation',
    'just = existenceAndItsDeterminateness',
    'though = noLongerTheEmptyBeing',
    'though = andNothing',
    'still = areQuiteAbstractDeterminations',
    'for = thisReason',
    'they = alsoAre',
    'they = theMostCommonExpressions',
    'and = aReflection',
    'and = thatIsStill',
    'and = philosophicallyUnschooled',
    'and = usesThemTheMost',
    'it = castsItsDistinctions',
    'it = inThem',
    'it = fancying',
    'it = thatInThem',
    'it = itHasSomething',
    'it = reallyWellAndFirmlyDetermined',
    'as = something',
    'theNegative = ofTheNegative',
    'theNegative = isOnly',
    'theNegative = theBeginning',
    'theNegative = ofTheSubject',
    'itsInItselfness = isStill',
    'itsInItselfness = quiteIndeterminate',
    'it = determinesItselfFurtherOn',
    'atFirst = asExistentForItself',
    'atFirst = andSoOn',
    'until = itFinallyObtains',
    'until = inTheConcept',
    'until = theIntensity',
    'until = ofTheSubject',
    'at = theBase',
    'at = ofAllTheseDeterminations',
    'at = thereLies',
    'at = theNegativeUnity',
    'at = withItself',
    'in = allThis',
    'however = care',
    'however = mustBeTaken',
    'however = toDistinguish',
    'however = theFirstNegation',
    'however = negationAsNegation',
    'however = inGeneral',
    'however = fromTheSecondNegation',
    'however = theNegationOfNegation',
    'however = whichIsConcrete',
    'however = absoluteNegativity',
    'just = asTheFirst',
    'just = isOnTheContrary',
    'just = onlyAbstractNegativity',
  ],
  predicates: [
    { name: 'negationOfNegation', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'negationOfNegation' },
  ],
  candidateSummary: 'Something is the first negation of negation, as simple existent self-reference. Existence, life, thought, and so forth, essentially take on the determination of an existent being, a living thing, a thinking mind ("I"), and so forth. This determination is of the highest importance if we do not wish to halt at existence, life, thought, and so forth, as generalities, also not at Godhood (instead of God). In common representation, something rightly carries the connotation of a real thing. Yet it still is a very superficial determination, just as reality and negation, existence and its determinateness, though no longer the empty being and nothing, still are quite abstract determinations. For this reason they also are the most common expressions, and a reflection that is still philosophically unschooled uses them the most; it casts its distinctions in them, fancying that in them it has something really well and firmly determined. As something, the negative of the negative is only the beginning of the subject; its in-itselfness is still quite indeterminate. It determines itself further on, at first as existent-for-itself and so on, until it finally obtains in the concept the intensity of the subject. At the base of all these determinations there lies the negative unity with itself. In all this, however, care must be taken to distinguish the first negation, negation as negation in general, from the second negation, the negation of negation which is concrete, absolute negativity, just as the first is on the contrary only abstract negativity.',
  provenance: {
    sourceChunk: 'existence-13',
    sourceOp: 'exist-op-13-something-negation-of-negation',
  },
};

export const existOp14SomethingMediation: LogicalOperation = {
  id: 'exist-op-14-something-mediation',
  chunkId: 'existence-14',
  label: 'Something IV: mediation-with-itself (vs alleged bare immediacy)',
  clauses: [
    'something = isAnExistent',
    'something = asTheNegation',
    'something = ofNegation',
    'for = suchANegation',
    'for = isTheRestoration',
    'for = ofTheSimpleReference',
    'for = toItself',
    'but = theSomething',
    'but = isTherebyEqually',
    'but = theMediation',
    'but = ofItself',
    'but = withItself',
    'present = inTheSimplicity',
    'present = ofSomething',
    'and = then',
    'and = withGreaterDeterminateness',
    'and = inBeingForItself',
    'and = inTheSubject',
    'and = andSoForth',
    'this = mediation',
    'this = ofItself',
    'this = withItself',
    'this = isAlsoAlreadyPresent',
    'this = inBecoming',
    'but = onlyAsTotallyAbstract',
    'but = mediation',
    'mediation = withItself',
    'mediation = isPosited',
    'mediation = inTheSomething',
    'in = soFarAs',
    'theLatter = isDetermined',
    'theLatter = asASimpleIdentity',
    'attention = canBeDrawn',
    'attention = toThePresence',
    'attention = ofMediation',
    'attention = inGeneral',
    'as = againstThePrinciple',
    'as = ofTheAlleged',
    'as = bareImmediacy',
    'as = ofAKnowledge',
    'as = fromWhich',
    'as = mediation',
    'as = shouldBeExcluded',
    'but = thereIsNoFurther',
    'but = need',
    'but = toDrawParticularAttention',
    'but = toTheMoment',
    'but = ofMediation',
    'since = itIsToBeFound',
    'since = everywhere',
    'since = andOnAllSides',
    'since = inEveryConcept',
  ],
  predicates: [
    { name: 'mediationWithItself', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'mediationWithItself' },
  ],
  candidateSummary: 'Something is an existent as the negation of negation, for such a negation is the restoration of the simple reference to itself; but the something is thereby equally the mediation of itself with itself. Present in the simplicity of something, and then with greater determinateness in being-for-itself, in the subject, and so forth, this mediation of itself with itself is also already present in becoming, but only as totally abstract mediation; mediation with itself is posited in the something in so far as the latter is determined as a simple identity. Attention can be drawn to the presence of mediation in general, as against the principle of the alleged bare immediacy of a knowledge from which mediation should be excluded. But there is no further need to draw particular attention to the moment of mediation, since it is to be found everywhere and on all sides, in every concept.',
  provenance: {
    sourceChunk: 'existence-14',
    sourceOp: 'exist-op-14-something-mediation',
  },
};

export const existOp15SomethingMediationOnly: LogicalOperation = {
  id: 'exist-op-15-something-mediation-only',
  chunkId: 'existence-15',
  label: 'Something V: mediation-only collapses to unity; becoming with moments as existents (other)',
  clauses: [
    'this = mediation',
    'this = withItself',
    'this = whichSomething',
    'this = isInItself',
    'when = takenOnly',
    'when = asTheNegation',
    'when = ofNegation',
    'has = noConcreteDeterminations',
    'has = forItsSides',
    'thus = itCollapses',
    'thus = intoTheSimpleUnity',
    'thus = whichIsBeing',
    'something = is',
    'something = andIsTherefore',
    'something = alsoAnExistent',
    'further = itIs',
    'further = inItself',
    'further = alsoBecoming',
    'but = aBecoming',
    'but = thatNoLongerHas',
    'but = onlyBeingAndNothing',
    'but = forItsMoments',
    'one = ofTheseMoments',
    'one = being',
    'one = isNowExistence',
    'one = andFurther',
    'one = anExistent',
    'theOther = moment',
    'theOther = isEqually',
    'theOther = anExistent',
    'but = determined',
    'but = asTheNegative',
    'but = ofSomething',
    'but = anOther',
  ],
  predicates: [
    { name: 'mediationOnly', args: ['something'] },
  ],
  relations: [
    { predicate: 'collapses', from: 'this', to: 'intoSimpleUnity' },
  ],
  candidateSummary: 'This mediation with itself which something is in itself, when taken only as the negation of negation, has no concrete determinations for its sides; thus it collapses into the simple unity which is being. Something is, and is therefore also an existent. Further, it is in itself also becoming, but a becoming that no longer has only being and nothing for its moments. One of these moments, being, is now existence and further an existent. The other moment is equally an existent, but determined as the negative of something; an other.',
  provenance: {
    sourceChunk: 'existence-15',
    sourceOp: 'exist-op-15-something-mediation-only',
  },
};

export const existOp16SomethingAlteration: LogicalOperation = {
  id: 'exist-op-16-something-alteration',
  chunkId: 'existence-16',
  label: 'Something VI: alteration; initially only in concept; other as qualitative',
  clauses: [
    'as = becoming',
    'something = isATransition',
    'theMoments = ofWhich',
    'theMoments = areThemselves',
    'theMoments = something',
    'and = forThatReason',
    'it = isAnAlteration',
    'it = aBecoming',
    'it = thatHasAlready',
    'it = becomeConcrete',
    'at = first',
    'however = something',
    'however = altersOnly',
    'however = inItsConcept',
    'it = isNotYet',
    'it = positedInThisWay',
    'it = asMediated',
    'it = andMediating',
    'but = atFirst',
    'but = onlyAsMaintaining',
    'but = itselfSimply',
    'but = inItsReference',
    'but = toItself',
    'and = itsNegative',
    'and = isPosited',
    'and = asEquallyQualitative',
    'and = asOnly',
    'and = anOther',
    'and = inGeneral',
  ],
  predicates: [
    { name: 'alteration', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'alteration' },
  ],
  candidateSummary: 'As becoming, something is a transition, the moments of which are themselves something, and for that reason it is an alteration, a becoming that has already become concrete. At first, however, something alters only in its concept; it is not yet posited in this way, as mediated and mediating, but at first only as maintaining itself simply in its reference to itself; and its negative is posited as equally qualitative, as only an other in general.',
  provenance: {
    sourceChunk: 'existence-16',
    sourceOp: 'exist-op-16-something-alteration',
  },
};

export const existenceOperations: LogicalOperation[] = [
  existOp1Outline,
  existOp2ExistenceFromBecoming,
  existOp3Dasein,
  existOp4ReflectionVsPosited,
  existOp5ReflectionVsPositedII,
  existOp6Correspondence,
  existOp7QualityImmediacy,
  existOp8QualityDefinition,
  existOp9QualityRealityAndNegation,
  existOp10QualityValuation,
  existOp11SomethingRealityAndNegation,
  existOp12SomethingSublation,
  existOp13SomethingNegationOfNegation,
  existOp14SomethingMediation,
  existOp15SomethingMediationOnly,
  existOp16SomethingAlteration,
];

