/**
 * Logical Operations: Something and Other
 *
 * Something and Other - the relationship between something and other,
 * establishing the structure of being-in-itself and being-for-other
 * that is essential for understanding finitude.
 *
 * Dialectical Movement:
 * - Something and other: both existents, both others, indifference
 * - Being-for-other and being-in-itself: two moments of something
 * - Identity of being-in-itself and being-for-other: both moments, thing-in-itself critique
 */

import type { LogicalOperation } from '../../../../types';

// ============================================================================
// SOMETHING AND OTHER
// ============================================================================

export const soOp1Outline: LogicalOperation = {
  id: 'so-op-1-outline',
  chunkId: 'something-and-other-1',
  label: 'Outline: (a) Something and other → (b) Determination/constitution/limit → (c) Finitude',
  clauses: [
    'a = somethingAndOther',
    'atFirst = theyAreIndifferent',
    'anOther = alsoAnImmediateExistent',
    'anOther = aSomething',
    'theNegation = thusFallsOutside',
    'theNegation = both',
    'something = isInItself',
    'something = inContrastTo',
    'something = itsBeingForOther',
    'but = theDeterminateness',
    'but = belongsAlso',
    'but = toItsInItself',
    'b = theDetermination',
    'b = ofThisInItself',
    'b = inTurnPassesOver',
    'b = intoConstitution',
    'thisLatter = asIdentical',
    'thisLatter = withDetermination',
    'thisLatter = constitutes',
    'thisLatter = theImmanent',
    'thisLatter = andAtTheSameTime',
    'thisLatter = negatedBeingForAnother',
    'thisLatter = theLimit',
    'thisLatter = ofSomething',
    'c = which',
    'c = isTheImmanentDetermination',
    'c = ofTheSomethingItself',
    'theSomething = thusIs',
    'theSomething = theFinite',
  ],
  predicates: [
    { name: 'outline', args: ['somethingAndOther'] },
  ],
  relations: [
    { predicate: 'passesOver', from: 'determination', to: 'constitution' },
    { predicate: 'is', from: 'something', to: 'finite' },
  ],
  candidateSummary: '(a) Something and other: at first they are indifferent to one another; an other is also an immediate existent, a something; the negation thus falls outside both. Something is in itself in contrast to its being-for-other. But the determinateness belongs also to its in-itself, and (b) the determination of this in-itself in turn passes over into constitution, and this latter, as identical with determination, constitutes the immanent and at the same time negated being-for-another, the limit of something which (c) is the immanent determination of the something itself, and the something thus is the finite.',
  provenance: {
    sourceChunk: 'something-and-other-1',
    sourceOp: 'so-op-1-outline',
  },
};

export const soOp2Introduction: LogicalOperation = {
  id: 'so-op-2-introduction',
  chunkId: 'something-and-other-2',
  label: 'Introduction: negative determination (vs affirmative in first division)',
  clauses: [
    'in = theFirstDivision',
    'where = existenceInGeneral',
    'where = wasConsidered',
    'thisExistence = had',
    'thisExistence = asAtFirst',
    'thisExistence = takenUp',
    'thisExistence = theDetermination',
    'thisExistence = ofAnExistent',
    'theMoments = ofItsDevelopment',
    'theMoments = qualityAndSomething',
    'theMoments = areTherefore',
    'theMoments = ofEquallyAffirmativeDetermination',
    'thePresentDivision = onTheContrary',
    'thePresentDivision = develops',
    'thePresentDivision = theNegativeDetermination',
    'thePresentDivision = whichIsPresent',
    'thePresentDivision = inExistence',
    'thePresentDivision = andWasThere',
    'thePresentDivision = fromTheStart',
    'thePresentDivision = onlyAsNegation',
    'thePresentDivision = inGeneral',
    'it = wasThen',
    'it = theFirstNegation',
    'it = butHasNow',
    'it = beenDetermined',
    'it = toThePoint',
    'it = ofTheBeingInItself',
    'it = ofTheSomething',
    'it = thePoint',
    'it = ofTheNegation',
    'it = ofNegation',
  ],
  predicates: [
    { name: 'negativeDetermination', args: ['existence'] },
  ],
  relations: [
    { predicate: 'develops', from: 'presentDivision', to: 'negativeDetermination' },
  ],
  candidateSummary: 'In the first division where existence in general was considered, this existence had, as at first taken up, the determination of an existent. The moments of its development, quality and something, are therefore of equally affirmative determination. The present division, on the contrary, develops the negative determination which is present in existence and was there from the start only as negation in general. It was then the first negation but has now been determined to the point of the being-in-itself of the something, the point of the negation of negation.',
  provenance: {
    sourceChunk: 'something-and-other-2',
    sourceOp: 'so-op-2-introduction',
  },
};

export const soOp3BothExistents: LogicalOperation = {
  id: 'so-op-3-both-existents',
  chunkId: 'something-and-other-3',
  label: 'Something and other I: both existents; both others; indifference',
  clauses: [
    'something = andOther',
    'something = are',
    'first = bothExistents',
    'first = orSomething',
    'second = each',
    'second = isEqually',
    'second = anOther',
    'it = isIndifferent',
    'it = which',
    'it = isNamedFirst',
    'and = justForThisReason',
    'it = isNamed',
    'it = something',
    'in = latin',
    'when = theyOccur',
    'when = inAProposition',
    'both = areAliud',
    'both = orTheOne',
    'both = theOther',
    'both = aliusAlium',
    'in = theCase',
    'in = ofAnAlternatingRelation',
    'theAnalogousExpression = is',
    'theAnalogousExpression = alterAlterum',
    'if = ofTwoBeings',
    'we = call',
    'we = theOne',
    'we = a',
    'we = andTheOther',
    'we = b',
    'theB = isTheOne',
    'theB = whichIsFirst',
    'theB = determinedAsOther',
    'but = theA',
    'but = isJustAsMuch',
    'but = theOther',
    'but = ofTheB',
    'both = areOther',
    'both = inTheSameWay',
  ],
  predicates: [
    { name: 'bothExistents', args: ['something', 'other'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'existent' },
    { predicate: 'is', from: 'other', to: 'existent' },
  ],
  candidateSummary: 'Something and other are, first, both existents or something. Second, each is equally an other. It is indifferent which is named first, and just for this reason it is named something (in Latin, when they occur in a proposition, both are aliud, or "the one, the other," alius alium; in the case of an alternating relation, the analogous expression is alter alterum). If of two beings we call the one A and the other B, the B is the one which is first determined as other. But the A is just as much the other of the B. Both are other in the same way.',
  provenance: {
    sourceChunk: 'something-and-other-3',
    sourceOp: 'so-op-3-both-existents',
  },
};

export const soOp4ThisAsSubjective: LogicalOperation = {
  id: 'so-op-4-this-as-subjective',
  chunkId: 'something-and-other-4',
  label: '"This" as subjective designation; language expresses universal',
  clauses: [
    'this = servesToFix',
    'this = theDistinction',
    'this = andTheSomething',
    'this = whichIsToBeTaken',
    'this = inTheAffirmativeSense',
    'but = this',
    'but = alsoExpresses',
    'but = theFact',
    'but = thatTheDistinction',
    'but = andThePrivileging',
    'but = ofOneSomething',
    'but = isASubjectiveDesignation',
    'but = thatFallsOutside',
    'but = theSomethingItself',
    'theWholeDeterminateness = falls',
    'theWholeDeterminateness = onTheSide',
    'theWholeDeterminateness = ofThisExternalPointing',
    'also = theExpression',
    'also = this',
    'also = containsNoDistinctions',
    'each = andEverySomething',
    'each = isJustAsGood',
    'each = aThis',
    'each = asAnyOther',
    'by = this',
    'we = meanToExpress',
    'we = somethingCompletelyDeterminate',
    'we = overlooking',
    'we = theFact',
    'we = thatLanguage',
    'we = asAWork',
    'we = ofTheUnderstanding',
    'we = onlyExpresses',
    'we = theUniversal',
    'we = albeitNamingIt',
    'we = asASingleObject',
    'but = anIndividualName',
    'but = isSomethingMeaningless',
    'but = inTheSense',
    'but = thatItDoesNotExpress',
    'but = aUniversal',
    'it = appears',
    'it = asSomethingMerelyPosited',
    'it = andArbitrary',
    'it = forTheSameReason',
    'it = thatProperNames',
    'it = canAlsoBe',
    'it = arbitrarilyPicked',
    'it = arbitrarilyGiven',
    'it = asWellAs',
    'it = arbitrarilyAltered',
  ],
  predicates: [
    { name: 'subjectiveDesignation', args: ['this'] },
  ],
  relations: [
    { predicate: 'expresses', from: 'language', to: 'universal' },
  ],
  candidateSummary: '"This" serves to fix the distinction and the something which is to be taken in the affirmative sense. But "this" also expresses the fact that the distinction, and the privileging of one something, is a subjective designation that falls outside the something itself. The whole determinateness falls on the side of this external pointing; also the expression "this" contains no distinctions; each and every something is just as good a "this" as any other. By "this" we mean to express something completely determinate, overlooking the fact that language, as a work of the understanding, only expresses the universal, albeit naming it as a single object. But an individual name is something meaningless in the sense that it does not express a universal. It appears as something merely posited and arbitrary for the same reason that proper names can also be arbitrarily picked, arbitrarily given as well as arbitrarily altered.',
  provenance: {
    sourceChunk: 'something-and-other-4',
    sourceOp: 'so-op-4-this-as-subjective',
  },
};

export const soOp5OthernessAsExternal: LogicalOperation = {
  id: 'so-op-5-otherness-as-external',
  chunkId: 'something-and-other-5',
  label: 'Otherness as external; comparison by Third; every existence is other',
  clauses: [
    'otherness = thusAppears',
    'otherness = asADetermination',
    'otherness = alienTo',
    'otherness = theExistence',
    'otherness = thusPointedAt',
    'or = theOtherExistence',
    'or = asOutside',
    'or = thisOneExistence',
    'partly = because',
    'theOneExistence = isDetermined',
    'theOneExistence = asOther',
    'theOneExistence = onlyBy',
    'theOneExistence = beingCompared',
    'theOneExistence = byAThird',
    'and = partly',
    'because = itIs',
    'because = soDetermined',
    'because = onlyOnAccount',
    'because = ofTheOther',
    'because = whichIsOutside',
    'because = it',
    'but = isNot',
    'but = anOther',
    'but = forItself',
    'at = theSameTime',
    'as = hasBeenRemarked',
    'even = forOrdinaryThinking',
    'everyExistence = equallyDetermines',
    'everyExistence = itself',
    'everyExistence = asAnOtherExistence',
    'so = that',
    'there = isNoExistence',
    'there = thatRemains',
    'there = determinedSimply',
    'there = asAnExistence',
    'none = which',
    'none = isNot',
    'none = outside',
    'none = anExistence',
    'none = andTherefore',
    'none = isNot',
    'none = itself',
    'none = anOther',
  ],
  predicates: [
    { name: 'otherness', args: ['existence'] },
  ],
  relations: [
    { predicate: 'is', from: 'everyExistence', to: 'other' },
  ],
  candidateSummary: 'Otherness thus appears as a determination alien to the existence thus pointed at, or the other existence as outside this one existence, partly because the one existence is determined as other only by being compared by a Third, and partly because it is so determined only on account of the other which is outside it, but is not an other for itself. At the same time, as has been remarked, even for ordinary thinking every existence equally determines itself as an other existence, so that there is no existence that remains determined simply as an existence, none which is not outside an existence and therefore is not itself an other.',
  provenance: {
    sourceChunk: 'something-and-other-5',
    sourceOp: 'so-op-5-otherness-as-external',
  },
};

export const soOp6SamenessInReflection: LogicalOperation = {
  id: 'so-op-6-sameness-in-reflection',
  chunkId: 'something-and-other-6',
  label: 'Sameness falls in external reflection; other for itself apart from something',
  clauses: [
    'both = areDetermined',
    'both = asSomething',
    'both = asWellAs',
    'both = other',
    'thus = theyAre',
    'thus = theSame',
    'thus = andThereIs',
    'thus = asYet',
    'thus = noDistinction',
    'thus = presentInThem',
    'but = thisSameness',
    'but = ofDeterminations',
    'but = too',
    'but = fallsOnly',
    'but = withinExternalReflection',
    'but = inTheComparison',
    'but = ofTheTwo',
    'but = theOther',
    'but = asPosited',
    'but = atFirst',
    'though = anOther',
    'though = withReference',
    'though = toSomething',
    'though = isOther',
    'though = alsoForItself',
    'though = apartFrom',
    'though = theSomething',
  ],
  predicates: [
    { name: 'sameness', args: ['something', 'other'] },
  ],
  relations: [
    { predicate: 'falls', from: 'sameness', to: 'externalReflection' },
  ],
  candidateSummary: 'Both are determined as something as well as other: thus they are the same and there is as yet no distinction present in them. But this sameness of determinations, too, falls only within external reflection, in the comparison of the two; but the other, as posited at first, though an other with reference to something, is other also for itself apart from the something.',
  provenance: {
    sourceChunk: 'something-and-other-6',
    sourceOp: 'so-op-6-sameness-in-reflection',
  },
};

export const soOp7OtherAsToHeteron: LogicalOperation = {
  id: 'so-op-7-other-as-to-heteron',
  chunkId: 'something-and-other-7',
  label: 'Other as \'to heteron\' (Plato); other-of-itself; nature as other of spirit',
  clauses: [
    'third = theOther',
    'third = isTherefore',
    'third = toBeTaken',
    'third = inIsolation',
    'third = withReference',
    'third = toItself',
    'third = hasToBeTaken',
    'third = abstractly',
    'third = asTheOther',
    'third = theToHeteron',
    'third = ofPlato',
    'third = whoOpposesIt',
    'third = toTheOne',
    'third = asAMoment',
    'third = ofTotality',
    'and = inThisWay',
    'and = ascribes',
    'and = toTheOther',
    'and = aNature',
    'and = ofItsOwn',
    'thus = theOther',
    'thus = takenSolely',
    'thus = asSuch',
    'thus = isNot',
    'thus = theOther',
    'thus = ofSomething',
    'thus = butIs',
    'thus = theOther',
    'thus = within',
    'thus = thatIs',
    'thus = theOther',
    'thus = ofItself',
    'such = anOther',
    'such = whichIs',
    'such = theOther',
    'such = byItsOwnDetermination',
    'such = isPhysicalNature',
    'nature = isTheOther',
    'nature = ofSpirit',
    'this = itsDetermination',
    'this = isAtFirst',
    'this = aMereRelativity',
    'this = expressing',
    'this = notAQuality',
    'this = ofNatureItself',
    'this = butOnly',
    'this = aReference',
    'this = externalToIt',
    'but = since',
    'spirit = isTheTrueSomething',
    'and = hence',
    'nature = isWhat',
    'nature = itIs',
    'nature = within',
    'nature = onlyInContrast',
    'nature = toSpirit',
    'taken = forItself',
    'theQuality = ofNature',
    'theQuality = isJustThis',
    'theQuality = toBe',
    'theQuality = theOther',
    'theQuality = within',
    'theQuality = thatWhichExists',
    'theQuality = outsideItself',
    'theQuality = inTheDeterminations',
    'theQuality = ofSpace',
    'theQuality = time',
    'theQuality = matter',
  ],
  predicates: [
    { name: 'toHeteron', args: ['other'] },
  ],
  relations: [
    { predicate: 'is', from: 'nature', to: 'otherOfSpirit' },
  ],
  candidateSummary: 'Third, the other is therefore to be taken in isolation, with reference to itself, has to be taken abstractly as the other, the \'to heteron\' of Plato who opposes it to the one as a moment of totality, and in this way ascribes to the other a nature of its own. Thus the other, taken solely as such, is not the other of something, but is the other within, that is, the other of itself. Such an other, which is the other by its own determination, is physical nature; nature is the other of spirit; this, its determination, is at first a mere relativity expressing not a quality of nature itself but only a reference external to it. But since spirit is the true something, and hence nature is what it is within only in contrast to spirit, taken for itself the quality of nature is just this, to be the other within, that which-exists-outside-itself (in the determinations of space, time, matter).',
  provenance: {
    sourceChunk: 'something-and-other-7',
    sourceOp: 'so-op-7-other-as-to-heteron',
  },
};

export const soOp8OtherOfItself: LogicalOperation = {
  id: 'so-op-8-other-of-itself',
  chunkId: 'something-and-other-8',
  label: 'Other-of-itself: absolutely unequal, negates/alters itself, yet identical',
  clauses: [
    'theOther = whichIs',
    'theOther = suchForItself',
    'theOther = isTheOther',
    'theOther = withinIt',
    'hence = theOther',
    'hence = ofItself',
    'hence = andSo',
    'hence = theOther',
    'hence = ofTheOther',
    'therefore = theAbsolutelyUnequal',
    'therefore = inItself',
    'therefore = thatWhich',
    'therefore = negatesItself',
    'therefore = altersItself',
    'but = itEqually',
    'but = remains',
    'but = identical',
    'but = withItself',
    'for = that',
    'for = intoWhich',
    'for = itAlters',
    'for = isTheOther',
    'for = andThisOther',
    'for = hasNo',
    'for = additionalDetermination',
    'but = thatWhich',
    'but = altersItself',
    'but = isNot',
    'but = determined',
    'but = inAnyOtherWay',
    'but = thanInThis',
    'but = toBe',
    'but = anOther',
    'in = goingOver',
    'in = toThisOther',
    'it = onlyUnites',
    'it = withItself',
    'it = isThus',
    'it = posited',
    'it = asReflected',
    'it = intoItself',
    'it = withSublation',
    'it = ofTheOtherness',
    'it = aSelfIdenticalSomething',
    'it = fromWhich',
    'it = theOtherness',
    'it = whichIs',
    'it = atTheSameTime',
    'it = aMoment',
    'it = ofIt',
    'it = isTherefore',
    'it = distinct',
    'it = itself',
    'it = notAppertaining',
    'it = toIt',
    'it = asSomething',
  ],
  predicates: [
    { name: 'otherOfItself', args: ['other'] },
  ],
  relations: [
    { predicate: 'alters', from: 'other', to: 'itself' },
    { predicate: 'unites', from: 'other', to: 'withItself' },
  ],
  candidateSummary: 'The other which is such for itself is the other within it, hence the other of itself and so the other of the other; therefore, the absolutely unequal in itself, that which negates itself, alters itself. But it equally remains identical with itself, for that into which it alters is the other, and this other has no additional determination; but that which alters itself is not determined in any other way than in this, to be an other; in going over to this other, it only unites with itself. It is thus posited as reflected into itself with sublation of the otherness, a self-identical something from which the otherness, which is at the same time a moment of it, is therefore distinct, itself not appertaining to it as something.',
  provenance: {
    sourceChunk: 'something-and-other-8',
    sourceOp: 'so-op-8-other-of-itself',
  },
};

export const soOp9SomethingPreservesItself: LogicalOperation = {
  id: 'so-op-9-something-preserves-itself',
  chunkId: 'something-and-other-9',
  label: 'Something preserves itself in non-being; being-for-other and being-in-itself',
  clauses: [
    'theSomething = preservesItself',
    'theSomething = inItsNonBeing',
    'it = isEssentially',
    'it = oneWithIt',
    'it = andEssentially',
    'it = notOne',
    'it = withIt',
    'it = therefore',
    'it = stands',
    'it = inReference',
    'it = toAnOtherness',
    'it = withoutBeing',
    'it = justThisOtherness',
    'theOtherness = isAtOnce',
    'theOtherness = containedInIt',
    'theOtherness = andYet',
    'theOtherness = separatedFromIt',
    'theOtherness = itIs',
    'theOtherness = beingForOther',
    'existence = asSuch',
    'existence = isAnImmediate',
    'existence = bareOfReferences',
    'or = itIs',
    'or = inTheDetermination',
    'or = ofBeing',
    'however = asIncluding',
    'however = nonBeing',
    'however = withinItself',
    'existence = isDeterminateBeing',
    'existence = beingNegated',
    'existence = withinItself',
    'existence = andThen',
    'existence = inTheFirstInstance',
    'existence = anOther',
    'but = since',
    'but = inBeingNegated',
    'but = itPreservesItself',
    'but = atTheSameTime',
    'but = itIs',
    'but = only',
    'but = beingForOther',
    'it = preservesItself',
    'it = inItsNonBeing',
    'it = andIs',
    'it = being',
    'not = however',
    'not = beingInGeneral',
    'not = butBeing',
    'not = withReference',
    'not = toItself',
    'not = inContrast',
    'not = toItsReference',
    'not = toTheOther',
    'not = asSelfEquality',
    'not = inContrast',
    'not = toItsInequality',
    'such = aBeing',
    'such = isBeingInItself',
  ],
  predicates: [
    { name: 'preservesItself', args: ['something'] },
    { name: 'beingForOther', args: ['something'] },
    { name: 'beingInItself', args: ['something'] },
  ],
  relations: [
    { predicate: 'preserves', from: 'something', to: 'inNonBeing' },
    { predicate: 'is', from: 'being', to: 'beingInItself' },
  ],
  candidateSummary: 'The something preserves itself in its non-being; it is essentially one with it, and essentially not one with it. It therefore stands in reference to an otherness without being just this otherness. The otherness is at once contained in it and yet separated from it; it is being-for-other. Existence as such is an immediate, bare of references; or, it is in the determination of being. However, as including non-being within itself, existence is determinate being, being negated within itself, and then in the first instance an other; but, since in being negated it preserves itself at the same time, it is only being-for-other. It preserves itself in its non-being and is being; not, however, being in general but being with reference to itself in contrast to its reference to the other, as self-equality in contrast to its inequality. Such a being is being-in-itself.',
  provenance: {
    sourceChunk: 'something-and-other-9',
    sourceOp: 'so-op-9-something-preserves-itself',
  },
};

export const soOp10TwoPairs: LogicalOperation = {
  id: 'so-op-10-two-pairs',
  chunkId: 'something-and-other-10',
  label: 'Two pairs of determinations; truth is connection',
  clauses: [
    'beingForOther = andBeingInItself',
    'beingForOther = constitute',
    'beingForOther = theTwoMoments',
    'beingForOther = ofSomething',
    'there = areHere',
    'there = twoPairs',
    'there = ofDeterminations',
    'one = somethingAndOther',
    'two = beingForOther',
    'two = andBeingInItself',
    'theFormer = contain',
    'theFormer = theNonConnectedness',
    'theFormer = ofTheirDeterminateness',
    'something = andOther',
    'something = fallApart',
    'but = theirTruth',
    'but = isTheirConnection',
    'beingForOther = andBeingInItself',
    'beingForOther = areTherefore',
    'beingForOther = theSameDeterminations',
    'beingForOther = positedAsMoments',
    'beingForOther = ofOneAndTheSame',
    'beingForOther = unity',
    'beingForOther = asDeterminations',
    'beingForOther = whichAre',
    'beingForOther = connections',
    'beingForOther = andWhich',
    'beingForOther = inTheirUnity',
    'beingForOther = remain',
    'beingForOther = inTheUnity',
    'beingForOther = ofExistence',
    'each = thusItself',
    'each = contains',
    'each = withinIt',
    'each = atTheSameTime',
    'each = alsoTheMoment',
    'each = diverseFromIt',
    'being = andNothing',
    'being = inTheirUnity',
    'being = whichIs',
    'being = existence',
    'being = areNoLonger',
    'being = beingAndNothing',
    'these = theyAre',
    'these = only',
    'these = outside',
    'these = theirUnity',
    'so = inTheirRestlessUnity',
    'so = inBecoming',
    'so = theyAre',
    'so = comingToBe',
    'so = andCeasingToBe',
    'in = theSomething',
    'being = isBeingInItself',
    'now = asSelfReference',
    'now = selfEquality',
    'being = isNoLonger',
    'being = immediately',
    'but = isSelfReference',
    'but = onlyAs',
    'but = theNonBeing',
    'but = ofOtherness',
    'but = asExistence',
    'but = reflected',
    'but = intoItself',
    'theSame = goesFor',
    'theSame = nonBeing',
    'as = theMoment',
    'as = ofSomething',
    'as = inThisUnity',
    'as = ofBeingAndNonBeing',
    'it = isNot',
    'it = nonExistence',
    'it = inGeneral',
    'it = butIs',
    'it = theOther',
    'it = andMore',
    'it = determinedly',
    'it = accordingAs',
    'it = being',
    'it = isAtTheSameTime',
    'it = distinguishedFromIt',
    'it = itIs',
    'it = reference',
    'it = toItsNonExistence',
    'it = beingForOther',
  ],
  predicates: [
    { name: 'twoPairs', args: ['determinations'] },
  ],
  relations: [
    { predicate: 'is', from: 'truth', to: 'connection' },
  ],
  candidateSummary: 'Being-for-other and being-in-itself constitute the two moments of something. There are here two pairs of determinations: (1) something and other; (2) being-for-other and being-in-itself. The former contain the non-connectedness of their determinateness; something and other fall apart. But their truth is their connection; being-for-other and being-in-itself are therefore the same determinations posited as moments of one and the same unity, as determinations which are connections and which, in their unity, remain in the unity of existence. Each thus itself contains within it, at the same time, also the moment diverse from it. Being and nothing in their unity, which is existence, are no longer being and nothing (these they are only outside their unity); so in their restless unity, in becoming, they are coming-to-be and ceasing-to-be. In the something, being is being-in-itself. Now, as self-reference, self-equality, being is no longer immediately, but is self-reference only as the non-being of otherness (as existence reflected into itself). The same goes for non-being: as the moment of something in this unity of being and non-being: it is not non-existence in general but is the other, and more determinedly, according as being is at the same time distinguished from it, it is reference to its non-existence, being-for-other.',
  provenance: {
    sourceChunk: 'something-and-other-10',
    sourceOp: 'so-op-10-two-pairs',
  },
};

export const soOp11BeingInItselfNegative: LogicalOperation = {
  id: 'so-op-11-being-in-itself-negative',
  chunkId: 'something-and-other-11',
  label: 'Being-in-itself: negative reference; has non-being in it',
  clauses: [
    'hence = beingInItself',
    'hence = is',
    'first = negativeReference',
    'first = toNonExistence',
    'it = hasOtherness',
    'it = outsideIt',
    'it = andIs',
    'it = opposedToIt',
    'in = soFarAs',
    'something = isInItself',
    'it = isWithdrawn',
    'it = fromBeingOther',
    'it = andBeingForOther',
    'but = second',
    'it = hasNonBeing',
    'it = alsoRight',
    'it = inIt',
    'for = itIs',
    'for = itself',
    'for = theNonBeing',
    'for = ofBeingForOther',
    'but = beingForOther',
    'but = is',
    'first = theNegation',
    'first = ofTheSimpleReference',
    'first = ofBeing',
    'first = toItself',
    'first = which',
    'first = inTheFirstPlace',
    'first = isSupposed',
    'first = toBe',
    'first = existence',
    'first = andSomething',
    'in = soFarAs',
    'something = isInAnOther',
    'something = orForAnOther',
    'it = lacks',
    'it = aBeing',
    'it = ofItsOwn',
    'but = second',
    'it = isNot',
    'it = nonExistence',
    'it = asPureNothing',
    'it = butIs',
    'it = nonExistence',
    'it = thatPoints',
    'it = toBeingInItself',
    'it = asItsBeing',
    'it = reflected',
    'it = intoItself',
    'just = asConversely',
    'theBeingInItself = points',
    'theBeingInItself = toBeingForOther',
  ],
  predicates: [
    { name: 'negativeReference', args: ['beingInItself'] },
  ],
  relations: [
    { predicate: 'has', from: 'beingInItself', to: 'nonBeing' },
  ],
  candidateSummary: 'Hence being-in-itself is, first, negative reference to non-existence; it has otherness outside it and is opposed to it; in so far as something is in itself, it is withdrawn from being-other and being-for-other. But, second, it has non-being also right in it; for it is itself the non-being of being-for-other. But being-for-other is, first, the negation of the simple reference of being to itself which, in the first place, is supposed to be existence and something; in so far as something is in an other or for an other, it lacks a being of its own. But, second, it is not non-existence as pure nothing; it is non-existence that points to being-in-itself as its being reflected into itself, just as conversely the being-in-itself points to being-for-other.',
  provenance: {
    sourceChunk: 'something-and-other-11',
    sourceOp: 'so-op-11-being-in-itself-negative',
  },
};

export const soOp12BothMoments: LogicalOperation = {
  id: 'so-op-12-both-moments',
  chunkId: 'something-and-other-12',
  label: 'Both moments of something; identity of being-in-itself and being-for-other',
  clauses: [
    'both = moments',
    'both = areDeterminations',
    'both = ofOneAndTheSame',
    'both = namely',
    'both = ofSomething',
    'something = isInItself',
    'something = inSoFarAs',
    'something = itHasReturned',
    'something = fromTheBeingForOther',
    'something = backToItself',
    'but = something',
    'but = hasAlso',
    'but = aDetermination',
    'but = orCircumstance',
    'whether = inItself',
    'whether = here',
    'whether = theAccent',
    'whether = isOn',
    'whether = theIn',
    'whether = orInIt',
    'in = soFarAs',
    'this = circumstance',
    'this = isInIt',
    'this = externally',
    'it = is',
    'it = aBeingForOther',
    'this = leads',
    'this = toA',
    'this = furtherDetermination',
    'beingInItself = andBeingForOther',
    'beingInItself = areDifferent',
    'beingInItself = atFirst',
    'but = that',
    'something = alsoHas',
    'something = inIt',
    'something = what',
    'something = itIs',
    'something = inItself',
    'something = andConversely',
    'something = isInItself',
    'something = also',
    'something = what',
    'something = itIs',
    'something = asBeingForOther',
    'this = isTheIdentity',
    'this = ofBeingInItself',
    'this = andBeingForOther',
    'in = accordance',
    'in = withTheDetermination',
    'in = thatTheSomething',
    'in = isItself',
    'in = oneAndTheSame',
    'in = something',
    'in = ofBothMoments',
    'and = these',
    'and = areInIt',
    'and = therefore',
    'and = undivided',
    'this = identity',
    'this = alreadyOccurs',
    'this = formally',
    'this = inTheSphere',
    'this = ofExistence',
    'but = moreExplicitly',
    'but = inTheTreatment',
    'but = ofEssence',
    'but = andLater',
    'but = ofTheRelations',
    'but = ofInteriority',
    'but = andExternality',
    'and = inTheMost',
    'and = determinateForm',
    'and = inTheTreatment',
    'and = ofTheIdea',
    'and = asTheUnity',
    'and = ofConcept',
    'and = andActuality',
  ],
  predicates: [
    { name: 'identity', args: ['beingInItself', 'beingForOther'] },
  ],
  relations: [
    { predicate: 'is', from: 'bothMoments', to: 'determinationsOfSomething' },
  ],
  candidateSummary: 'Both moments are determinations of one and the same, namely of something. Something is in-itself in so far as it has returned from the being-for-other back to itself. But something has also a determination or circumstance, whether in itself (here the accent is on the in) or in it; in so far as this circumstance is in it externally, it is a being-for-other. This leads to a further determination. Being-in-itself and being-for-other are different at first. But that something also has in it what it is in itself and conversely is in itself also what it is as being-for-other this is the identity of being-in-itself and being-for-other, in accordance with the determination that the something is itself one and the same something of both moments, and these are in it, therefore, undivided. This identity already occurs formally in the sphere of existence, but more explicitly in the treatment of essence and later of the relations of interiority and externality, and in the most determinate form in the treatment of the idea, as the unity of concept and actuality.',
  provenance: {
    sourceChunk: 'something-and-other-12',
    sourceOp: 'so-op-12-both-moments',
  },
};

export const soOp13InItselfAsAbstract: LogicalOperation = {
  id: 'so-op-13-in-itself-as-abstract',
  chunkId: 'something-and-other-13',
  label: 'In-itself as abstract; thing-in-itself critique I',
  clauses: [
    'opinion = hasIt',
    'opinion = thatWith',
    'opinion = theInItself',
    'opinion = somethingLofty',
    'opinion = isBeingSaid',
    'opinion = asWith',
    'opinion = theInner',
    'but = what',
    'something = isOnly',
    'something = inItself',
    'something = isAlso',
    'something = only',
    'something = inIt',
    'inItself = isA',
    'inItself = merelyAbstract',
    'inItself = andHence',
    'inItself = itselfExternal',
    'inItself = determination',
    'theExpressions = thereIs',
    'theExpressions = nothingInIt',
    'theExpressions = orThereIs',
    'theExpressions = somethingInIt',
    'theExpressions = imply',
    'theExpressions = though',
    'theExpressions = somewhatObscurely',
    'theExpressions = thatWhat',
    'theExpressions = isIn',
    'theExpressions = aThing',
    'theExpressions = alsoPertains',
    'theExpressions = toItsInItselfness',
    'theExpressions = toItsInner',
    'theExpressions = trueWorth',
  ],
  predicates: [
    { name: 'abstract', args: ['inItself'] },
  ],
  relations: [
    { predicate: 'is', from: 'inItself', to: 'abstract' },
  ],
  candidateSummary: 'Opinion has it that with the in-itself something lofty is being said, as with the inner; but what something is only in itself, is also only in it; in-itself is a merely abstract, and hence itself external determination. The expressions: there is nothing in it, or there is something in it, imply, though somewhat obscurely, that what is in a thing also pertains to its in-itselfness, to its inner, true worth.',
  provenance: {
    sourceChunk: 'something-and-other-13',
    sourceOp: 'so-op-13-in-itself-as-abstract',
  },
};

export const soOp14ThingInItselfCritique: LogicalOperation = {
  id: 'so-op-14-thing-in-itself-critique',
  chunkId: 'something-and-other-14',
  label: 'Thing-in-itself critique II: empty abstraction',
  clauses: [
    'it = mayBe',
    'it = observed',
    'it = thatHere',
    'it = weHave',
    'it = theMeaning',
    'it = ofTheThingInItself',
    'it = isA',
    'it = verySimple',
    'it = abstraction',
    'though = itWas',
    'though = forAWhile',
    'though = aVery',
    'though = importantDetermination',
    'though = somethingSophisticated',
    'though = asItWere',
    'just = asTheProposition',
    'just = thatWe',
    'just = knowNothing',
    'just = ofWhat',
    'just = thingsAre',
    'just = inThemselves',
    'just = wasA',
    'just = muchValued',
    'just = pieceOfWisdom',
    'things = areCalled',
    'things = inThemselves',
    'things = inSoFarAs',
    'things = abstraction',
    'things = isMade',
    'things = fromAll',
    'things = beingForOther',
    'which = reallyMeans',
    'in = soFarAs',
    'they = areThought',
    'they = withoutAll',
    'they = determination',
    'they = asNothing',
    'in = thisSense',
    'of = course',
    'it = isImpossible',
    'it = toKnow',
    'it = what',
    'it = theThingInItself',
    'it = is',
    'for = theQuestion',
    'for = what',
    'for = callsFor',
    'for = determinations',
    'for = toBeProduced',
    'but = since',
    'theThings = ofWhich',
    'theThings = theDeterminations',
    'theThings = areCalledFor',
    'theThings = areAtTheSameTime',
    'theThings = presumed',
    'theThings = toBe',
    'theThings = thingsInThemselves',
    'theThings = whichMeans',
    'theThings = precisely',
    'theThings = withoutDetermination',
    'the = impossibility',
    'the = ofAnAnswer',
    'the = isThoughtlessly',
    'the = implanted',
    'the = inTheQuestion',
    'or = else',
    'a = senselessAnswer',
    'a = isGiven',
    'theThingInItself = isTheSame',
    'theThingInItself = asThat',
    'theThingInItself = absolute',
    'theThingInItself = ofWhich',
    'theThingInItself = nothing',
    'theThingInItself = isKnown',
    'theThingInItself = except',
    'theThingInItself = thatInIt',
    'theThingInItself = allIsOne',
    'what = thereIs',
    'what = inThese',
    'what = thingsInThemselves',
    'what = isTherefore',
    'what = veryWell',
    'what = known',
    'they = areAsSuch',
    'they = nothingBut',
    'they = emptyAbstractions',
    'they = voidOfTruth',
  ],
  predicates: [
    { name: 'thingInItself', args: ['thing'] },
  ],
  relations: [
    { predicate: 'is', from: 'thingInItself', to: 'emptyAbstraction' },
  ],
  candidateSummary: 'It may be observed that here we have the meaning of the thing-in-itself. It is a very simple abstraction, though it was for a while a very important determination, something sophisticated, as it were, just as the proposition that we know nothing of what things are in themselves was a much valued piece of wisdom. Things are called "in-themselves" in so far as abstraction is made from all being-for-other, which really means, in so far as they are thought without all determination, as nothing. In this sense, of course, it is impossible to know what the thing-in-itself is. For the question "what?" calls for determinations to be produced; but since the things of which the determinations are called for are at the same time presumed to be things-in-themselves, which means precisely without determination, the impossibility of an answer is thoughtlessly implanted in the question, or else a senseless answer is given. The thing-in-itself is the same as that absolute of which nothing is known except that in it all is one. What there is in these things-in-themselves is therefore very well known; they are as such nothing but empty abstractions void of truth.',
  provenance: {
    sourceChunk: 'something-and-other-14',
    sourceOp: 'so-op-14-thing-in-itself-critique',
  },
};

export const soOp15ThingInItselfInTruth: LogicalOperation = {
  id: 'so-op-15-thing-in-itself-in-truth',
  chunkId: 'something-and-other-15',
  label: 'Thing-in-itself in truth: concept (concrete, cognizable)',
  clauses: [
    'what = however',
    'theThingInItself = inTruth',
    'theThingInItself = is',
    'what = there',
    'what = basically',
    'what = isInIt',
    'of = this',
    'theLogic = isThe',
    'theLogic = exposition',
    'but = inThis',
    'but = logic',
    'something = better',
    'something = isUnderstood',
    'something = byThe',
    'something = inItself',
    'something = than',
    'something = anAbstraction',
    'namely = what',
    'something = is',
    'something = inItsConcept',
    'but = thisConcept',
    'but = isInItself',
    'but = concrete',
    'as = concept',
    'in = principle',
    'conceptually = graspable',
    'and = asDetermined',
    'and = asThe',
    'and = connectedWhole',
    'and = ofItsDeterminations',
    'inherently = cognizable',
  ],
  predicates: [
    { name: 'concept', args: ['thingInItself'] },
  ],
  relations: [
    { predicate: 'is', from: 'thingInItself', to: 'concept' },
  ],
  candidateSummary: 'What, however, the thing-in-itself in truth is, what there basically is in it, of this the Logic is the exposition. But in this Logic something better is understood by the in-itself than an abstraction, namely, what something is in its concept; but this concept is in itself concrete: as concept, in principle conceptually graspable; and, as determined and as the connected whole of its determinations, inherently cognizable.',
  provenance: {
    sourceChunk: 'something-and-other-15',
    sourceOp: 'so-op-15-thing-in-itself-in-truth',
  },
};

export const soOp16Positedness: LogicalOperation = {
  id: 'so-op-16-positedness',
  chunkId: 'something-and-other-16',
  label: 'Positedness; transition vs positing; in-itself vs posited',
  clauses: [
    'beingInItself = hasAtFirst',
    'beingInItself = theBeingForOther',
    'beingInItself = asAMoment',
    'beingInItself = standing',
    'beingInItself = overAgainstIt',
    'but = positedness',
    'but = alsoComes',
    'but = toBe',
    'but = positioned',
    'but = overAgainstIt',
    'and = although',
    'in = thisExpression',
    'beingForOther = isAlso',
    'beingForOther = included',
    'theExpression = still',
    'theExpression = contains',
    'theExpression = theDetermination',
    'theExpression = ofTheBending',
    'theExpression = back',
    'theExpression = whichHas',
    'theExpression = alreadyOccurred',
    'theExpression = ofThat',
    'theExpression = whichIs',
    'theExpression = notInItself',
    'theExpression = intoThat',
    'theExpression = whereinIt',
    'theExpression = isPositive',
    'theExpression = andThis',
    'theExpression = isIts',
    'theExpression = beingInItself',
    'beingInItself = isNormally',
    'beingInItself = toBeTaken',
    'beingInItself = asAn',
    'beingInItself = abstractWay',
    'beingInItself = ofExpressing',
    'beingInItself = theConcept',
    'positing = strictlySpeaking',
    'positing = firstOccurs',
    'positing = inTheSphere',
    'positing = ofEssence',
    'positing = ofObjectiveReflection',
    'theGround = posits',
    'theGround = thatWhich',
    'theGround = isGrounded',
    'theGround = throughIt',
    'more = strongly',
    'theCause = produces',
    'theCause = anEffect',
    'theCause = anExistence',
    'theCause = whoseSubsistence',
    'theCause = isImmediately',
    'theCause = negated',
    'theCause = andWhich',
    'theCause = carries',
    'theCause = theMeaning',
    'theCause = thatIt',
    'theCause = hasIts',
    'theCause = substance',
    'theCause = itsBeing',
    'theCause = inAnOther',
    'in = theSphere',
    'in = ofBeing',
    'existence = onlyEmerges',
    'existence = outOf',
    'existence = becoming',
    'or = again',
    'with = theSomething',
    'anOther = isPosited',
    'with = theFinite',
    'anInfinite = isPosited',
    'but = theFinite',
    'but = doesNot',
    'but = bringForth',
    'but = theInfinite',
    'but = doesNot',
    'but = positIt',
    'in = theSphere',
    'in = ofBeing',
    'theSelfDetermining = ofTheConcept',
    'theSelfDetermining = isAtFirst',
    'theSelfDetermining = onlyInItself',
    'theSelfDetermining = orImplicit',
    'and = forThatReason',
    'it = isCalled',
    'it = aTransition',
    'it = orPassingOver',
    'and = theReflecting',
    'and = determinations',
    'and = ofBeing',
    'such = asSomethingAndOther',
    'such = orFiniteAndInfinite',
    'although = theyEssentially',
    'although = pointTo',
    'although = oneAnother',
    'or = areAs',
    'or = beingForOther',
    'also = stand',
    'also = onTheirOwn',
    'also = qualitatively',
    'theOther = exists',
    'theFinite = likeTheInfinite',
    'theFinite = isEqually',
    'theFinite = toBe',
    'theFinite = regarded',
    'theFinite = asAn',
    'theFinite = immediateExistent',
    'theFinite = thatStands',
    'theFinite = firm',
    'theFinite = onItsOwn',
    'theMeaning = ofEach',
    'theMeaning = appears',
    'theMeaning = complete',
    'theMeaning = even',
    'theMeaning = withoutItsOther',
    'thePositive = andTheNegative',
    'thePositive = onTheContrary',
    'cause = andEffect',
    'however = much',
    'they = areTaken',
    'they = inIsolation',
    'they = haveAtTheSameTime',
    'they = noMeaning',
    'they = each',
    'they = withoutTheOther',
    'their = reflectiveShining',
    'their = inEach',
    'their = ofItsOther',
    'their = isPresent',
    'their = rightInThem',
    'in = theDifferent',
    'in = cycles',
    'in = ofDetermination',
    'and = especially',
    'in = theProgress',
    'in = ofTheExposition',
    'or = morePrecisely',
    'in = theProgress',
    'in = ofTheConcept',
    'in = inTheExposition',
    'in = ofItself',
    'it = isOf',
    'it = capitalConcern',
    'it = always',
    'it = toClearly',
    'it = distinguish',
    'it = what',
    'it = stillIs',
    'it = inItself',
    'it = orImplicitly',
    'it = andWhat',
    'it = isPosited',
    'it = how',
    'it = determinations',
    'it = areIn',
    'it = theConcept',
    'it = andHow',
    'it = theyAre',
    'it = asPosited',
    'it = orAs',
    'it = existingForOther',
    'this = isA',
    'this = distinction',
    'this = thatBelongs',
    'this = only',
    'this = toThe',
    'this = dialecticalDevelopment',
    'this = andOne',
    'this = unknown',
    'this = toMetaphysical',
    'this = philosophizing',
    'this = toWhich',
    'this = theCritical',
    'this = alsoBelongs',
    'the = definitions',
    'the = ofMetaphysics',
    'like = itsPresuppositions',
    'like = distinctions',
    'like = andConclusions',
    'like = areMeant',
    'like = toAssert',
    'like = andProduce',
    'like = only',
    'like = theExistent',
    'like = andThat',
    'like = too',
    'like = asExistentInItself',
  ],
  predicates: [
    { name: 'positedness', args: ['being'] },
  ],
  relations: [
    { predicate: 'is', from: 'positedness', to: 'overAgainstBeingInItself' },
  ],
  candidateSummary: 'Being-in-itself has at first the being-for-other as a moment standing over against it. But positedness also comes to be positioned over against it, and, although in this expression being-for-other is also included, the expression still contains the determination of the bending back, which has already occurred, of that which is not in itself into that wherein it is positive, and this is its being-in-itself. Being-in-itself is normally to be taken as an abstract way of expressing the concept; positing, strictly speaking, first occurs in the sphere of essence, of objective reflection; the ground posits that which is grounded through it; more strongly, the cause produces an effect, an existence whose subsistence is immediately negated and which carries the meaning that it has its substance, its being, in an other. In the sphere of being, existence only emerges out of becoming. Or again, with the something an other is posited; with the finite, an infinite; but the finite does not bring forth the infinite, does not posit it. In the sphere of being, the self-determining of the concept is at first only in itself or implicit, and for that reason it is called a transition or passing over. And the reflecting determinations of being, such as something and other, or finite and infinite, although they essentially point to one another, or are as being-for-other, also stand on their own qualitatively; the other exists; the finite, like the infinite, is equally to be regarded as an immediate existent that stands firm on its own; the meaning of each appears complete even without its other. The positive and the negative, on the contrary, cause and effect, however much they are taken in isolation, have at the same time no meaning each without the other; their reflective shining in each other, the shine in each of its other, is present right in them. In the different cycles of determination and especially in the progress of the exposition, or, more precisely, in the progress of the concept in the exposition of itself, it is of capital concern always to clearly distinguish what still is in itself or implicitly and what is posited, how determinations are in the concept and how they are as posited or as existing-for-other. This is a distinction that belongs only to the dialectical development and one unknown to metaphysical philosophizing (to which the critical also belongs); the definitions of metaphysics, like its presuppositions, distinctions, and conclusions, are meant to assert and produce only the existent and that, too, as existent-in-itself.',
  provenance: {
    sourceChunk: 'something-and-other-16',
    sourceOp: 'so-op-16-positedness',
  },
};

export const soOp17IdentityInSomething: LogicalOperation = {
  id: 'so-op-17-identity-in-something',
  chunkId: 'something-and-other-17',
  label: 'Identity in something; determination as quality',
  clauses: [
    'in = theUnity',
    'in = ofTheSomething',
    'in = withItself',
    'beingForOther = isIdentical',
    'beingForOther = with',
    'beingForOther = itsInItself',
    'theBeingForOther = isThus',
    'theBeingForOther = inTheSomething',
    'theDeterminateness = thus',
    'theDeterminateness = reflected',
    'theDeterminateness = intoItself',
    'theDeterminateness = isTherefore',
    'theDeterminateness = again',
    'theDeterminateness = aSimple',
    'theDeterminateness = existent',
    'theDeterminateness = andHence',
    'theDeterminateness = again',
    'theDeterminateness = aQuality',
    'theDeterminateness = determination',
  ],
  predicates: [
    { name: 'determination', args: ['quality'] },
  ],
  relations: [
    { predicate: 'is', from: 'determinateness', to: 'quality' },
  ],
  candidateSummary: 'In the unity of the something with itself, being-for-other is identical with its in-itself; the being-for-other is thus in the something. The determinateness thus reflected into itself is therefore again a simple existent and hence again a quality: determination.',
  provenance: {
    sourceChunk: 'something-and-other-17',
    sourceOp: 'so-op-17-identity-in-something',
  },
};

export const somethingAndOtherOperations: LogicalOperation[] = [
  soOp1Outline,
  soOp2Introduction,
  soOp3BothExistents,
  soOp4ThisAsSubjective,
  soOp5OthernessAsExternal,
  soOp6SamenessInReflection,
  soOp7OtherAsToHeteron,
  soOp8OtherOfItself,
  soOp9SomethingPreservesItself,
  soOp10TwoPairs,
  soOp11BeingInItselfNegative,
  soOp12BothMoments,
  soOp13InItselfAsAbstract,
  soOp14ThingInItselfCritique,
  soOp15ThingInItselfInTruth,
  soOp16Positedness,
  soOp17IdentityInSomething,
];

