packages:
  - gdsl
  - logic
  - model
  - task

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - duckdb
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - '@prisma/engines'
  - bcrypt
  - prisma
  - sharp
