packages:
  - logic
  - model
  - task
  - gds
  - gdsl
  - reality

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - duckdb
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
