packages:
  - logic
  - model
  - task
  - model/examples/dashboard

ignoredBuiltDependencies:
  - '@firebase/util'
  - '@scarf/scarf'
  - duckdb
  - esbuild
  - protobufjs

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
