/**
 * Logical Operations: The Judgment of the Concept
 *
 * The judgment of the concept shows how the concept as "ought" relates to
 * actuality, progressing from assertoric (immediate) through problematic
 * (contingent) to apodictic (truly objective), revealing the truth of judgment.
 *
 * Dialectical Movement:
 * - Assertoric Judgment: Immediate; "this house is good"
 * - Problematic Judgment: Subject differentiated into ought and constitution
 * - Apodictic Judgment: Truly objective; ground in constitution
 *
 * This judgment reveals how the concept measures actuality against itself,
 * culminating in the apodictic judgment where subject and predicate correspond
 * and the copula becomes replete of content, transitioning to syllogism.
 */

import type { LogicalOperation } from '../../../types';

// ============================================================================
// INTRODUCTION: Concept as Ought
// ============================================================================

export const concOp1IntroductionOught: LogicalOperation = {
  id: 'conc-op-1-introduction-ought',
    chunkId: 'conc-1-introduction-ought',
    label: 'Introduction: Concept as Ought; True Adjudication',
    clauses: [
      'judgmentsOfExistence = hardlySignOfGreatPower',
      'judgmentsOfReflection = morePropositions',
      'judgmentOfNecessity.subjectMatter = objectiveUniversality',
      'judgmentOfConcept.connection = withConcept',
      'concept.atBasis = ofJudgment',
      'concept = ought',
      'reality.mayConform = toOught',
      'reality.mayNotConform = toOught',
      'judgmentOfConcept.firstContains = trueAdjudication',
      'predicates = "good"',
      'predicates = "bad"',
      'predicates = "true"',
      'predicates = "right"',
      'fact.measured = againstConcept',
      'fact.measured = asOught',
      'fact.inAgreement = withOught',
      'fact.notInAgreement = withOught',
    ],
    predicates: [
      { name: 'hardlySignOfGreatPower', args: ['judgmentsOfExistence'] },
      { name: 'morePropositions', args: ['judgmentsOfReflection'] },
      { name: 'objectiveUniversality', args: ['judgmentOfNecessity.subjectMatter'] },
      { name: 'ought', args: ['concept'] },
      { name: 'trueAdjudication', args: ['judgmentOfConcept.firstContains'] },
      { name: 'measured', args: ['fact', 'againstConcept'] },
    ],
    relations: [
      { predicate: 'atBasis', from: 'concept', to: 'ofJudgment' },
      { predicate: 'is', from: 'concept', to: 'ought' },
      { predicate: 'mayConform', from: 'reality', to: 'toOught' },
      { predicate: 'measured', from: 'fact', to: 'againstConcept' },
    ],
    candidateSummary: 'To know how to form judgments of existence, such as "the rose is red," "the snow is white," etc., hardly counts as a sign of great power of judgment. The judgments of reflection are more in the nature of propositions; to be sure, in the judgment of necessity the subject matter is present in its objective universality, but it is only in the judgment now to be considered that its connection with the concept is to be found. The concept is at the basis of this judgment, and it is there with reference to the subject matter, as an ought to which reality may or may not conform. This is the judgment, therefore, that first contains true adjudication; the predicates, "good," "bad," "true," "right," etc., express that the fact is measured against the concept as an ought which is simply presupposed, and is, or is not, in agreement with it.',
    provenance: {
      sourceChunk: 'conc-1-introduction-ought',
      sourceOp: 'conc-op-1-introduction-ought',
    },
};

export const concOp2Modality: LogicalOperation = {
  id: 'conc-op-2-modality',
    chunkId: 'conc-2-modality',
    label: 'Judgment of Modality: Problematic, Assertoric, Apodictic; Objective Truth',
    clauses: [
      'judgmentOfConcept.called = judgmentOfModality',
      'judgmentOfModality.regarded = asContainingForm',
      'form = connection(subject, predicate)',
      'form.obtains = inExternalUnderstanding',
      'form.concerned = withValueOfCopula',
      'form.concerned = onlyInConnectionWithThought',
      'problematic = affirmationNegationOptional',
      'problematic = affirmationNegationPossible',
      'assertoric = takenAsTrue',
      'assertoric = takenAsActual',
      'apodictic = takenAsNecessary',
      'concept = subjective',
      'concept.comesIntoPlay = inJudgment',
      'concept.relates = toImmediateActuality',
      'subjectivity != confusedWithExternalReflection',
      'concept.emerged = fromDisjunctiveJudgment',
      'concept = oppositeOfMereMode',
      'earlierJudgments = subjective',
      'earlierJudgments.rest = onAbstractOneSidedness',
      'earlierJudgments.concept = lost',
      'judgmentOfConcept = objective',
      'judgmentOfConcept = truth',
      'judgmentOfConcept.rests = onConcept',
      'judgmentOfConcept.rests = inDeterminatenessAsConcept',
      'judgmentOfConcept.rests != inExternalReflection',
      'judgmentOfConcept.rests != inAccidentalThought',
    ],
    predicates: [
      { name: 'judgmentOfModality', args: ['judgmentOfConcept.called'] },
      { name: 'problematic', args: ['affirmationNegationOptional'] },
      { name: 'assertoric', args: ['takenAsTrue'] },
      { name: 'apodictic', args: ['takenAsNecessary'] },
      { name: 'objective', args: ['judgmentOfConcept'] },
      { name: 'truth', args: ['judgmentOfConcept'] },
    ],
    relations: [
      { predicate: 'called', from: 'judgmentOfConcept', to: 'judgmentOfModality' },
      { predicate: 'comesIntoPlay', from: 'concept', to: 'inJudgment' },
      { predicate: 'relates', from: 'concept', to: 'toImmediateActuality' },
      { predicate: 'emerged', from: 'concept', to: 'fromDisjunctiveJudgment' },
      { predicate: 'is', from: 'judgmentOfConcept', to: 'objective' },
      { predicate: 'is', from: 'judgmentOfConcept', to: 'truth' },
    ],
    candidateSummary: 'The judgment of the concept has been called the judgment of modality, and has been regarded as containing the form of the connection of subject and predicate as this obtains in an external understanding, and as concerned with the value of the copula only in connection with thought. Accordingly, judgment is said to be problematic when the affirmation or negation is taken as optional or possible; assertoric, when it is taken as true, that is, actual, and apodictic when it is taken as necessary. It is easy to see why it would be an easy step in this judgment to go outside the judgment itself and to regard its determination as something merely subjective. For it is the concept here, the subjective, that comes into play again in judgment and relates to an immediate actuality. But this subjectivity is not to be confused with external reflection, which is of course also something subjective but in a different sense than the concept itself; on the contrary, the concept that has again emerged out of the disjunctive judgment is the very opposite of a mere mode or manner. The earlier judgments are subjective in this sense, for they rest on an abstract one-sidedness in which the concept is lost. But the judgment of the concept is instead objective and, as contrasted with the others, it is the truth, for it rests on the concept precisely in its determinateness as concept, not in some external reflection or with reference to some subjective, that is, accidental, thought.',
    provenance: {
      sourceChunk: 'conc-2-modality',
      sourceOp: 'conc-op-2-modality',
    },
};

export const concOp3Diremption: LogicalOperation = {
  id: 'conc-op-3-diremption',
    chunkId: 'conc-3-diremption',
    label: 'Concept from Disjunctive; Diremption into Extremes',
    clauses: [
      'inDisjunctiveJudgment.concept = identity',
      'identity = of(universalNature, particularization)',
      'relation.sublated = inDisjunctiveJudgment',
      'concretion = simpleResult',
      'concretion.mustDevelop = intoTotality',
      'moments.collapsed = intoConcretion',
      'moments.notStand = overAgainstEachOther',
      'moments.notStand = inDeterminateSelfSubsistence',
      'shortcoming = negativeUnityNotDetermined',
      'negativeUnityNotDetermined = asSingularity',
      'objectiveUniversality.attained = completion',
      'objectiveUniversality.attained = inParticularization',
      'negativeUnity.retreated = intoObjectiveUniversality',
      'negativeUnity.notDetermined = asThirdMoment',
      'negativeUnity.notDetermined = asSingularity',
      'result = negativeUnity',
      'result = singularity',
      'determinateness.mustPosit = itsNegativity',
      'determinateness.mustPart = intoExtremes',
      'determinateness.concludes = inSyllogisticConclusion',
      'proximateDiremption = judgment',
      'unity.posited1 = asSubject',
      'unity.posited1 = asImmediateSingular',
      'unity.posited2 = asPredicate',
      'unity.posited2 = asDeterminateConnection',
    ],
    predicates: [
      { name: 'identity', args: ['of', 'universalNature', 'particularization'] },
      { name: 'simpleResult', args: ['concretion'] },
      { name: 'negativeUnityNotDetermined', args: ['shortcoming', 'asSingularity'] },
      { name: 'negativeUnity', args: ['result'] },
      { name: 'singularity', args: ['result'] },
      { name: 'syllogisticConclusion', args: ['determinateness.concludes'] },
    ],
    relations: [
      { predicate: 'is', from: 'inDisjunctiveJudgment.concept', to: 'identity' },
      { predicate: 'sublated', from: 'relation', to: 'inDisjunctiveJudgment' },
      { predicate: 'mustDevelop', from: 'concretion', to: 'intoTotality' },
      { predicate: 'mustPosit', from: 'determinateness', to: 'itsNegativity' },
      { predicate: 'mustPart', from: 'determinateness', to: 'intoExtremes' },
      { predicate: 'concludes', from: 'determinateness', to: 'inSyllogisticConclusion' },
    ],
    candidateSummary: 'In the disjunctive judgment, the concept was posited as the identity of universal nature and its particularization, and with that the relation of the judgment was sublated. This concretion of universality and particularization is at first a simple result; it must now further develop itself into totality, for its moments have at first collapsed into it and do not as yet stand over against each other in determinate self-subsistence. The shortcoming of that result may also be stated more incisively by saying that although in the disjunctive judgment the objective universality has attained completion in its particularization, the negative unity of the latter has only retreated into it and has not as yet determined itself as the third moment, that of singularity. But to the extent that the result is itself negative unity, it is already this singularity; it is then this one determinateness alone that must now posit its negativity, that must part itself into extremes and in this way concludes its development in the syllogistic conclusion. The proximate diremption of this unity is the judgment in which the unity is posited first as subject, as an immediate singular, and then as predicate, as the determinate connection of its moments.',
    provenance: {
      sourceChunk: 'conc-3-diremption',
      sourceOp: 'conc-op-3-diremption',
    },
};

// ============================================================================
// A. THE ASSERTORIC JUDGMENT
// ============================================================================

export const concOp4AssertoricImmediate: LogicalOperation = {
  id: 'conc-op-4-assertoric-immediate',
    chunkId: 'conc-4-assertoric-immediate',
    label: 'Assertoric Judgment: Immediate; Ought and Constitution',
    clauses: [
      'judgmentOfConcept.atFirst = immediate',
      'judgmentOfConcept = assertoricJudgment',
      'subject = concreteSingular',
      'predicate.expresses = connection',
      'connection = of(actuality, determinateness, constitution)',
      'connection = toConcept',
      'example = "thisHouse is bad"',
      'example = "thisAction is good"',
      'contains1 = subjectOughtToBe',
      'universalNature.posited = asSelfSubsistentConcept',
      'contains2 = particularityConstituted',
      'particularity = externalConcreteExistence',
      'particularity.differs = fromUniversalNature',
      'particularity.indifferent = toUniversal',
      'particularity.mayConform = toUniversal',
      'particularity.mayNotConform = toUniversal',
      'constitution = singularity',
      'singularity.escapes = necessaryDetermination',
      'necessaryDetermination = ofUniversal',
      'necessaryDetermination = asParticularizationOfSpecies',
      'necessaryDetermination = asNegativePrincipleOfGenus',
      'concreteUniversality.divides = intoExtremes',
      'concept = positedUnity',
      'concept = connectingExtremes',
      'concept.stillLacking = inAssertoricJudgment',
    ],
    predicates: [
      { name: 'assertoricJudgment', args: ['judgmentOfConcept'] },
      { name: 'concreteSingular', args: ['subject'] },
      { name: 'selfSubsistentConcept', args: ['universalNature.posited'] },
      { name: 'externalConcreteExistence', args: ['particularity'] },
      { name: 'singularity', args: ['constitution'] },
    ],
    relations: [
      { predicate: 'is', from: 'judgmentOfConcept', to: 'assertoricJudgment' },
      { predicate: 'expresses', from: 'predicate', to: 'connection' },
      { predicate: 'posited', from: 'universalNature', to: 'asSelfSubsistentConcept' },
      { predicate: 'differs', from: 'particularity', to: 'fromUniversalNature' },
      { predicate: 'divides', from: 'concreteUniversality', to: 'intoExtremes' },
    ],
    candidateSummary: 'The judgment of the concept is at first immediate; as such, it is the assertoric judgment. The subject is a concrete singular in general, and the predicate expresses this same singular as the connection of its actuality, its determinateness or constitution, to its concept. ("This house is bad," "this action is good.") More closely considered, it contains, therefore, (a) that the subject ought to be something; its universal nature has posited itself as the self-subsistent concept; (b) that particularity is something constituted or an external concrete existence, not only because of its immediacy, but because it expressly differs from its self-subsisting universal nature; its external concrete existence, for its part, because of this self-subsistence of the concept, is also indifferent with respect to the universal and may or may not conform to it. This constitution is the singularity which in the disjunctive judgment escapes the necessary determination of the universal, a determination that exists only as the particularization of the species and as the negative principle of the genus. Thus the concrete universality that has come out of the disjunctive judgment divides in the assertoric judgment into the form of extremes to which the concept itself, as the posited unity connecting them, is still lacking.',
    provenance: {
      sourceChunk: 'conc-4-assertoric-immediate',
      sourceOp: 'conc-op-4-assertoric-immediate',
    },
};

export const concOp5AssertoricSubjective: LogicalOperation = {
  id: 'conc-op-5-assertoric-subjective',
    chunkId: 'conc-5-assertoric-subjective',
    label: 'Assertoric: Subjective Assurance; External Third',
    clauses: [
      'judgment.onlyAssertoric = soFar',
      'credential = subjectiveAssurance',
      'goodBadRight.hangs = onExternalThird',
      'connectedness.externallyPosited = sameAs',
      'connectedness.externallyPosited = onlyInItself',
      'connectedness.externallyPosited = onlyInternal',
      'goodBadRight != onlyInSubjectiveConsciousness',
      'goodBadRight = predicatesOfObject',
      'merelySubjective = implicitlyPresent',
      'implicitlyPresent.connectedness = notPosited',
      'implicitlyPresent.connectedness = onlyExternal',
      'copula = immediateAbstractBeing',
    ],
    predicates: [
      { name: 'subjectiveAssurance', args: ['credential'] },
      { name: 'externalThird', args: ['goodBadRight.hangs'] },
      { name: 'onlyInItself', args: ['connectedness.externallyPosited'] },
      { name: 'onlyInternal', args: ['connectedness.externallyPosited'] },
      { name: 'immediateAbstractBeing', args: ['copula'] },
    ],
    relations: [
      { predicate: 'hangs', from: 'goodBadRight', to: 'onExternalThird' },
      { predicate: 'is', from: 'connectedness.externallyPosited', to: 'onlyInItself' },
      { predicate: 'is', from: 'copula', to: 'immediateAbstractBeing' },
    ],
    candidateSummary: 'For this reason the judgment is so far only assertoric; its credential is only a subjective assurance. That something is good or bad, right, suitable or not, hangs on an external third. But to say that the connectedness is thus externally posited is the same as saying that it is still only in itself or internal. When we say that something is good or bad, etc., we certainly do not mean to say that it is good only in a subjective consciousness but may perhaps be bad in itself, or that "good and bad," "right," "suitable," etc. may not be predicates of the object itself. The merely subjective character of the assertion of this judgment consists, therefore, in the fact that the implicitly present connectedness of subject and predicate has not been posited yet, or, what amounts to the same thing, that it is only external; the copula still is an immediate abstract being.',
    provenance: {
      sourceChunk: 'conc-5-assertoric-subjective',
      sourceOp: 'conc-op-5-assertoric-subjective',
    },
};

export const concOp6AssertoricProblematic: LogicalOperation = {
  id: 'conc-op-6-assertoric-problematic',
    chunkId: 'conc-6-assertoric-problematic',
    label: 'Assertoric Passes to Problematic; Contingent Conformity',
    clauses: [
      'assurance.canBeConfronted = byOpposing',
      'example1 = "thisAction is good"',
      'example2 = "thisAction is bad"',
      'opposing.has = equalJustification',
      'subject = immediateSingular',
      'subject = abstraction',
      'subject.noDeterminateness = containingConnection',
      'contingent = whetherConformityToConcept',
      'essentially = problematic',
    ],
    predicates: [
      { name: 'byOpposing', args: ['assurance.canBeConfronted'] },
      { name: 'equalJustification', args: ['opposing.has'] },
      { name: 'immediateSingular', args: ['subject'] },
      { name: 'abstraction', args: ['subject'] },
      { name: 'problematic', args: ['essentially'] },
    ],
    relations: [
      { predicate: 'canBeConfronted', from: 'assurance', to: 'byOpposing' },
      { predicate: 'has', from: 'opposing', to: 'equalJustification' },
      { predicate: 'is', from: 'subject', to: 'immediateSingular' },
      { predicate: 'is', from: 'essentially', to: 'problematic' },
    ],
    candidateSummary: 'Thus the assurance of the assertoric judgment can with right be confronted by an opposing one. When the assurance is given that "this action is good," the opposite, "this action is bad," has equal justification. Or, considering the judgment in itself, since its subject is an immediate singular, in this abstraction it still does not have, posited in it, the determinateness that would contain its connection with the universal concept; it still is a contingent matter, therefore, whether there is or there is not conformity to the concept. Essentially, therefore, the judgment is problematic.',
    provenance: {
      sourceChunk: 'conc-6-assertoric-problematic',
      sourceOp: 'conc-op-6-assertoric-problematic',
    },
};

// ============================================================================
// B. THE PROBLEMATIC JUDGMENT
// ============================================================================

export const concOp7ProblematicDifferentiated: LogicalOperation = {
  id: 'conc-op-7-problematic-differentiated',
    chunkId: 'conc-7-problematic-differentiated',
    label: 'Problematic Judgment: Subject Differentiated into Ought and Constitution',
    clauses: [
      'problematicJudgment = assertoricJudgment',
      'problematicJudgment.taken = positively',
      'problematicJudgment.taken = negatively',
      'particularJudgment = problematic',
      'particularJudgment.has = positiveValue',
      'particularJudgment.has = negativeValue',
      'hypotheticalJudgment.being = problematic',
      'singularJudgment = merelySubjective',
      'categoricalJudgment = merelySubjective',
      'problematicJudgment.positing = moreImmanent',
      'predicate.content = connectionToConcept',
      'determinationOfImmediate = contingent',
      'predicate.oughtToBe = coupledWithSubject',
      'predicate.notOughtToBe = coupledWithSubject',
      'indeterminateness.falls = onCopula',
      'predicate = objectiveConcreteUniversality',
      'problematicElement.falls = onImmediacyOfSubject',
      'subject.determined = asContingency',
      'mustNotAbstract = fromSingularity',
      'subject.differentiated1 = intoUniversality',
      'subject.differentiated1 = intoObjectiveNature',
      'subject.differentiated1 = intoOught',
      'subject.differentiated2 = intoParticularizedConstitution',
      'subject.differentiated2 = intoImmediateExistence',
      'subject.contains = ground',
      'ground = forBeingWhatOught',
      'ground = forNotBeingWhatOught',
      'subject.equated = withPredicate',
      'negativity = originalPartition',
      'originalPartition = into(universal, particular)',
      'subject.already = unity',
      'partition = judgmentItself',
    ],
    predicates: [
      { name: 'problematicJudgment', args: ['assertoricJudgment'] },
      { name: 'moreImmanent', args: ['problematicJudgment.positing'] },
      { name: 'objectiveConcreteUniversality', args: ['predicate'] },
      { name: 'asContingency', args: ['subject.determined'] },
      { name: 'originalPartition', args: ['negativity', 'into'] },
    ],
    relations: [
      { predicate: 'is', from: 'problematicJudgment', to: 'assertoricJudgment' },
      { predicate: 'taken', from: 'problematicJudgment', to: 'positively' },
      { predicate: 'taken', from: 'problematicJudgment', to: 'negatively' },
      { predicate: 'falls', from: 'indeterminateness', to: 'onCopula' },
      { predicate: 'falls', from: 'problematicElement', to: 'onImmediacyOfSubject' },
      { predicate: 'differentiated', from: 'subject', to: 'intoUniversality' },
      { predicate: 'contains', from: 'subject', to: 'ground' },
      { predicate: 'equated', from: 'subject', to: 'withPredicate' },
    ],
    candidateSummary: 'The problematic judgment is the assertoric judgment in so far as the latter must be taken positively as well as negatively. According to this qualitative side, the particular judgment is likewise a problematic one, for it has positive just as much as negative value (equally problematic is also the being of the subject and predicate in the hypothetical judgment), and also posited through this side is that the singular judgment and the categorical are still something merely subjective. In the problematic judgment as such, however, this positing is more immanent than it is in these others, for in it the content of the predicate is the connection of the subject to the concept; here, therefore, the determination of the immediate as something contingent is itself present. Whether the predicate ought to be or not to be coupled with a certain subject appears at first only as problematic, and to this extent the indeterminateness falls on the side of the copula. The predicate has no determination to gain from this coupling, since it is already the objective, concrete universality. The problematic element falls, therefore, on the immediacy of the subject, which is thereby determined as a contingency. But further, we must not for that reason abstract from the singularity of the subject; purified of such a singularity, the subject would be only a universal, whereas the predicate entails precisely this, that the concept of the subject ought to be posited with reference to its singularity. We may not say, "the house or a house is good," but, "so indeed it is in the way it is made." The problematic element in the subject itself constitutes its moment of contingency, the subjectivity of the fact it expresses as contrasted with its objective nature or its concept, its mere mode and manner or its constitution. Consequently the subject is itself differentiated into its universality or objective nature, that is, its ought, and the particularized constitution of immediate existence. It thereby contains the ground for being or not being what it ought to be. In this way, it is equated with the predicate. Accordingly, the negativity of the problematic character of the judgment, inasmuch as it implicates the immediacy of the subject, only amounts to this original partition of the latter into its moments of universal and particular of which it is already the unity, a partition which is the judgment itself.',
    provenance: {
      sourceChunk: 'conc-7-problematic-differentiated',
      sourceOp: 'conc-op-7-problematic-differentiated',
    },
};

export const concOp8TwoMeaningsSubjectivity: LogicalOperation = {
  id: 'conc-op-8-two-meanings-subjectivity',
    chunkId: 'conc-8-two-meanings-subjectivity',
    label: 'Two Meanings of Subjectivity; Duplicity',
    clauses: [
      'bothSides = subjectivity',
      'concept = universalEssence',
      'concept = withdrawnIntoItself',
      'concept = negativeSelfUnity',
      'concept = factSubjectivity',
      'fact = contingent',
      'fact = externalConstitution',
      'externalConstitution = mereSubjectivity',
      'externalConstitution.contrasted = toObjectivity',
      'fact.consists = inConcept',
      'concept.negates = itsUniversality',
      'concept.projects = intoExternality',
      'externality = ofSingularity',
      'subject = duplicity',
      'truth = twoMeaningsInOne',
      'meaning = problematic',
      'subjectivity.hasNoTruth = inOneAlone',
      'duplicity = manifestation',
      'manifestation = ofOneSidedness',
    ],
    predicates: [
      { name: 'subjectivity', args: ['bothSides'] },
      { name: 'universalEssence', args: ['concept'] },
      { name: 'negativeSelfUnity', args: ['concept'] },
      { name: 'factSubjectivity', args: ['concept'] },
      { name: 'mereSubjectivity', args: ['externalConstitution'] },
      { name: 'duplicity', args: ['subject'] },
      { name: 'problematic', args: ['meaning'] },
      { name: 'manifestation', args: ['duplicity', 'ofOneSidedness'] },
    ],
    relations: [
      { predicate: 'is', from: 'concept', to: 'universalEssence' },
      { predicate: 'is', from: 'concept', to: 'negativeSelfUnity' },
      { predicate: 'is', from: 'externalConstitution', to: 'mereSubjectivity' },
      { predicate: 'negates', from: 'concept', to: 'itsUniversality' },
      { predicate: 'projects', from: 'concept', to: 'intoExternality' },
      { predicate: 'is', from: 'subject', to: 'duplicity' },
    ],
    candidateSummary: 'One more comment that can be made is that both sides of the subject, its concept and the way it is constituted, could each be called its subjectivity. The concept is the universal essence of a fact, withdrawn into itself, the fact\'s negative self-unity; this unity constitutes the fact\'s subjectivity. But a fact is also essentially contingent and has an external constitution; this last may also be called its mere subjectivity, as contrasted with the objectivity of the concept. The fact consists just in this, that its concept, as self-negating unity, negates its universality and projects itself into the externality of singularity. As this duplicity, the subject of the judgment is here posited; the truth of those two opposite meanings of subjectivity is that they are in one. The meaning of subjective has itself become problematic by having lost the immediate determinateness that it had in the immediate judgment and its determinate opposition to the predicate. These opposite meanings of subjectivity that surface even in the ratiocination of ordinary reflection should by themselves at least call attention to the fact that subjectivity has no truth in one of them alone. The duplicity of meaning is the manifestation of the one-sidedness of each when taken by itself.',
    provenance: {
      sourceChunk: 'conc-8-two-meanings-subjectivity',
      sourceOp: 'conc-op-8-two-meanings-subjectivity',
    },
};

export const concOp9ProblematicApodictic: LogicalOperation = {
  id: 'conc-op-9-problematic-apodictic',
    chunkId: 'conc-9-problematic-apodictic',
    label: 'Problematic Passes to Apodictic',
    clauses: [
      'when(problematicCharacter.posited = asCharacterOfFact)',
      'when(problematicCharacter.posited = withConstitution)',
      'judgment.noLonger = problematic',
      'judgment = apodictic',
    ],
    predicates: [
      { name: 'asCharacterOfFact', args: ['problematicCharacter.posited'] },
      { name: 'apodictic', args: ['judgment'] },
    ],
    relations: [
      { predicate: 'posited', from: 'problematicCharacter', to: 'asCharacterOfFact' },
      { predicate: 'is', from: 'judgment', to: 'apodictic' },
    ],
    candidateSummary: 'When this problematic character of the judgment is thus posited as the character of the fact, the fact with its constitution, the judgment itself is no longer problematic but apodictic.',
    provenance: {
      sourceChunk: 'conc-9-problematic-apodictic',
      sourceOp: 'conc-op-9-problematic-apodictic',
    },
};

// ============================================================================
// C. THE APODICTIC JUDGMENT
// ============================================================================

export const concOp10ApodicticObjective: LogicalOperation = {
  id: 'conc-op-10-apodictic-objective',
    chunkId: 'conc-10-apodictic-objective',
    label: 'Apodictic Judgment: Truly Objective; Correspondence',
    clauses: [
      'example = "house, asSoAndSoConstituted, is good"',
      'example = "action, asSoAndSoConstituted, is right"',
      'subject.includes1 = universal',
      'subject.includes1 = ought',
      'subject.includes2 = constitution',
      'constitution.contains = ground',
      'ground = whyPredicatePertains',
      'ground = whetherSubjectCorresponds',
      'judgment = trulyObjective',
      'judgment = truthOfJudgment',
      'subject.predicate = correspond',
      'subject.predicate = sameConcept',
      'content = concreteUniversality',
      'content.contains1 = objectiveUniversal',
      'content.contains1 = genus',
      'content.contains2 = singularizedUniversal',
      'universal.continues = throughOpposite',
      'universal = onlyInUnity',
      'universal = "good"',
      'universal = "fitting"',
      'universal = "right"',
      'universal.hasGround = ought',
      'universal.contains = correspondence',
      'universal.contains = ofExistence',
      'universal != oughtAlone',
      'universal != genusAlone',
      'correspondence = universality',
      'correspondence = constitutesPredicate',
    ],
    predicates: [
      { name: 'trulyObjective', args: ['judgment'] },
      { name: 'truthOfJudgment', args: ['judgment'] },
      { name: 'correspond', args: ['subject.predicate'] },
      { name: 'concreteUniversality', args: ['content'] },
      { name: 'correspondence', args: ['universality'] },
    ],
    relations: [
      { predicate: 'includes', from: 'subject', to: 'universal' },
      { predicate: 'includes', from: 'subject', to: 'constitution' },
      { predicate: 'contains', from: 'constitution', to: 'ground' },
      { predicate: 'is', from: 'judgment', to: 'trulyObjective' },
      { predicate: 'correspond', from: 'subject', to: 'predicate' },
      { predicate: 'continues', from: 'universal', to: 'throughOpposite' },
    ],
    candidateSummary: 'The subject of the apodictic judgment ("the house, as so and so constituted, is good," "the action, as so and so constituted, is right") includes, first, the universal, or what it ought to be; second, its constitution; the latter contains the ground why a predicate of the judgment of the concept does or does not pertain to it, that is, whether the subject corresponds to its concept or not. This judgment is now truly objective; or it is the truth of the judgment in general. Subject and predicate correspond to each other, and have the same concept, and this content is itself posited concrete universality; that is to say, it contains the two moments, the objective universal or the genus and the singularized universal. Here we have, therefore, the universal that is itself and continues through its opposite, and is a universal only in unity with the latter. Such a universal, like "good," "fitting," "right," etc., has an ought for its ground, and contains at the same time the correspondence of existence; it is not the ought or the genus by itself, but this correspondence which is the universality that constitutes the predicate of the apodictic judgment.',
    provenance: {
      sourceChunk: 'conc-10-apodictic-objective',
      sourceOp: 'conc-op-10-apodictic-objective',
    },
};

export const concOp11AbsoluteJudgment: LogicalOperation = {
  id: 'conc-op-11-absolute-judgment',
    chunkId: 'conc-11-absolute-judgment',
    label: 'Apodictic: Absolute Judgment on Actuality; Soul',
    clauses: [
      'subject.contains = twoMoments',
      'twoMoments = inImmediateUnity',
      'twoMoments = asFact',
      'truth = internallyFractured',
      'internallyFractured = into(ought, being)',
      'absoluteJudgment = onAllActuality',
      'originalPartition = omnipotenceOfConcept',
      'originalPartition = turningBackIntoUnity',
      'absoluteConnection = of(ought, being)',
      'absoluteConnection.makes = actualIntoFact',
      'innerConnection = concreteIdentity',
      'innerConnection = soul',
    ],
    predicates: [
      { name: 'inImmediateUnity', args: ['twoMoments'] },
      { name: 'internallyFractured', args: ['truth', 'into'] },
      { name: 'absoluteJudgment', args: ['onAllActuality'] },
      { name: 'omnipotenceOfConcept', args: ['originalPartition'] },
      { name: 'turningBackIntoUnity', args: ['originalPartition'] },
      { name: 'concreteIdentity', args: ['innerConnection'] },
      { name: 'soul', args: ['innerConnection'] },
    ],
    relations: [
      { predicate: 'contains', from: 'subject', to: 'twoMoments' },
      { predicate: 'is', from: 'truth', to: 'internallyFractured' },
      { predicate: 'is', from: 'originalPartition', to: 'omnipotenceOfConcept' },
      { predicate: 'makes', from: 'absoluteConnection', to: 'actualIntoFact' },
      { predicate: 'is', from: 'innerConnection', to: 'concreteIdentity' },
    ],
    candidateSummary: 'The subject likewise contains these two moments in immediate unity as fact. The truth of the latter, however, is that it is internally fractured into its ought and its being; this is the absolute judgment on all actuality. That this original partition, which is the omnipotence of the concept, is equally a turning back into the concept\'s unity and the absolute connection of "ought" and "being" to each other, is what makes the actual into a fact; the fact\'s inner connection, this concrete identity, constitutes its soul.',
    provenance: {
      sourceChunk: 'conc-11-absolute-judgment',
      sourceOp: 'conc-op-11-absolute-judgment',
    },
};

export const concOp12GroundCopula: LogicalOperation = {
  id: 'conc-op-12-ground-copula',
    chunkId: 'conc-12-ground-copula',
    label: 'Ground in Constitution; Accomplished Copula',
    clauses: [
      'transition.lies = inParticularDeterminateness',
      'genus = universalExistingInAndForItself',
      'genus.appears = asUnconnected',
      'determinateness.reflected = intoItself',
      'determinateness.reflected = intoOther',
      'judgment.hasGround = inConstitution',
      'judgment = apodictic',
      'accomplishedCopula = abstractIs',
      'accomplishedCopula.developed = intoGround',
      'accomplishedCopula.attaches = toSubject',
      'accomplishedCopula.attaches = asImmediateDeterminateness',
      'accomplishedCopula = connectionToPredicate',
      'predicate = correspondenceItself',
      'predicate = connectionToUniversality',
    ],
    predicates: [
      { name: 'universalExistingInAndForItself', args: ['genus'] },
      { name: 'asUnconnected', args: ['genus.appears'] },
      { name: 'inConstitution', args: ['judgment.hasGround'] },
      { name: 'apodictic', args: ['judgment'] },
      { name: 'accomplishedCopula', args: ['abstractIs'] },
      { name: 'correspondenceItself', args: ['predicate'] },
    ],
    relations: [
      { predicate: 'lies', from: 'transition', to: 'inParticularDeterminateness' },
      { predicate: 'appears', from: 'genus', to: 'asUnconnected' },
      { predicate: 'reflected', from: 'determinateness', to: 'intoItself' },
      { predicate: 'reflected', from: 'determinateness', to: 'intoOther' },
      { predicate: 'hasGround', from: 'judgment', to: 'inConstitution' },
      { predicate: 'developed', from: 'accomplishedCopula', to: 'intoGround' },
    ],
    candidateSummary: 'The transition from the immediate simplicity of the fact to the correspondence which is the determinate connection of its ought and its being, the copula, now shows itself upon closer examination to lie in the particular determinateness of the fact. The genus is the universal existing in and for itself which, to that extent, appears as unconnected; the determinateness, however, is that which in that universality is reflected into itself but at the same time into an other. The judgment, therefore, has its ground in the constitution of the subject and is thereby apodictic. Consequently, we now have the determinate and accomplished copula which hitherto consisted in the abstract "is" but has now further developed into ground in general. It first attaches to the subject as immediate determinateness, but it is equally the connection to the predicate, a predicate that has no other content than this correspondence itself, or the connection of the subject to the universality.',
    provenance: {
      sourceChunk: 'conc-12-ground-copula',
      sourceOp: 'conc-op-12-ground-copula',
    },
};

export const concOp13FormPassesAway: LogicalOperation = {
  id: 'conc-op-13-form-passes-away',
    chunkId: 'conc-13-form-passes-away',
    label: 'Form of Judgment Passes Away; Identity Recovered',
    clauses: [
      'form.passedAway1 = subjectPredicateSameContent',
      'form.passedAway2 = subjectPointsBeyond',
      'form.passedAway2 = subjectConnects',
      'form.passedAway3 = connectingPassedOver',
      'connectingPassedOver = intoPredicate',
      'connectingPassedOver = constitutesContent',
      'connectingPassedOver = connectingAsPosited',
      'connectingPassedOver = judgmentItself',
      'concreteIdentity = ofConcept',
      'concreteIdentity = resultOfDisjunctiveJudgment',
      'concreteIdentity = innerFoundation',
      'concreteIdentity = ofJudgmentOfConcept',
      'concreteIdentity.posited = atFirstOnlyInPredicate',
      'concreteIdentity.recovered = inWhole',
    ],
    predicates: [
      { name: 'passedAway', args: ['form'] },
      { name: 'subjectPredicateSameContent', args: ['form.passedAway1'] },
      { name: 'connectingPassedOver', args: ['intoPredicate'] },
      { name: 'concreteIdentity', args: ['ofConcept'] },
      { name: 'innerFoundation', args: ['concreteIdentity'] },
    ],
    relations: [
      { predicate: 'passedAway', from: 'form', to: 'subjectPredicateSameContent' },
      { predicate: 'pointsBeyond', from: 'subject', to: 'itself' },
      { predicate: 'connects', from: 'subject', to: 'toPredicate' },
      { predicate: 'passedOver', from: 'connecting', to: 'intoPredicate' },
      { predicate: 'is', from: 'concreteIdentity', to: 'resultOfDisjunctiveJudgment' },
      { predicate: 'recovered', from: 'concreteIdentity', to: 'inWhole' },
    ],
    candidateSummary: 'Thus the form of judgment has passed away, first, because subject and predicate are in themselves the same content; but, second, because through its determinateness the subject points beyond itself and connects itself to the predicate; but again, third, this connecting has equally passed over into the predicate, only constitutes the content of it, and so it is the connecting as posited or the judgment itself. The concrete identity of the concept that was the result of the disjunctive judgment and constitutes the inner foundation of the judgment of the concept (the identity that was posited at first only in the predicate) is thus recovered in the whole.',
    provenance: {
      sourceChunk: 'conc-13-form-passes-away',
      sourceOp: 'conc-op-13-form-passes-away',
    },
};

export const concOp14TransitionSyllogism: LogicalOperation = {
  id: 'conc-op-14-transition-syllogism',
    chunkId: 'conc-14-transition-syllogism',
    label: 'Transition to Syllogism; Copula Replete of Content',
    clauses: [
      'subject = wholeConcept',
      'predicate = wholeConcept',
      'unityOfConcept = determinateness',
      'unityOfConcept = constitutingCopula',
      'unityOfConcept = connectingSubjectPredicate',
      'unityOfConcept = distinct',
      'unityOfConcept.atFirst = immediateConstitution',
      'unityOfConcept.essence = toConnect',
      'unityOfConcept = notOnlyImmediateConstitution',
      'unityOfConcept = universal',
      'unityOfConcept.runsThrough = subjectAndPredicate',
      'subject.predicate = sameContent',
      'formOfConnection.posited = throughDeterminateness',
      'determinateness = asUniversal',
      'determinateness = asParticularity',
      'contains = formDeterminationsOfExtremes',
      'contains = determinateConnection',
      'accomplishedCopula = repleteOfContent',
      'unityOfConcept = reEmerging',
      'unityOfConcept.reEmerging = fromJudgment',
      'unityOfConcept.wasLost = inExtremes',
      'byVirtueOfRepletion = judgmentBecomeSyllogism',
    ],
    predicates: [
      { name: 'wholeConcept', args: ['subject'] },
      { name: 'wholeConcept', args: ['predicate'] },
      { name: 'constitutingCopula', args: ['unityOfConcept'] },
      { name: 'toConnect', args: ['unityOfConcept.essence'] },
      { name: 'repleteOfContent', args: ['accomplishedCopula'] },
      { name: 'reEmerging', args: ['unityOfConcept'] },
      { name: 'judgmentBecomeSyllogism', args: ['byVirtueOfRepletion'] },
    ],
    relations: [
      { predicate: 'is', from: 'subject', to: 'wholeConcept' },
      { predicate: 'is', from: 'predicate', to: 'wholeConcept' },
      { predicate: 'is', from: 'unityOfConcept', to: 'determinateness' },
      { predicate: 'runsThrough', from: 'unityOfConcept', to: 'subjectAndPredicate' },
      { predicate: 'contains', from: 'accomplishedCopula', to: 'formDeterminationsOfExtremes' },
      { predicate: 'reEmerging', from: 'unityOfConcept', to: 'fromJudgment' },
    ],
    candidateSummary: 'On closer examination, the positive factor in this result which is responsible for the transition of the judgment into another form is that, as we have just seen, the subject and predicate are in the apodictic judgment each the whole concept. The unity of the concept, as the determinateness constituting the copula that connects them, is at the same time distinct from them. At first, it stands only on the other side of the subject as the latter\'s immediate constitution. But since its essence is to connect, it is not only that immediate constitution but the universal that runs through the subject and predicate. While subject and predicate have the same content, it is the form of their connection that is instead posited through the determinateness of the copula, the determinateness as a universal or the particularity. Thus it contains in itself both the form determinations of the extremes and is the determinate connection of the subject and predicate: the accomplished copula of the judgment, the copula replete of content, the unity of the concept that re-emerges from the judgment wherein it was lost in the extremes. By virtue of this repletion of the copula, the judgment has become syllogism.',
    provenance: {
      sourceChunk: 'conc-14-transition-syllogism',
      sourceOp: 'conc-op-14-transition-syllogism',
    },
};

export const judgmentOfConceptOperations: LogicalOperation[] = [
  concOp1IntroductionOught,
  concOp2Modality,
  concOp3Diremption,
  concOp4AssertoricImmediate,
  concOp5AssertoricSubjective,
  concOp6AssertoricProblematic,
  concOp7ProblematicDifferentiated,
  concOp8TwoMeaningsSubjectivity,
  concOp9ProblematicApodictic,
  concOp10ApodicticObjective,
  concOp11AbsoluteJudgment,
  concOp12GroundCopula,
  concOp13FormPassesAway,
  concOp14TransitionSyllogism,
];

