/**
 * Logical Operations: The Judgment of Existence
 *
 * The determinate dialectic - the most manifest moment of the dialectic in itself.
 *
 * Dialectical Movement:
 * - Positive Judgment: "the singular is universal"
 * - Negative Judgment: "the singular is a particular"
 * - Infinite Judgment: "the singular is singular"
 *
 * This is the foundation of the judgment genus, showing how the dialectic
 * operates through the immediate judgment of existence.
 */

import type { LogicalOperation } from '../../../types';

// ============================================================================
// INTRODUCTION: Judgment as Truth
// ============================================================================

export const existOp1JudgmentTruth: LogicalOperation = {
  id: 'exist-op-1-judgment-truth',
  chunkId: 'exist-1-introduction-truth',
  label: 'Judgment as Truth; Agreement of Concept and Reality',
  clauses: [
    'judgment = truth',
      'truth = agreement(concept, reality)',
      'subjectiveJudgment.object = double(singularActuality, essentialIdentity)',
      'subjectiveJudgment.object = double(singularActuality, concept)',
      'singular.raised = universality',
      'universal.madeSingular = actuality',
      'judgmentOfExistence = immediate',
      'judgmentOfExistence = qualitativeJudgment',
      'immediacy = noReflection',
    'immediacy = noMovement',
  ],
  predicates: [
    { name: 'truth', args: ['judgment'] },
      { name: 'agreement', args: ['concept', 'reality'] },
      { name: 'double', args: ['singularActuality', 'essentialIdentity'] },
    { name: 'immediate', args: ['judgment'] },
  ],
  relations: [
    { predicate: 'is', from: 'judgment', to: 'truth' },
      { predicate: 'contains', from: 'subjectiveJudgment', to: 'object' },
      { predicate: 'transitions', from: 'singular', to: 'universality' },
    { predicate: 'transitions', from: 'universal', to: 'actuality' },
  ],
  candidateSummary: 'Judgment is truth as the agreement of concept and reality. In subjective judgment, the same object appears double: once as singular actuality, again as essential identity or concept. The singular is raised into universality, or the universal is made singular into actuality. But at first the judgment is immediate, with no reflection or movement of determinations, rendering it a judgment of immediate existence or qualitative judgment.',
  provenance: {
    sourceChunk: 'exist-1-introduction-truth',
    sourceOp: 'exist-op-1-judgment-truth',
  },
};

export const existOp2JudgmentInherence: LogicalOperation = {
  id: 'exist-op-2-judgment-inherence',
  chunkId: 'exist-2-judgment-inherence',
  label: 'Judgment of Inherence; Subject Immediate, Predicate Has Foundation',
    clauses: [
      'judgmentOfExistence = judgmentOfInherence',
      'subject = immediate',
      'subject = firstTerm',
      'subject = essentialTerm',
      'predicate.foundation = subject',
      'predicate.subsistence = false',
    ],
    predicates: [
      { name: 'inherence', args: ['judgment'] },
      { name: 'immediate', args: ['subject'] },
      { name: 'hasFoundation', args: ['predicate', 'subject'] },
    ],
    relations: [
      { predicate: 'is', from: 'judgmentOfExistence', to: 'judgmentOfInherence' },
      { predicate: 'foundation', from: 'predicate', to: 'subject' },
    ],
    candidateSummary: 'The judgment of existence is also the judgment of inherence. The subject is the immediate, first and essential term in the judgment. The predicate does not subsist on its own but has its foundation in the subject.',
    provenance: {
      sourceChunk: 'exist-2-judgment-inherence',
      sourceOp: 'exist-op-2-judgment-inherence',
    },
};

// ============================================================================
// A. THE POSITIVE JUDGMENT
// ============================================================================

export const existOp3SubjectPredicateDeterminations: LogicalOperation = {
  id: 'exist-op-3-subject-predicate-determinations',
    chunkId: 'exist-3-subject-predicate-determinations',
    label: 'Subject and Predicate Determinations; Abstract Singularity and Universality',
    clauses: [
      'subject = abstractSingular',
      'predicate = abstractUniversal',
      'subject.predicate = names',
      'judgment.sides = {subject, predicate}',
      'judgment = positedDeterminateConcept',
      'subject.predicate.determination = momentsOfConcept',
      'immediacy.determination = simple',
      'immediacy.determination = notEnrichedByMediation',
      'opposition = abstract(singularity, universality)',
      'predicate.conditioned = mediation',
      'predicate.conditioned = sublation(singularity, particularity)',
      'mediation = presupposition',
      'immediacyOfUniversal = containsMediation',
      'immediacyOfUniversal = arisenThroughSublation',
      'qualitativeBeing.concept = universal',
      'universality.conceptDetermination = negativity',
      'subject = conceptPassedOverIntoExternality',
      'copula = immediateAbstractBeing',
      'connection.contains = noMediation',
      'connection.contains = noNegation',
      'judgment = positive',
    ],
    predicates: [
      { name: 'abstractSingular', args: ['subject'] },
      { name: 'abstractUniversal', args: ['predicate'] },
      { name: 'momentsOfConcept', args: ['determination'] },
      { name: 'containsMediation', args: ['immediacy'] },
      { name: 'arisenThroughSublation', args: ['immediacy'] },
    ],
    relations: [
      { predicate: 'opposition', from: 'abstractSingularity', to: 'abstractUniversality' },
      { predicate: 'conditioned', from: 'predicate', to: 'mediation' },
      { predicate: 'passedOver', from: 'concept', to: 'externality' },
      { predicate: 'contains', from: 'universality', to: 'negativity' },
    ],
    candidateSummary: 'Subject and predicate are names at first that receive their actual determination only as the judgment runs its course. As sides of the judgment (the posited determinate concept), they have the determination of moments of the concept. But on account of immediacy, this determination is simple, not enriched by mediation, caught up in the abstract opposition of abstract singularity and abstract universality. The predicate is the abstract universal, conditioned by mediation and the sublation of singularity and particularity, but such mediation is here only a presupposition. The subject is an abstract singular, the side according to which the concept has passed over into externality. The copula is immediate, abstract being. Because the connection does not contain any mediation or negation, this judgment is called "positive".',
    provenance: {
      sourceChunk: 'exist-3-subject-predicate-determinations',
      sourceOp: 'exist-op-3-subject-predicate-determinations',
    },
};

export const existOp4FirstPureExpression: LogicalOperation = {
  id: 'exist-op-4-first-pure-expression',
    chunkId: 'exist-4-first-pure-expression',
    label: 'First Pure Expression: "The Singular is Universal"',
    clauses: [
      'positiveJudgment.expression = "singular is universal"',
      'positiveJudgment.expression != "A is B"',
      '"A is B" = formless',
      '"A is B" = meaningless',
      'judgment.extremes = determinationsOfConcept',
      'everyJudgment.asserts = "singular is universal"',
      'everyJudgment = abstractJudgment',
    ],
    predicates: [
      { name: 'pureExpression', args: ['positiveJudgment'] },
      { name: 'formless', args: ['expression'] },
      { name: 'meaningless', args: ['expression'] },
      { name: 'asserts', args: ['judgment', 'proposition'] },
    ],
    relations: [
      { predicate: 'hasExpression', from: 'positiveJudgment', to: '"singular is universal"' },
      { predicate: 'hasExtremes', from: 'judgment', to: 'determinationsOfConcept' },
    ],
    candidateSummary: 'The first pure expression of the positive judgment is: "the singular is universal". This expression must not be put in the form of "A is B", for A and B are totally formless and hence meaningless names, whereas judgment has determinations of the concept for its extremes. What is asserted in every judgment, even one more richly determined in form, is the proposition "the singular is universal", for every judgment is in principle also an abstract judgment.',
    provenance: {
      sourceChunk: 'exist-4-first-pure-expression',
      sourceOp: 'exist-op-4-first-pure-expression',
    },
};

export const existOp5ObjectiveMeaningResolution: LogicalOperation = {
  id: 'exist-op-5-objective-meaning-resolution',
    chunkId: 'exist-5-objective-meaning-resolution',
    label: 'Objective Meaning: Perishableness and Resolution; Universal Resolves into Singular',
    clauses: [
      'objectiveMeaning = perishableness(singularThings)',
      'objectiveMeaning = positiveSubsistence(singularThings, concept)',
      'concept = imperishable',
      'concept.emergence = subjectedToAlteration',
      'concept.emergence = fallingBackIntoUniversalNature',
      'universal.gives = determinateExistence',
      'essence.goesOut = reflectiveShine',
      'ground.goesOut = concreteExistence',
      'substance.goesOut = manifestation',
      'universal.resolves = singular',
      'judgment = resolution(universal)',
      'judgment = development(negativity)',
      'subject.referred = universal',
      'subject.posited = concrete',
      'subject = something(manyQualities)',
      'subject = thing(manifoldProperties)',
      'subject = actual(manifoldPossibilities)',
      'subject = substance(accidents)',
      'subject.inherently = universal',
      'predicate = abstractDeterminateness',
      'predicate.contains = oneMoment',
      'predicate.excludes = otherMoments',
      'predicate = abstractSingular',
      'proposition = "universal is singular"',
    ],
    predicates: [
      { name: 'perishableness', args: ['singularThings'] },
      { name: 'positiveSubsistence', args: ['singularThings', 'concept'] },
      { name: 'imperishable', args: ['concept'] },
      { name: 'resolves', args: ['universal', 'singular'] },
      { name: 'development', args: ['negativity'] },
      { name: 'inherently', args: ['subject', 'universal'] },
    ],
    relations: [
      { predicate: 'resolves', from: 'universal', to: 'singular' },
      { predicate: 'referred', from: 'subject', to: 'universal' },
      { predicate: 'posited', from: 'subject', to: 'concrete' },
      { predicate: 'contains', from: 'predicate', to: 'oneMoment' },
      { predicate: 'excludes', from: 'predicate', to: 'otherMoments' },
    ],
    candidateSummary: 'The objective meaning of the proposition "the singular is universal" conveys both the perishableness of singular things and their positive subsistence in the concept in general. The concept itself is imperishable, but that which emerges from it in its division is subjected to alteration and to falling back into its universal nature. The universal gives itself a determinate existence. Just as essence goes out into reflective shine, ground into concrete existence, and substance into manifestation, so does the universal resolve itself into the singular. Judgment is this resolution of the universal, the development of the negativity which, implicitly, it already is. The subject, referred to its other (the universal), is posited as concrete (something of many qualities, thing of manifold properties). The subject is inherently the universal. The predicate, being abstract universality, is in contrast to the subject the determinateness; it contains only one moment of the subject\'s totality to the exclusion of the others. On account of this negativity, the predicate is an abstract singular. From this side, the proposition says: "the universal is singular".',
    provenance: {
      sourceChunk: 'exist-5-objective-meaning-resolution',
      sourceOp: 'exist-op-5-objective-meaning-resolution',
    },
};

export const existOp6TwofoldResultFormContent: LogicalOperation = {
  id: 'exist-op-6-twofold-result-form-content',
    chunkId: 'exist-6-twofold-result-form-content',
    label: 'Twofold Result: Form and Content; Reciprocal Determination',
    clauses: [
      'twofoldResult.1 = subject.determinedAs(universal)',
      'twofoldResult.2 = predicate.determinedAs(singular)',
      'subject.predicate.retain = opposition(conceptDeterminations)',
      'when(subject = universal, predicate = singular)',
      'when(subject = singular, predicate = universal)',
      'mereIdentity = "singular is singular"',
      'mereIdentity = "universal is universal"',
      'mereIdentity.sides = fallenApart',
      'mereIdentity.judgment = sublated',
      'proposition1 = "universal is singular"',
      'proposition1 = content',
      'proposition1 = isolatedDetermination(predicate)',
      'proposition1 = totality(subject)',
      'proposition2 = "singular is universal"',
      'proposition2 = form',
      'proposition2 = immediateDeterminateness',
      'positiveJudgment.extremes = simple',
      'positiveJudgment.formContent = united',
      'positiveJudgment != twoPropositions',
      'twofoldConnection = onePositiveJudgment',
    ],
    predicates: [
      { name: 'twofoldResult', args: ['judgment'] },
      { name: 'determinedAs', args: ['term', 'determination'] },
      { name: 'retain', args: ['opposition'] },
      { name: 'fallenApart', args: ['sides'] },
      { name: 'united', args: ['form', 'content'] },
    ],
    relations: [
      { predicate: 'determinedAs', from: 'subject', to: 'universal' },
      { predicate: 'determinedAs', from: 'predicate', to: 'singular' },
      { predicate: 'opposition', from: 'subject', to: 'predicate' },
      { predicate: 'expresses', from: 'proposition1', to: 'content' },
      { predicate: 'expresses', from: 'proposition2', to: 'form' },
    ],
    candidateSummary: 'By juxtaposing the reciprocal determination of subject and predicate in the judgment, we obtain this twofold result: (1) Immediately, the subject is indeed an existent or the singular, while the predicate is the universal. But because the judgment connects the two, and the subject is determined as universal by the predicate, the subject is then the universal. (2) The predicate is determined in the subject, for it is not a determination in general but the determination rather of the subject. The predicate is therefore a singular. The subject and predicate should retain the opposition of concept determinations. When the subject is determined as universal, the predicate should not also be taken in its determination of universality, for then we would have no judgment; it must rather be taken only in its determination of singularity. If we reflect on the mere identity, then we have these two identical propositions, "the singular is singular" and "the universal is universal", in which the sides of the judgment would have completely fallen apart. The first proposition ("the universal is singular") expresses the judgment according to its content, as an isolated determination in the predicate and as the totality of determinations in the subject. The other ("the singular is universal") expresses it according to form as immediately given through the judgment itself. In the immediate positive judgment, the extremes are still simple: form and content are therefore still united.',
    provenance: {
      sourceChunk: 'exist-6-twofold-result-form-content',
      sourceOp: 'exist-op-6-twofold-result-form-content',
    },
};

export const existOp7CannotBeUnited: LogicalOperation = {
  id: 'exist-op-7-cannot-be-united',
    chunkId: 'exist-7-cannot-be-united',
    label: 'Two Propositions Cannot Be United; External Reflection',
    clauses: [
      'if(united(subject, predicate), both = particular)',
      'combination.arrivedAt = externalReflection',
      'result = "particular is particular"',
      'result = emptyIdenticalProposition',
      'result != judgment',
      'singularity.universality.cannotUnite = particularity',
      'positiveJudgment.singularityUniversality = immediate',
      'judgment.distinguished = formAndContent',
      'subject.predicate.distinguished = immediacyAndMediated',
      'judgment = selfSubsistence(connectedTerms)',
      'judgment = reciprocalDetermination(connectedTerms)',
    ],
    predicates: [
      { name: 'united', args: ['subject', 'predicate'] },
      { name: 'externalReflection', args: ['combination'] },
      { name: 'emptyIdenticalProposition', args: ['result'] },
      { name: 'cannotUnite', args: ['singularity', 'universality', 'particularity'] },
      { name: 'selfSubsistence', args: ['connectedTerms'] },
      { name: 'reciprocalDetermination', args: ['connectedTerms'] },
    ],
    relations: [
      { predicate: 'arrivedAt', from: 'combination', to: 'externalReflection' },
      { predicate: 'distinguished', from: 'judgment', to: 'formAndContent' },
      { predicate: 'distinguished', from: 'subject', to: 'immediacy' },
      { predicate: 'distinguished', from: 'predicate', to: 'mediated' },
    ],
    candidateSummary: 'If now the two propositions were to be united because they are contained in the one positive judgment, so that both, the subject as well as the predicate, were determined as the unity of singularity and universality, then both the subject and predicate would be the particular, and this must be recognized as implicitly their inner determination. However, this combination would be arrived at only through an external reflection; moreover, the proposition that results from it, "the particular is the particular", would no longer be a judgment but an empty identical proposition. Singularity and universality cannot yet be united into particularity, because in the positive judgment they are still posited as immediate. The judgment must still be distinguished according to its form and its content, because the subject and predicate are themselves still distinguished as immediacy and mediated, or because the judgment, according to its connection, is both the self-subsistence of the connected terms and their reciprocal determination or mediation.',
    provenance: {
      sourceChunk: 'exist-7-cannot-be-united',
      sourceOp: 'exist-op-7-cannot-be-united',
    },
};

export const existOp8PositiveNotTrue: LogicalOperation = {
  id: 'exist-op-8-positive-not-true',
    chunkId: 'exist-8-positive-not-true',
    label: 'Positive Judgment Not True; Form and Content Fail',
    clauses: [
      'form.proposition = "singular is universal"',
      'immediateSingular != universal',
      'predicate.extension = wider',
      'predicate.corresponds = false',
      'subject = beingExistingImmediately',
      'subject = opposite(abstraction)',
      'subject = opposite(universality)',
      'content.proposition = "universal is singular"',
      'subject = universeOfQualities',
      'subject = infinitelyDeterminedConcreteUniverse',
      'subject.totality = badInfinitePlurality',
      'subject != oneSingleProperty',
      'bothPropositions.mustBeUnited = true',
      'positiveJudgment.mustBePosited = negative',
    ],
    predicates: [
      { name: 'widerExtension', args: ['predicate'] },
      { name: 'doesNotCorrespond', args: ['predicate', 'subject'] },
      { name: 'universeOfQualities', args: ['subject'] },
      { name: 'badInfinitePlurality', args: ['totality'] },
      { name: 'mustBePosited', args: ['positiveJudgment', 'negative'] },
    ],
    relations: [
      { predicate: 'corresponds', from: 'predicate', to: 'subject' },
      { predicate: 'opposite', from: 'subject', to: 'abstraction' },
      { predicate: 'opposite', from: 'subject', to: 'universality' },
      { predicate: 'mustBeUnited', from: 'bothPropositions', to: 'true' },
    ],
    candidateSummary: 'In first place, then, the meaning of the judgment when considered according to its form is that the singular is universal. But in fact such an immediate singular is definitely not universal; its predicate is of wider extension, does not correspond to it. The subject is a being existing immediately for itself, and hence the opposite of that abstraction, of that universality posited through mediation that was supposed to be predicated of it. In second place, if the judgment is considered according to its content, or as the proposition "the universal is singular", then the subject is a universe of qualities, an infinitely determined concrete universe, and since its determinacies are as yet qualities, properties, or accidents, its totality is the bad infinite plurality of them. Such a subject, therefore, is not at all the one single property that its predicate declares. Consequently, both propositions must be united, and the positive judgment must be posited as negative instead.',
    provenance: {
      sourceChunk: 'exist-8-positive-not-true',
      sourceOp: 'exist-op-8-positive-not-true',
    },
};

// ============================================================================
// B. THE NEGATIVE JUDGMENT
// ============================================================================

export const existOp9TruthInNegative: LogicalOperation = {
  id: 'exist-op-9-truth-in-negative',
    chunkId: 'exist-9-truth-in-negative',
    label: 'Truth of Positive Judgment in Negative; "The Singular is a Particular"',
    clauses: [
      'commonNotion.truthFalsity = dependsOn(content)',
      'logicalTruth = onlyForm',
      'logicalTruth.requirement = noContradiction',
      'twoConcepts.relate = singularAndUniversal',
      'twoConcepts = trulyLogicalContent',
      'positiveJudgment.truth = false',
      'positiveJudgment.truth = inNegativeJudgment',
      'content.contradicts = itself',
      'positiveJudgment.truth = false',
      'negativeJudgment.proposition1 = "singular is not abstractly universal"',
      'negativeJudgment.proposition1.result = singular = particular',
      'negativeJudgment.proposition2 = "universal is not abstractly singular"',
      'negativeJudgment.proposition2.result = universal = particular',
      'bothReduce = "singular is particular"',
    ],
    predicates: [
      { name: 'dependsOn', args: ['truthFalsity', 'content'] },
      { name: 'relate', args: ['twoConcepts', 'singularAndUniversal'] },
      { name: 'trulyLogicalContent', args: ['twoConcepts'] },
      { name: 'contradicts', args: ['content', 'itself'] },
      { name: 'reduces', args: ['both', 'proposition'] },
    ],
    relations: [
      { predicate: 'hasTruth', from: 'positiveJudgment', to: 'negativeJudgment' },
      { predicate: 'relate', from: 'twoConcepts', to: 'singularAndUniversal' },
      { predicate: 'reduces', from: 'bothPropositions', to: '"singular is particular"' },
    ],
    candidateSummary: 'We spoke earlier of the common notion that whether the content of a judgment is true or false depends solely on the content itself, since logical truth concerns only the form and its only requirement is that such content shall not contradict itself. But we have seen that these two concepts are not just the relationless determination of a sum, but that they relate to each other as singular and universal. These are the determinations that constitute the truly logical content and also, abstracted in that way, the content of the positive judgment. It is because of this purely logical content that the positive judgment is not true but has its truth in the negative judgment. In judgment, so it is required, the content simply ought not to contradict itself; but it does contradict itself in the positive judgment, as we have just seen. The positive judgment first attains its truth in the negative judgment: the singular is not abstractly universal, but rather, the predicate of the singular, because it is such a predicate, is for that very reason itself something determinate; from the start, therefore, the singular is a particular. Furthermore, with respect to the other proposition that the positive judgment contains, the meaning of the negative judgment is that the universal is not abstractly singular but that this predicate, by the very fact that it is a predicate, is more than just mere singularity, and the universal, accordingly, is from the start equally a particular. Since this universal, as subject, is itself in the judgment determination of singularity, the two propositions both reduce to one: "the singular is a particular".',
    provenance: {
      sourceChunk: 'exist-9-truth-in-negative',
      sourceOp: 'exist-op-9-truth-in-negative',
    },
};

export const existOp10ParticularityArises: LogicalOperation = {
  id: 'exist-op-10-particularity-arises',
    chunkId: 'exist-10-particularity-arises',
    label: 'Particularity Arises Through Negative Connection; Mediated Determination',
    clauses: [
      'particularity.posited = notExternalReflection',
      'particularity.arisen = mediatedByNegativeConnection',
      'determination.results = forPredicate',
      'immediateJudgment.subject = underlyingBasis',
      'firstNegation != determination',
      'positingOfSingular = secondMoment',
      'positingOfSingular = negativeOfNegative',
      'positiveExpression = "singular is particular"',
      'positiveExpression = ofNegativeJudgment',
      'positiveJudgment.extremes = abstraction',
      'particular = firstMediatedDetermination',
      'particular.arisen = throughPositingOfJudgmentConnection',
      'determination = ofExtremes',
      'determination = ofConnection',
      'judgment.considered = negative',
    ],
    predicates: [
      { name: 'arisen', args: ['particularity', 'mediatedByNegativeConnection'] },
      { name: 'results', args: ['determination', 'forPredicate'] },
      { name: 'firstMediatedDetermination', args: ['particular'] },
      { name: 'considered', args: ['judgment', 'negative'] },
    ],
    relations: [
      { predicate: 'arisen', from: 'particularity', to: 'mediatedByNegativeConnection' },
      { predicate: 'results', from: 'determination', to: 'forPredicate' },
      { predicate: 'arisen', from: 'particular', to: 'throughPositingOfJudgmentConnection' },
    ],
    candidateSummary: 'We may remark that (a) the particularity that here comes to the predicate has already come up for consideration before; here, however, it is not posited by external reflection but has arisen rather as mediated by the negative connection indicated in the judgment. (b) This determination results here only for the predicate. In the immediate judgment, the judgment of existence, the subject is the underlying basis; the determination seems at first, therefore, to occur in the predicate. But in fact this first negation cannot as yet be a determination, or cannot truly be the positing of the singular, for such a positing is only a second moment, the negative of the negative. "The singular is a particular": this is the positive expression of the negative judgment. This expression, therefore, is not the positive judgment itself, for the latter, because of its immediacy, has an abstraction for its extremes, while the particular, precisely through the positing of the judgment connection, results as the first mediated determination. But this determination is not to be taken only as a moment of the extremes, but also as the determination of the connection, as it truly is from the start; in other words, the judgment is also to be considered as negative.',
    provenance: {
      sourceChunk: 'exist-10-particularity-arises',
      sourceOp: 'exist-op-10-particularity-arises',
    },
};

export const existOp11TransitionFounded: LogicalOperation = {
  id: 'exist-op-11-transition-founded',
    chunkId: 'exist-11-transition-founded',
    label: 'Transition Founded on Relation of Extremes; Connection Has Negativity',
    clauses: [
      'transition.founded = relationOfExtremes',
      'transition.founded = connectionInJudgment',
      'positiveJudgment = connection(singular, universal)',
      'singular.universal = immediate',
      'singular.universal.each = notWhatOtherIs',
      'connection = essentiallySeparation',
      'connection = negative',
      'positiveJudgment.mustBePosited = negative',
      'judgment.determination = notPurelyQualitative',
      'judgment.determination = notDeterminationOfReflection',
      'judgment.determination = universalWithin',
      'judgment.determination = extendingContinuously',
      'judgment.connection = sameDeterminationAsExtremes',
      'judgment.connection = universality',
      'judgment.connection = continuousExtension',
      'when(distinguished, connection.has = negativity)',
    ],
    predicates: [
      { name: 'founded', args: ['transition', 'relationOfExtremes'] },
      { name: 'essentiallySeparation', args: ['connection'] },
      { name: 'universalWithin', args: ['judgmentDetermination'] },
      { name: 'extendingContinuously', args: ['judgmentDetermination'] },
      { name: 'has', args: ['connection', 'negativity'] },
    ],
    relations: [
      { predicate: 'founded', from: 'transition', to: 'relationOfExtremes' },
      { predicate: 'founded', from: 'transition', to: 'connectionInJudgment' },
      { predicate: 'connection', from: 'singular', to: 'universal' },
      { predicate: 'has', from: 'connection', to: 'negativity' },
    ],
    candidateSummary: 'This transition is founded on the relation of the extremes and on their connection in the judgment as such. The positive judgment is the connection of the singular and the universal which are such immediately and each, therefore, is not at the same time what the other is. The connection is therefore just as essentially separation, or negative; for this reason the positive judgment was to be posited as negative. In the judgment, the determination of the extremes is equally a determinate connection. The judgment determination, or the extreme, is not the purely qualitative one of immediate being that only stands over against an other outside it. Nor is it the determination of reflection, which, in accordance with its general form, behaves positively and negatively, posited in either case as exclusive, only implicitly identical with the other. The judgment determination, as the determination of the concept, is a universal within, posited as extending continuously in its other. Conversely, the judgment connection is the same determination as the extremes have; for it is precisely this universality and continuous extension of each into the other; in so far as these are distinguished, the connection also has negativity in it.',
    provenance: {
      sourceChunk: 'exist-11-transition-founded',
      sourceOp: 'exist-op-11-transition-founded',
    },
};

export const existOp12NotUniversalParticular: LogicalOperation = {
  id: 'exist-op-12-not-universal-particular',
    chunkId: 'exist-12-not-universal-particular',
    label: 'Not-Universal is Particular; Fluid Continuity of Concept',
    clauses: [
      'transition.from = formOfConnection',
      'transition.to = formOfDetermination',
      'notOfCopula.attached = predicate',
      'predicate = notUniversal',
      'notUniversal = particular',
      'if(focusOnAbstractNonBeing, predicate = totallyIndeterminate)',
      'white = unconceptualizedDetermination',
      'notWhite = unconceptualizedNonBeing',
      'concept = trueThingInItself',
      'concept = rational',
      'otherDeterminations.belong = beingEssence',
      'otherDeterminations.notYet = formsDevelopedIntoTruth',
      'inImmediateExistence.nonBeing = limit',
      'inReflection.negative.refers = positive',
      'inReflection.ground = third',
      'inConcept.not = immediatelyPositive',
      'inConcept.negation = takenUpIntoUniversality',
      'inConcept.negation = positedAsIdentical',
      'nonUniversal = directlyParticular',
    ],
    predicates: [
      { name: 'unconceptualizedDetermination', args: ['white'] },
      { name: 'unconceptualizedNonBeing', args: ['notWhite'] },
      { name: 'trueThingInItself', args: ['concept'] },
      { name: 'takenUpIntoUniversality', args: ['negation'] },
      { name: 'positedAsIdentical', args: ['negation'] },
    ],
    relations: [
      { predicate: 'transition', from: 'formOfConnection', to: 'formOfDetermination' },
      { predicate: 'attached', from: 'notOfCopula', to: 'predicate' },
      { predicate: 'is', from: 'notUniversal', to: 'particular' },
      { predicate: 'refers', from: 'negative', to: 'positive' },
      { predicate: 'takenUp', from: 'negation', to: 'universality' },
    ],
    candidateSummary: 'The just stated transition from the form of the connection to the form of the determination has the immediate consequence that the not of the copula must just as equally be attached to the predicate and that the latter must be determined as the not-universal. But, through a no less immediate consequence, the not-universal is the particular. If the focus is on the negative according to the totally abstract determination of immediate non-being, then the predicate is the totally indeterminate not-universal. This is the determination which is normally treated in logic in connection with the contradictory concepts, and the further point is made that in the negative of a concept one should only focus on the negative, taking it as the mere indeterminate extent of the other of the positive concept. But white is an unconceptualized determination of intuition; the not of white is equally, then, unconceptualized not-being, the abstraction that came in for consideration at the very beginning of the Logic where becoming was recognized to be its closest truth. To use as an example, in the consideration of judgment determinations, an unconceptualized content of this sort, drawn from intuition and the imagination, and to take the determinations of being, and of reflection, as such judgment determinations, is the same uncritical practice as when Kant applies the concepts of the understanding to the infinite idea of reason, the so-called thing-in-itself; the concept, to which the judgment proceeding from it also belongs, is the true thing-in-itself or the rational. In the sphere of immediate existence: non-being becomes limit, and by virtue of this limit the something refers to an other despite itself. In the sphere of reflection, on the other hand, it is the negative that refers essentially to a positive, and is thereby determined; a negative is no longer that indeterminate non-being, for it is posited to be only to the extent that the positive stands over against it, and as third comes their ground. But it is all the more in the absolutely fluid continuity of the concept that the not is immediately a positive, and the negation is not just determinateness but is taken up into universality and is posited as identical with it. The non-universal is therefore directly the particular.',
    provenance: {
      sourceChunk: 'exist-12-not-universal-particular',
      sourceOp: 'exist-op-12-not-universal-particular',
    },
};

export const existOp13StillJudgment: LogicalOperation = {
  id: 'exist-op-13-still-judgment',
    chunkId: 'exist-13-still-judgment',
    label: 'Negative Judgment Still a Judgment; Universal Sphere Retained',
    clauses: [
      'negativeJudgment = stillJudgment',
      'negativeJudgment = relation(subject, predicate)',
      'negativeJudgment = relation(singularity, universality)',
      'negativeJudgment = formOfJudgment',
      'subject.untouched = byNegation',
      'subject.retains = determinationOfHavingPredicate',
      'subject.retains = referenceToUniversality',
      'whatNegated = notUniversality',
      'whatNegated = abstractionOfPredicate',
      'whatNegated = determinatenessOfPredicate',
      'negativeJudgment != totalNegation',
      'universalSphere.remains = standing',
      'universalSphere.contains = predicate',
      'connection.still = essentiallyPositive',
      'example = "rose is not red"',
      'example.onlyDenied = determinateness',
      'example.separated = fromUniversality',
      'example.color = retained',
      'fromSideOfUniversalSphere.judgment = stillPositive',
      'positiveExpression = "singular is particular"',
      'positiveExpression.expresses = particularContainsUniversality',
      'positiveExpression.expresses = predicateDeterminate',
      'negativeForm = roseNotRed',
      'negativeForm.supposed = haveOtherDeterminateColor',
      'singularityOfDeterminateness = onlySublated',
      'universalSphere = leftStanding',
      'determinateness.retained = transformedIntoParticularity',
    ],
    predicates: [
      { name: 'stillJudgment', args: ['negativeJudgment'] },
      { name: 'untouched', args: ['subject', 'byNegation'] },
      { name: 'retains', args: ['subject', 'determination'] },
      { name: 'totalNegation', args: ['negativeJudgment'] },
      { name: 'transformedIntoParticularity', args: ['determinateness'] },
    ],
    relations: [
      { predicate: 'untouched', from: 'subject', to: 'byNegation' },
      { predicate: 'retains', from: 'subject', to: 'determinationOfHavingPredicate' },
      { predicate: 'retains', from: 'subject', to: 'referenceToUniversality' },
      { predicate: 'contains', from: 'universalSphere', to: 'predicate' },
      { predicate: 'transformed', from: 'determinateness', to: 'particularity' },
    ],
    candidateSummary: 'Since negation has to do with the connection of judgment, and we are considering the negative judgment still as such, the latter is in the first instance still a judgment; we thus have the relation of subject and predicate, or of singularity and universality, and their connection, the form of the judgment. The subject, as the immediate underlying basis, remains untouched by the negation; it retains, therefore, its determination of having a predicate, or its reference to the universality. Consequently, what is negated in the predicate is not the universality as such, but the abstraction or the determinateness of the predicate that appeared as content in contrast to that universality. The negative judgment is not, therefore, total negation; the universal sphere which contains the predicate remains standing; the connection of subject and the predicate is therefore still essentially positive; the yet remaining determination of the predicate is no less connection. When it is said that, for instance, the rose is not red, only the determinateness of the predicate is thereby denied and thus separated from the universality which equally attaches to it; the universal sphere, color, is retained; if the rose is not red, it is nonetheless assumed that it has a color, though another color. From the side of this universal sphere, the judgment is still positive. "The singular is a particular." This positive form of the negative judgment immediately expresses that the particular contains universality. In addition, it also expresses that the predicate is not just a universal but also one which is still determinate. The negative form contains the same, for although the rose, for instance, is not red, it is supposed, nevertheless, not only still to retain the universal sphere of color as predicate, but to have some other determinate color as well; the singularity of determinateness of the rose is therefore only sublated; and not only is the universal sphere left standing but determinateness too is retained, although transformed into an indeterminate determinateness, a universal determinateness, that is to say, into particularity.',
    provenance: {
      sourceChunk: 'exist-13-still-judgment',
      sourceOp: 'exist-op-13-still-judgment',
    },
};

export const existOp14ParticularityMediating: LogicalOperation = {
  id: 'exist-op-14-particularity-mediating',
    chunkId: 'exist-14-particularity-mediating',
    label: 'Particularity as Mediating Term; Determinate Determinate',
    clauses: [
      'particularity = positiveDetermination(negativeJudgment)',
      'particularity = termMediating(singularity, universality)',
      'negativeJudgment.provides = mediation',
      'negativeJudgment.provides = thirdStep',
      'thirdStep = reflection(judgmentOfExistence)',
      'objectiveMeaning = momentOfAlteration(accidents)',
      'objectiveMeaning = singularizedProperties(concrete)',
      'throughAlteration.fullDeterminateness = emerges',
      'throughAlteration.concrete = posited',
      'positiveExpression = "singular is particular"',
      'singular.also = notParticular',
      'particularity.extension = wider',
      'particularity.extension = thanSingularity',
      'predicate.corresponds = false',
      'negativity = "singular is only a singular"',
      'negativity.refers = nothingElse',
      'negativity.refers = exceptItself',
      'rose = notThingOfSomeColor',
      'rose = oneDeterminateColor',
      'rose = roseColor',
      'singular = notIndeterminateDeterminate',
      'singular = determinateDeterminate',
    ],
    predicates: [
      { name: 'positiveDetermination', args: ['particularity', 'negativeJudgment'] },
      { name: 'termMediating', args: ['particularity', 'singularity', 'universality'] },
      { name: 'provides', args: ['negativeJudgment', 'mediation'] },
      { name: 'momentOfAlteration', args: ['objectiveMeaning', 'accidents'] },
      { name: 'determinateDeterminate', args: ['singular'] },
    ],
    relations: [
      { predicate: 'mediates', from: 'particularity', to: 'singularity' },
      { predicate: 'mediates', from: 'particularity', to: 'universality' },
      { predicate: 'provides', from: 'negativeJudgment', to: 'mediation' },
      { predicate: 'refers', from: 'negativity', to: 'nothingElse' },
      { predicate: 'refers', from: 'negativity', to: 'exceptItself' },
    ],
    candidateSummary: 'The particularity that has resulted as the positive determination of the negative judgment is the term mediating singularity and universality; so the negative judgment is now that which provides in general the mediation for the third step, that of the reflection of the judgment of existence into itself. This judgment is according to its objective meaning only the moment of the alteration of accidents, or, in the sphere of existence, of the singularized properties of the concrete. Through this alteration, the full determinateness of the predicate, or the concrete, emerges as posited. "The singular is particular" is what the positive expression of the negative judgment says. But the singular is also not particular, for particularity is of wider extension than singularity; it is a predicate, therefore, that does not correspond to the subject, one in which the latter, therefore, does not as yet have its truth. "The singular is only a singular": this is a negativity that refers to nothing else, be it positive or negative, except itself. The rose is not a thing of some color or other, but one that only has the one determinate color which is the rose-color. The singular is not an indeterminate determinate but the determinate determinate.',
    provenance: {
      sourceChunk: 'exist-14-particularity-mediating',
      sourceOp: 'exist-op-14-particularity-mediating',
    },
};

export const existOp15NegationNegative: LogicalOperation = {
  id: 'exist-op-15-negation-negative',
    chunkId: 'exist-15-negation-negative',
    label: 'Negation of Negative Judgment; Second Negation',
    clauses: [
      'negation.appears = firstNegation',
      'negation.is = notFirstNegation',
      'negativeJudgment = secondNegation',
      'negativeJudgment = negationOfNegation',
      'negativeJudgment.inAndForItself = toBePosited',
      'judgment.negates = determinatenessOfPredicate',
      'judgment.negates = abstractUniversality',
      'judgment.negates = singularQuality',
      'negationOfDeterminateness = secondNegation',
      'negationOfDeterminateness = infiniteTurningBack',
      'infiniteTurningBack = ofSingularity',
      'infiniteTurningBack = intoItself',
      'restoration = concreteTotality(subject)',
      'subject.now = positedAsSingular',
      'subject.mediated = withItself',
      'subject.mediated = throughNegation',
      'subject.mediated = throughSublationOfNegation',
      'predicate.passedOver = fromFirstUniversality',
      'predicate.passedOver = toAbsoluteDeterminateness',
      'predicate.madeEqual = toSubject',
      'judgment.says = "singular is singular"',
      'fromOtherSide.subject = universal',
      'predicate.expanded = intoParticularity',
      'negationOfDeterminateness = purification(universality)',
      'judgment.says = "universal is universal"',
    ],
    predicates: [
      { name: 'secondNegation', args: ['negativeJudgment'] },
      { name: 'negationOfNegation', args: ['negativeJudgment'] },
      { name: 'infiniteTurningBack', args: ['ofSingularity', 'intoItself'] },
      { name: 'concreteTotality', args: ['subject'] },
      { name: 'positedAsSingular', args: ['subject'] },
      { name: 'purification', args: ['negationOfDeterminateness', 'universality'] },
    ],
    relations: [
      { predicate: 'is', from: 'negativeJudgment', to: 'secondNegation' },
      { predicate: 'is', from: 'negativeJudgment', to: 'negationOfNegation' },
      { predicate: 'turningBack', from: 'singularity', to: 'itself' },
      { predicate: 'mediated', from: 'subject', to: 'withItself' },
      { predicate: 'passedOver', from: 'predicate', to: 'absoluteDeterminateness' },
      { predicate: 'expanded', from: 'predicate', to: 'particularity' },
    ],
    candidateSummary: 'This negation of the negative judgment appears, when one starts from its positive form, to be again a first negation. But this is not what it is. The negative judgment is again, in and for itself, already the second negation or the negation of negation, and this, what it is in and for itself, is to be posited. To wit: the judgment negates the determinateness of the predicate of the positive judgment, its abstract universality, or, considered as content, the singular quality that it possesses of the subject. But the negation of the determinateness is already the second negation, hence the infinite turning back of the singularity into itself. With this, therefore, the restoration of the concrete totality of the subject has taken place, or rather, the subject is now for the first time posited as singular, for through the negation and the sublation of that negation it is mediated with itself. The predicate, for its part, has thereby passed over from the first universality to absolute determinateness and made itself equal to the subject. Thus the judgment says: "the singular is singular." From the other side, since the subject was equally to be taken as a universal, and since in the negative judgment the predicate, which as against that subject is the singular, expanded into particularity; moreover, since now the negation of this determinateness is equally the purification of the universality contained in the predicate, this judgment also says: "the universal is the universal."',
    provenance: {
      sourceChunk: 'exist-15-negation-negative',
      sourceOp: 'exist-op-15-negation-negative',
    },
};

// ============================================================================
// C. THE INFINITE JUDGMENT
// ============================================================================

export const existOp16InfiniteNegative: LogicalOperation = {
  id: 'exist-op-16-infinite-negative',
    chunkId: 'exist-16-infinite-negative',
    label: 'Infinite Judgment: Negative Infinite; Nonsensical',
    clauses: [
      'twoJudgments.obtained = throughExternalReflection',
      'twoJudgments.express = predicateInPositivity',
      'negationOfNegativeJudgment.mustAppear = inFormOfNegativeJudgment',
      'negativeJudgment.stillContains = positiveConnection',
      'negativeJudgment.stillContains = universalSphere',
      'negativeJudgment.contains = universality',
      'negativeJudgment.universality = morePurified',
      'negativeJudgment.universality = ofLimitation',
      'negativeJudgment.universality = thanPositiveJudgment',
      'negativeJudgment.universality = allTheMoreToBeNegated',
      'negativeJudgment.universality = ofSubjectAsSingular',
      'wholeExtentOfPredicate = negated',
      'noLongerPositiveConnection = betweenPredicateAndSubject',
      'this = infiniteJudgment',
      'negativeInfinite = judgmentInWhichFormSublated',
      'negativeInfinite = nonsensicalJudgment',
      'negativeInfinite.ought = toBeJudgment',
      'negativeInfinite.contains = connection',
      'negativeInfinite.connection = oughtNotBeThere',
      'examples = spiritNotRed',
      'examples = roseNotElephant',
      'examples = understandingNotTable',
      'examples.correct = true',
      'examples.nonsensical = true',
      'examples.fatuous = true',
      'examples = notJudgments',
      'moreRealistic = evilAction',
      'moreRealistic = crime',
      'inCivilLitigation.thingNegated = asProperty',
      'inCivilLitigation.stillConceded = ifPartyHadRight',
      'inCivilLitigation.universalSphere = right',
      'inCivilLitigation.universalSphere = acknowledged',
      'crime = infiniteJudgment',
      'crime.negates = notOnlyParticularRight',
      'crime.negates = universalSphere',
      'crime.negates = rightAsRight',
      'crime.correct = effectiveAction',
      'crime.stands = thoroughlyNegative',
      'crime.stands = withRespectToMorality',
      'crime.nonsensical = true',
    ],
    predicates: [
      { name: 'nonsensicalJudgment', args: ['negativeInfinite'] },
      { name: 'formSublated', args: ['negativeInfinite'] },
      { name: 'evilAction', args: ['crime'] },
      { name: 'thoroughlyNegative', args: ['crime', 'withRespectToMorality'] },
    ],
    relations: [
      { predicate: 'obtained', from: 'twoJudgments', to: 'throughExternalReflection' },
      { predicate: 'mustAppear', from: 'negationOfNegativeJudgment', to: 'inFormOfNegativeJudgment' },
      { predicate: 'contains', from: 'negativeJudgment', to: 'positiveConnection' },
      { predicate: 'contains', from: 'negativeJudgment', to: 'universalSphere' },
      { predicate: 'negates', from: 'crime', to: 'notOnlyParticularRight' },
      { predicate: 'negates', from: 'crime', to: 'universalSphere' },
    ],
    candidateSummary: 'In these two judgments, which were earlier obtained through external reflection, the predicate is already expressed in its positivity. But the negation of the negative judgment must itself first appear in the form of a negative judgment. It has just been shown that there still remained in this judgment a positive connection of subject and predicate as well the universal sphere of the latter. From this side, the negative judgment thus contains a universality which is more purified of limitation than was contained by the positive judgment and is for this reason all the more to be negated of the subject as a singular. In this manner, the whole extent of the predicate is negated, and there is no longer any positive connection between it and the subject. This is the infinite judgment. The negative infinite, a judgment in which even the form of judgment is sublated, is a nonsensical judgment. It ought to be a judgment, and hence contains a connection of subject and predicate; but any such connection ought not at the same time to be there. Examples of negatively infinite judgments are easy to come by: spirit is not red, yellow, etc., is not acid, not alkali, etc., or that the rose is not an elephant, the understanding is not a table, and the like. These judgments are correct or true, as it is said, and yet, any such truth notwithstanding, nonsensical and fatuous. Or, more to the point, they are not judgments at all. A more realistic example of the infinite judgment is the evil action. In civil litigation, when a thing is negated as the property of another party, it is still conceded that the same thing would indeed belong to that party if the latter had a right to it. It is only under the title of right that the possession of it is challenged; in the negative judgment, therefore, the universal sphere, "right," is still acknowledged and maintained. But crime is the infinite judgment that negates, not only the particular right, but the universal sphere, the right as right. It has correctness, in the sense that it is an effective action, but since it stands in a thoroughly negative fashion with respect to the morality that constitutes its sphere, it is nonsensical.',
    provenance: {
      sourceChunk: 'exist-16-infinite-negative',
      sourceOp: 'exist-op-16-infinite-negative',
    },
};

export const existOp17InfinitePositive: LogicalOperation = {
  id: 'exist-op-17-infinite-positive',
    chunkId: 'exist-17-infinite-positive',
    label: 'Positive Infinite: "The Singular is Singular"; Judgment Sublated',
    clauses: [
      'positiveElement = negationOfNegation',
      'positiveElement = reflectionOfSingularity',
      'positiveElement = intoItself',
      'singularity.firstPosited = asDeterminateDeterminate',
      'positiveInfinite.says = "singular is singular"',
      'inJudgmentOfExistence.subject = immediateSingular',
      'inJudgmentOfExistence.subject = moreOfJustSomething',
      'throughMediation.posited = asSingular',
      'throughMediation.posited = forFirstTime',
      'singular.posited = asExpanding',
      'singular.expanding = intoPredicate',
      'singular.predicate = identical',
      'universality.noLonger = immediate',
      'universality = summingOfDistincts',
      'positivelyInfinite.says = "universal is universal"',
      'positivelyInfinite.universal = positedAsTurningBack',
      'positivelyInfinite.universal = intoItself',
      'throughReflection.judgmentDeterminations = intoThemselves',
      'throughReflection.judgment = sublated',
      'negativelyInfinite.difference = tooGreat',
      'negativelyInfinite.stillRemain = judgment',
      'negativelyInfinite.subjectPredicate = noPositiveConnection',
      'positivelyInfinite.only = identity',
      'positivelyInfinite.totalLack = difference',
      'positivelyInfinite.noLonger = judgment',
    ],
    predicates: [
      { name: 'reflectionOfSingularity', args: ['positiveElement', 'intoItself'] },
      { name: 'determinateDeterminate', args: ['singularity'] },
      { name: 'summingOfDistincts', args: ['universality'] },
      { name: 'turningBack', args: ['universal', 'intoItself'] },
      { name: 'sublated', args: ['judgment'] },
    ],
    relations: [
      { predicate: 'is', from: 'positiveElement', to: 'negationOfNegation' },
      { predicate: 'is', from: 'positiveElement', to: 'reflectionOfSingularity' },
      { predicate: 'firstPosited', from: 'singularity', to: 'asDeterminateDeterminate' },
      { predicate: 'expanding', from: 'singular', to: 'intoPredicate' },
      { predicate: 'identical', from: 'singular', to: 'predicate' },
      { predicate: 'turningBack', from: 'universal', to: 'intoItself' },
    ],
    candidateSummary: 'The positive element of the infinite judgment, the negation of the negation, is the reflection of singularity into itself by virtue of which the singularity is first posited as the determinate determinate. "The singular is singular" is what the infinite judgment said according to that reflection. In the judgment of existence, the subject is as the immediate singular, hence more of just a something in general. Through the mediation of the negative and infinite judgment, it is posited as singular for the first time. The singular is thus posited as expanding into its predicate, which is identical with it; to the same extent, therefore, universality is also no longer anything immediate but a summing of distincts. The positively infinite judgment equally says, "the universal is universal," and in this the universal is posited also as a turning back into itself. Now through the reflection of the judgment determinations into themselves, the judgment has sublated itself; in the negatively infinite judgment, the difference is, so to speak, too great for it still to remain a judgment; subject and predicate have no positive connection whatsoever to each other; in the positively infinite judgment, on the contrary, only identity is present, and because of this total lack of difference there is no longer a judgment.',
    provenance: {
      sourceChunk: 'exist-17-infinite-positive',
      sourceOp: 'exist-op-17-infinite-positive',
    },
};

export const existOp18TransitionReflection: LogicalOperation = {
  id: 'exist-op-18-transition-reflection',
    chunkId: 'exist-18-transition-reflection',
    label: 'Transition to Judgment of Reflection; Terms Reflected into Themselves',
    clauses: [
      'judgmentOfExistence.has = sublatedItself',
      'posited = whatCopulaContains',
      'copula.contains = inIdentity',
      'copula.contains = qualitativeExtremesSublated',
      'since(unity = concept, immediatelyTornApart = judgment)',
      'terms.noLonger = immediatelyDetermined',
      'terms = reflectedIntoThemselves',
      'judgmentOfExistence.passedOver = intoJudgmentOfReflection',
    ],
    predicates: [
      { name: 'sublatedItself', args: ['judgmentOfExistence'] },
      { name: 'qualitativeExtremesSublated', args: ['copula'] },
      { name: 'immediatelyTornApart', args: ['unity', 'judgment'] },
      { name: 'reflectedIntoThemselves', args: ['terms'] },
      { name: 'passedOver', args: ['judgmentOfExistence', 'intoJudgmentOfReflection'] },
    ],
    relations: [
      { predicate: 'has', from: 'judgmentOfExistence', to: 'sublatedItself' },
      { predicate: 'contains', from: 'copula', to: 'inIdentity' },
      { predicate: 'contains', from: 'copula', to: 'qualitativeExtremesSublated' },
      { predicate: 'is', from: 'unity', to: 'concept' },
      { predicate: 'tornApart', from: 'unity', to: 'judgment' },
      { predicate: 'passedOver', from: 'judgmentOfExistence', to: 'judgmentOfReflection' },
    ],
    candidateSummary: 'More precisely, it is the judgment of existence that has sublated itself and, consequently, there is posited what the copula of the judgment contains, namely that in its identity the qualitative extremes are sublated. But since this unity is the concept, it is immediately torn apart and is a judgment, but one whose terms are no longer immediately determined but are reflected into themselves. The judgment of existence has passed over into the judgment of reflection.',
    provenance: {
      sourceChunk: 'exist-18-transition-reflection',
      sourceOp: 'exist-op-18-transition-reflection',
    },
};

export const judgmentOfExistenceOperations: LogicalOperation[] = [
  existOp1JudgmentTruth,
  existOp2JudgmentInherence,
  existOp3SubjectPredicateDeterminations,
  existOp4FirstPureExpression,
  existOp5ObjectiveMeaningResolution,
  existOp6TwofoldResultFormContent,
  existOp7CannotBeUnited,
  existOp8PositiveNotTrue,
  existOp9TruthInNegative,
  existOp10ParticularityArises,
  existOp11TransitionFounded,
  existOp12NotUniversalParticular,
  existOp13StillJudgment,
  existOp14ParticularityMediating,
  existOp15NegationNegative,
  existOp16InfiniteNegative,
  existOp17InfinitePositive,
  existOp18TransitionReflection,
];

