/**
 * Logical Operations: The Judgment of Necessity
 *
 * The judgment of necessity shows the connection of objective universality
 * (genus and species) through categorical, hypothetical, and disjunctive forms,
 * revealing the necessity of the concept itself.
 *
 * Dialectical Movement:
 * - Categorical Judgment: Genus divides into species; substantial identity
 * - Hypothetical Judgment: "If A is, then B is"; being of an other
 * - Disjunctive Judgment: "A is either B or C"; necessity of concept
 *
 * This judgment reveals how objective universality (genus) connects with
 * particularity (species) through necessary relations, culminating in the
 * disjunctive judgment where the concept itself is posited.
 */

import type { LogicalOperation } from '../../../types';

// ============================================================================
// INTRODUCTION: Objective Universality
// ============================================================================

export const necOp1IntroductionObjective: LogicalOperation = {
  id: 'nec-op-1-introduction-objective',
    chunkId: 'nec-1-introduction-objective',
    label: 'Introduction: Objective Universality; Distinguished from Substantiality; Genus and Species',
    clauses: [
      'universality.advanced = objectiveUniversality',
      'objectiveUniversality = existsInAndForItself',
      'objectiveUniversality.corresponds = substantiality',
      'objectiveUniversality.distinguished = fromSubstantiality',
      'objectiveUniversality.belongs = toConcept',
      'objectiveUniversality = positedNecessity',
      'objectiveUniversality.distinction = immanent',
      'substance.distinction = onlyInAccidents',
      'substance.distinction != principle',
      'objectiveUniversality.posited1 = asEssential',
      'objectiveUniversality.posited1 = asImmanent',
      'objectiveUniversality.posited2 = asDiverse',
      'objectiveUniversality.posited2 = asParticularity',
      'objectiveUniversality.determined = asGenusAndSpecies',
    ],
    predicates: [
      { name: 'objectiveUniversality', args: ['universality.advanced'] },
      { name: 'existsInAndForItself', args: ['objectiveUniversality'] },
      { name: 'positedNecessity', args: ['objectiveUniversality'] },
      { name: 'immanent', args: ['distinction'] },
      { name: 'genusAndSpecies', args: ['objectiveUniversality.determined'] },
    ],
    relations: [
      { predicate: 'advanced', from: 'universality', to: 'objectiveUniversality' },
      { predicate: 'corresponds', from: 'objectiveUniversality', to: 'substantiality' },
      { predicate: 'belongs', from: 'objectiveUniversality', to: 'toConcept' },
      { predicate: 'determined', from: 'objectiveUniversality', to: 'asGenusAndSpecies' },
    ],
    candidateSummary: 'The determination to which universality has advanced is, as we have seen, the universality that exists in and for itself or the objective universality that in the sphere of essence corresponds to substantiality. It is distinguished from the latter because it belongs to the concept and for this reason is not only the inner but also the posited necessity of its determinations, or in other words, the distinction is immanent to it, whereas substance has its distinction only in its accidents, does not have it as a principle within it. In the judgment now, this objective universality is posited, first, posited with this determinateness as essential to it, immanent to it; second, posited with it as diverse from it, a particularity for which the said universality constitutes the substantial basis. In this way the universality is determined as genus and species.',
    provenance: {
      sourceChunk: 'nec-1-introduction-objective',
      sourceOp: 'nec-op-1-introduction-objective',
    },
};

// ============================================================================
// A. THE CATEGORICAL JUDGMENT
// ============================================================================

export const necOp2CategoricalGenusDivides: LogicalOperation = {
  id: 'nec-op-2-categorical-genus-divides',
    chunkId: 'nec-2-categorical-genus-divides',
    label: 'Categorical Judgment: Genus Divides into Species; Substantial Identity',
    clauses: [
      'genus.essentiallyDivides = intoSpecies',
      'genus.repels = intoSpecies',
      'genus.isGenus = onlyInsofarAs(comprehendsSpecies)',
      'species.isSpecies = onlyInsofarAs(existsInSingulars)',
      'species.possesses = higherUniversality',
      'categoricalJudgment.predicate = universality',
      'subject.possesses = immanentNature',
      'categoricalJudgment = firstJudgmentOfNecessity',
      'categoricalJudgment = immediateJudgmentOfNecessity',
      'subject.determinateness = singular',
      'subject.contrasted = toGenus',
      'subject.contrasted = toSpecies',
      'subject.belongs = toImmediacy',
      'subject.belongs = toExternalConcreteExistence',
      'objectiveUniversality.has = firstImmediateParticularization',
      'objectiveUniversality = determinateGenus',
      'objectiveUniversality != mostProximateGenus',
      'objectiveUniversality.determinateness != principle',
      'necessary = substantialIdentity(subject, predicate)',
      'distinguishingMark = unessentialPositedness',
      'distinguishingMark = onlyName',
      'subject.reflected = intoBeingInAndForItself',
    ],
    predicates: [
      { name: 'essentiallyDivides', args: ['genus', 'intoSpecies'] },
      { name: 'repels', args: ['genus', 'intoSpecies'] },
      { name: 'comprehendsSpecies', args: ['genus'] },
      { name: 'immanentNature', args: ['subject.possesses'] },
      { name: 'substantialIdentity', args: ['subject', 'predicate'] },
      { name: 'beingInAndForItself', args: ['subject.reflected'] },
    ],
    relations: [
      { predicate: 'divides', from: 'genus', to: 'intoSpecies' },
      { predicate: 'repels', from: 'genus', to: 'intoSpecies' },
      { predicate: 'possesses', from: 'subject', to: 'immanentNature' },
      { predicate: 'reflected', from: 'subject', to: 'intoBeingInAndForItself' },
    ],
    candidateSummary: 'The genus essentially divides or repels itself into species; it is genus only in so far as it comprehends the species under it; the species is a species only in so far as, on the one side, it exists in singulars, and, on the other side, it possesses in the genus a higher universality. Now the categorical judgment has for predicate such a universality as in it the subject possesses its immanent nature. But the categorical judgment is itself the first or the immediate judgment of necessity; consequently, the determinateness of the subject, by virtue of which the latter is a singular as contrasted to the genus or the species, belongs to the immediacy of external concrete existence. But objective universality also has here only its first immediate particularization; on the one hand, therefore, it is itself a determinate genus with respect to which there are higher genera; on the other hand, it is not the most proximate genus, that is, its determinateness is not directly the principle of the specific particularity of the subject. But what is necessary in it is the substantial identity of subject and predicate, in view of which the distinguishing mark of each is only an unessential positedness or even only a name; in its predicate, the subject is reflected into its being-in-and-for-itself.',
    provenance: {
      sourceChunk: 'nec-2-categorical-genus-divides',
      sourceOp: 'nec-op-2-categorical-genus-divides',
    },
};

export const necOp3CategoricalDistinguished: LogicalOperation = {
  id: 'nec-op-3-categorical-distinguished',
    chunkId: 'nec-3-categorical-distinguished',
    label: 'Categorical Distinguished from Positive/Negative; Totality of Form',
    clauses: [
      'categoricalPredicate != classedWithPreceding',
      'example1 = "rose is red"',
      'example2 = "rose is a plant"',
      'externalProperty != vegetableNature',
      'categoricalJudgment.distinguished = fromPositiveNegative',
      'positiveNegative.content = singularAccidentalContent',
      'categorical.content = totalityOfForm',
      'categorical.content.reflected = intoItself',
      'categorical.copula = necessity',
      'positiveNegative.copula = abstractImmediateBeing',
    ],
    predicates: [
      { name: 'classedWithPreceding', args: ['categoricalPredicate'] },
      { name: 'singularAccidentalContent', args: ['positiveNegative.content'] },
      { name: 'totalityOfForm', args: ['categorical.content'] },
      { name: 'reflectedIntoItself', args: ['categorical.content'] },
    ],
    relations: [
      { predicate: 'distinguished', from: 'categoricalJudgment', to: 'fromPositiveNegative' },
      { predicate: 'is', from: 'categorical.copula', to: 'necessity' },
      { predicate: 'is', from: 'positiveNegative.copula', to: 'abstractImmediateBeing' },
    ],
    candidateSummary: 'Such a predicate ought not to be classed with the predicates of the preceding judgments. For example, to throw together into one class these judgments: "The rose is red," "The rose is a plant," or "This ring is yellow," "It is gold," and thus to take such an external property as the color of a flower as a predicate equal to its vegetable nature, is to overlook a difference which the dullest mind would not miss. The categorical judgment, therefore, is definitely to be distinguished from the positive and the negative judgment; in these, what is said of the subject is a singular accidental content; in the former, the content is the totality of the form reflected into itself. In this content, therefore, the copula has the meaning of necessity, whereas in that of the other two it has only the meaning of abstract, immediate being.',
    provenance: {
      sourceChunk: 'nec-3-categorical-distinguished',
      sourceOp: 'nec-op-3-categorical-distinguished',
    },
};

export const necOp4CategoricalPassesHypothetical: LogicalOperation = {
  id: 'nec-op-4-categorical-passes-hypothetical',
    chunkId: 'nec-4-categorical-passes-hypothetical',
    label: 'Categorical: Inner Necessity; Passes to Hypothetical',
    clauses: [
      'subject.determinateness = atFirstContingent',
      'subject.predicate.notConnected = withNecessity',
      'subject.predicate.notConnected = byForm',
      'necessity = innerOne',
      'subject = subjectOnlyAsParticular',
      'objectiveUniversal.determining = connection(identity, repelledDeterminateness)',
      'connection = essentially',
      'determinateness != merelyAccidental',
      'throughNecessityOfImmediateBeing',
      'categoricalJudgment.conforms = toObjectiveUniversality',
      'categoricalJudgment.passedOver = intoHypothetical',
    ],
    predicates: [
      { name: 'atFirstContingent', args: ['subject.determinateness'] },
      { name: 'innerOne', args: ['necessity'] },
      { name: 'connection', args: ['identity', 'repelledDeterminateness'] },
      { name: 'essentially', args: ['connection'] },
      { name: 'merelyAccidental', args: ['determinateness'] },
      { name: 'passedOver', args: ['categoricalJudgment', 'intoHypothetical'] },
    ],
    relations: [
      { predicate: 'notConnected', from: 'subject.predicate', to: 'withNecessity' },
      { predicate: 'determining', from: 'objectiveUniversal', to: 'connection' },
      { predicate: 'conforms', from: 'categoricalJudgment', to: 'toObjectiveUniversality' },
      { predicate: 'passedOver', from: 'categoricalJudgment', to: 'intoHypothetical' },
    ],
    candidateSummary: 'The determinateness of the subject, which makes it a particular with respect to the predicate, is at first still something contingent; subject and predicate are not connected with necessity by the form or the determinateness; the necessity is therefore still an inner one. The subject is subject, however, only as a particular, and to the extent that it possesses objective universality, it has to possess it essentially in accordance with that at first immediate determinateness. The objective universal, in determining itself, that is, in positing itself in a judgment, is in a connection of identity with this repelled determinateness as such, essentially, that is, this determinateness is not to be posited as merely accidental. Only through this necessity of its immediate being does the categorical judgment conform to its objective universality and, in this way, has passed over into the hypothetical judgment.',
    provenance: {
      sourceChunk: 'nec-4-categorical-passes-hypothetical',
      sourceOp: 'nec-op-4-categorical-passes-hypothetical',
    },
};

// ============================================================================
// B. THE HYPOTHETICAL JUDGMENT
// ============================================================================

export const necOp5HypotheticalIfThen: LogicalOperation = {
  id: 'nec-op-5-hypothetical-if-then',
    chunkId: 'nec-5-hypothetical-if-then',
    label: 'Hypothetical Judgment: "If A is, then B is"; Being of an Other',
    clauses: [
      'hypotheticalJudgment = "ifA is, thenB is"',
      'hypotheticalJudgment = "beingOfA is notItsOwnBeing"',
      'hypotheticalJudgment = "beingOfA is beingOfOther(B)"',
      'posited = necessaryConnectedness(immediateDeterminacies)',
      'connectedness.notPosited = inCategoricalJudgment',
      'twoImmediateExistences = externallyContingent',
      'inCategoricalJudgment = onlyOne(subject)',
      'one.external = toOther',
      'other.external = toFirst',
      'contents.indifferent = toEachOther',
      'judgment = propositionOfEmptyForm',
      'immediacy = selfSubsistent',
      'immediacy = concreteBeing',
      'essential = connection',
      'being = merePossibility',
      'hypotheticalJudgment.notSays = A is',
      'hypotheticalJudgment.notSays = B is',
      'hypotheticalJudgment.says = ifOne, thenOther',
      'posited = connectednessOfExtremes',
      'notPosited = extremesThemselves',
      'eachExtreme = beingOfOther',
      'principleOfIdentity.asserts = A is onlyA, notB',
      'principleOfIdentity.asserts = B is onlyB, notA',
      'hypotheticalJudgment.posits = beingOfFiniteThings',
      'hypotheticalJudgment.posits = throughConcept',
      'hypotheticalJudgment.posits = accordingToFormalTruth',
      'finite = itsOwnBeing',
      'finite = notItsOwnBeing',
      'finite = beingOfOther',
      'inSphereOfBeing.finite = alters',
      'inSphereOfBeing.finite = comesToBeOther',
      'inSphereOfEssence.finite = appearance',
      'inSphereOfEssence.being = reflectiveShining',
      'inSphereOfEssence.necessity = innerConnection',
      'concept = identityPosited',
      'existent = notAbstractSelfIdentity',
      'existent = concreteSelfIdentity',
      'existent.immediately = beingOfOther',
    ],
    predicates: [
      { name: 'necessaryConnectedness', args: ['immediateDeterminacies'] },
      { name: 'externallyContingent', args: ['twoImmediateExistences'] },
      { name: 'propositionOfEmptyForm', args: ['judgment'] },
      { name: 'merePossibility', args: ['being'] },
      { name: 'beingOfOther', args: ['eachExtreme'] },
      { name: 'concreteSelfIdentity', args: ['existent'] },
    ],
    relations: [
      { predicate: 'posited', from: 'hypotheticalJudgment', to: 'necessaryConnectedness' },
      { predicate: 'is', from: 'being', to: 'merePossibility' },
      { predicate: 'is', from: 'eachExtreme', to: 'beingOfOther' },
      { predicate: 'posits', from: 'hypotheticalJudgment', to: 'beingOfFiniteThings' },
      { predicate: 'is', from: 'existent', to: 'concreteSelfIdentity' },
    ],
    candidateSummary: '"If A is, then B is"; or "The being of A is not its own being but the being of an other, of B." What is posited in this judgment is the necessary connectedness of immediate determinacies, a connectedness which in the categorical judgment is not yet posited. There are here two immediate, or externally contingent concrete existences, of which in the categorical judgment there is at first only one, the subject; but since one is external to the other, this other is immediately also external with respect to the first. On account of this immediacy, the contents of both sides are still indifferent to each other; at first, therefore, this judgment is a proposition of empty form. Now, first, the immediacy is as such indeed self-subsistent, a concrete being; but, second, what is essential is its connection; this being is therefore just as much mere possibility; the hypothetical judgment does not say either that A is, or that B is, but only that if the one is, then the other is; only the connectedness of the extremes is posited as existing, not the extremes themselves. Indeed, each extreme is posited in this necessity as equally the being of an other. The principle of identity asserts that A is only A, not B; and B is only B, not A. In the hypothetical judgment, on the contrary, the being of finite things is posited through the concept in accordance with their formal truth, namely that the finite is its own being, but equally is not its own being but is the being of an other. In the sphere of being, the finite alters and comes to be an other. In the sphere of essence, it is appearance; its being is posited to consist in the reflective shining of an other in it, and the necessity is the inner connection not yet posited as such. But the concept is this: that this identity is posited; that the existent is not abstract self-identity but concrete self-identity and is, immediately within it, the being of an other.',
    provenance: {
      sourceChunk: 'nec-5-hypothetical-if-then',
      sourceOp: 'nec-op-5-hypothetical-if-then',
    },
};

export const necOp6HypotheticalRelations: LogicalOperation = {
  id: 'nec-op-6-hypothetical-relations',
  chunkId: 'nec-6-hypothetical-relations',
    label: 'Hypothetical: Relations of Reflection; Indeterminate Form; Passes to Disjunctive',
    clauses: [
      'hypotheticalJudgment.determined = asRelationsOfReflection',
      'relations = groundConsequence',
      'relations = conditionConditioned',
      'relations = causality',
      'substantiality.present = inCategoricalJudgment',
      'substantiality.present = inFormOfConcept',
      'connectednessOfCausality.present = inHypotheticalJudgment',
      'relations = momentsOfOneIdentity',
      'relations.notOpposed = asSingular',
      'relations.notOpposed = asParticular',
      'relations.notOpposed = asUniversal',
      'relations = momentsInGeneral',
      'hypotheticalJudgment.shape = moreProposition',
      'hypotheticalJudgment = indeterminateForm',
      'determinationOfContent.notConforms = toRelation(subject, predicate)',
      'being = unity(itself, other)',
      'being = universality',
      'being = particular',
      'being = determinateBeing',
      'being.notRefers = merelyToItself',
      'particularity.notPosited = asSimpleAbstract',
      'throughImmediacy.momentsOfParticularity = differentiated',
      'throughUnity.particularity = totality',
      'posited = universalityAsConcreteIdentity',
      'concreteIdentity = ofConcept',
      'determinations.noSubsistence = ofOwn',
      'determinations = particularitiesPosited',
      'soItIs = disjunctiveJudgment',
    ],
    predicates: [
      { name: 'relationsOfReflection', args: ['hypotheticalJudgment.determined'] },
      { name: 'momentsOfOneIdentity', args: ['relations'] },
      { name: 'indeterminateForm', args: ['hypotheticalJudgment'] },
      { name: 'concreteIdentity', args: ['ofConcept'] },
      { name: 'disjunctiveJudgment', args: ['soItIs'] },
    ],
    relations: [
      { predicate: 'determined', from: 'hypotheticalJudgment', to: 'asRelationsOfReflection' },
      { predicate: 'is', from: 'relations', to: 'momentsOfOneIdentity' },
      { predicate: 'is', from: 'being', to: 'unity' },
      { predicate: 'is', from: 'being', to: 'universality' },
      { predicate: 'is', from: 'being', to: 'particular' },
      { predicate: 'is', from: 'posited', to: 'universalityAsConcreteIdentity' },
    ],
    candidateSummary: 'The hypothetical judgment can be more closely determined in terms of the relations of reflection as a relation of ground and consequence, condition and conditioned, causality etc. Just as substantiality is present in the categorical judgment in the form of its concept, so is the connectedness of causality in the hypothetical judgment. This and the other relations all recur in it, but they are there essentially only as moments of one and the same identity. However, in it they are as yet not opposed as singular or particular and universal according to the determinations of the concept, but are only as moments in general at first. The hypothetical judgment, therefore, has a shape which is more that of a proposition; just as the particular judgment is of indeterminate content, so is the hypothetical of indeterminate form, for the determination of its content does not conform to the relation of subject and predicate. Yet the being, since it is the being of the other, is for that very reason in itself the unity of itself and the other, and therefore universality; by the same token it is in fact only a particular, for it is a determinate being and does not refer in its determinateness merely to itself. But it is not the simple, abstract particularity that is posited; on the contrary, through the immediacy which the determinacies possess, the moments of particularity are differentiated; at the same time, through the unity of these moments as constituted by their connection, the particularity is also their totality. In truth, therefore, what is posited in this judgment is universality as the concrete identity of the concept whose determinations do not have any subsistence of their own but are only particularities posited in that identity. So it is the disjunctive judgment.',
    provenance: {
      sourceChunk: 'nec-6-hypothetical-relations',
      sourceOp: 'nec-op-6-hypothetical-relations',
    },
};

// ============================================================================
// C. THE DISJUNCTIVE JUDGMENT
// ============================================================================

export const necOp7DisjunctiveEitherOr: LogicalOperation = {
  id: 'nec-op-7-disjunctive-either-or',
  chunkId: 'nec-7-disjunctive-either-or',
    label: 'Disjunctive Judgment: "A is either B or C"; Necessity of Concept',
    clauses: [
      'inCategoricalJudgment.concept = objectiveUniversality',
      'inCategoricalJudgment.concept = externalSingularity',
      'inHypothetical.concept.manifests = negativeIdentity',
      'throughIdentity.obtainDeterminateness = nowPosited',
      'disjunctiveJudgment = objectiveUniversality',
      'disjunctiveJudgment.posited = inUnionWithForm',
      'disjunctiveJudgment.contains1 = concreteUniversality',
      'disjunctiveJudgment.contains1 = genusInSimpleForm',
      'disjunctiveJudgment.contains1 = asSubject',
      'disjunctiveJudgment.contains2 = sameUniversality',
      'disjunctiveJudgment.contains2 = asTotality',
      'disjunctiveJudgment.contains2 = asDifferentiatedDeterminations',
      'disjunctiveJudgment = "A is eitherB orC"',
      'disjunctiveJudgment = necessityOfConcept',
      'selfIdentity = ofTwoExtremes',
      'selfIdentity = sameExtent',
      'selfIdentity = sameContent',
      'selfIdentity = sameUniversality',
      'extremes.differentiated = accordingToForm',
      'differentiation = conceptualDetermination',
      'determination = mereForm',
      'identicalObjectiveUniversality.appears = reflectedIntoItself',
      'content.hasDeterminateness = ofForm',
      'content.once = simpleDeterminationOfGenus',
      'content.again = determinatenessDeveloped',
      'content = particularityOfSpecies',
      'content = totality',
      'content = universalityOfGenus',
      'particularity.constitutes = predicate',
      'particularity.contains = wholeUniversalSphere',
      'particularity.contains = articulationOfParticularity',
      'particularity = greaterUniversal',
    ],
    predicates: [
      { name: 'objectiveUniversality', args: ['inCategoricalJudgment.concept'] },
      { name: 'negativeIdentity', args: ['inHypothetical.concept.manifests'] },
      { name: 'necessityOfConcept', args: ['disjunctiveJudgment'] },
      { name: 'conceptualDetermination', args: ['differentiation'] },
      { name: 'greaterUniversal', args: ['particularity'] },
    ],
    relations: [
      { predicate: 'is', from: 'disjunctiveJudgment', to: 'objectiveUniversality' },
      { predicate: 'contains', from: 'disjunctiveJudgment', to: 'concreteUniversality' },
      { predicate: 'contains', from: 'disjunctiveJudgment', to: 'sameUniversality' },
      { predicate: 'is', from: 'disjunctiveJudgment', to: '"A is eitherB orC"' },
      { predicate: 'is', from: 'disjunctiveJudgment', to: 'necessityOfConcept' },
      { predicate: 'constitutes', from: 'particularity', to: 'predicate' },
    ],
    candidateSummary: 'In the categorical judgment, the concept is objective universality and an external singularity. In the hypothetical, the concept manifests its presence in this externality, in its negative identity. Through this identity, the objective universality and the external singularity obtain the determinateness, now posited in the disjunctive judgment, which in the hypothetical they possess immediately. Hence the disjunctive judgment is objective universality at the same time posited in union with the form. It thus contains, first, the concrete universality or the genus in simple form, as the subject; second, the same universality but as the totality of its differentiated determinations. "A is either B or C." This is the necessity of the concept in which, first, the self-identity of the two extremes is of the same extent, content, and universality. Second, they are differentiated according to the form of conceptual determination, but, because of that identity, this determination is a mere form. Third, the identical objective universality appears for that reason reflected into itself as against the non-essential form, as a content which however has the determinateness of form in it, once as the simple determination of genus; then again, as this determinateness developed in its difference, and in this way it is the particularity of the species and their totality, the universality of the genus. The particularity constitutes in its development the predicate, because, in containing the whole universal sphere of the subject, and in containing it, however, also in the articulation of particularity, it is to that extent the greater universal.',
    provenance: {
      sourceChunk: 'nec-7-disjunctive-either-or',
      sourceOp: 'nec-op-7-disjunctive-either-or',
    },
};

export const necOp8DisjunctivePositiveNegative: LogicalOperation = {
  id: 'nec-op-8-disjunctive-positive-negative',
    chunkId: 'nec-8-disjunctive-positive-negative',
    label: 'Disjunctive: Positive and Negative Identity; Unity of Determinate Particulars',
    clauses: [
      'genus.constitutes = substantialUniversality',
      'genus.constitutes = ofSpecies',
      'subject = B asWellAsC',
      '"asWellAs" = positiveIdentity',
      '"asWellAs" = particularWithUniversal',
      'objectiveUniversal.maintains = inParticularity',
      'species.mutuallyExclude = oneAnother',
      '"A is eitherB orC"',
      '"eitherOr" = negativeConnection',
      'species = specificDifference',
      'species = ofUniversalSphere',
      'inNegativeConnection = justAsIdentical',
      'inNegativeConnection = asInPositive',
      'genus = unity',
      'genus = unityOfDeterminateParticulars',
      'if(genus = abstractUniversality)',
      'species = diverse',
      'species = mutuallyIndifferent',
      'universality != external',
      'universality != throughComparison',
      'universality != throughAbstraction',
      'universality = immanentToGenus',
      'universality = concrete',
    ],
    predicates: [
      { name: 'substantialUniversality', args: ['genus.constitutes', 'ofSpecies'] },
      { name: 'positiveIdentity', args: ['"asWellAs"'] },
      { name: 'mutuallyExclude', args: ['species', 'oneAnother'] },
      { name: 'negativeConnection', args: ['"eitherOr"'] },
      { name: 'unityOfDeterminateParticulars', args: ['genus'] },
      { name: 'immanentToGenus', args: ['universality'] },
      { name: 'concrete', args: ['universality'] },
    ],
    relations: [
      { predicate: 'constitutes', from: 'genus', to: 'substantialUniversality' },
      { predicate: 'is', from: 'subject', to: 'B asWellAsC' },
      { predicate: 'maintains', from: 'objectiveUniversal', to: 'inParticularity' },
      { predicate: 'mutuallyExclude', from: 'species', to: 'oneAnother' },
      { predicate: 'is', from: 'genus', to: 'unity' },
    ],
    candidateSummary: 'Upon closer consideration of this particularization, it is the genus that constitutes first of all the substantial universality of the species; the subject is thus B as well as C; this "as well as" indicates the positive identity of the particular with the universal; this objective universal maintains itself fully in its particularity. Secondly, the species mutually exclude one another; "A is either B or C"; for they are the specific difference of the universal sphere. This "either or" is their negative connection. In this negative connection they are just as identical as in the positive; the genus is their unity as a unity of determinate particulars. If the genus were an abstract universality, as in the judgments of existence, then the species would also have to be taken as diverse and mutually indifferent; this universality, however, is not the external one that arises only through comparison and abstraction but is, on the contrary, the universality which is immanent to the genus and concrete.',
    provenance: {
      sourceChunk: 'nec-8-disjunctive-positive-negative',
      sourceOp: 'nec-op-8-disjunctive-positive-negative',
    },
};

export const necOp9EmpiricalWithoutNecessity: LogicalOperation = {
  id: 'nec-op-9-empirical-without-necessity',
    chunkId: 'nec-9-empirical-without-necessity',
    label: 'Empirical Disjunctive Without Necessity; Negative Unity',
    clauses: [
      'empiricalDisjunctive = withoutNecessity',
      'empiricalDisjunctive = "A is eitherB orC orD, etc"',
      'species = foundBeforehand',
      'species = B, C, D, etc',
      'noQuestion = ofEitherOr',
      'completeness = subjective',
      'oneSpecies.excludes = other',
      '"eitherOr" = excludesEveryOtherSpecies',
      '"eitherOr" = excludesEntireSphere',
      'totality.hasNecessity = inNegativeUnity',
      'negativeUnity = objectiveUniversal',
      'negativeUnity.dissolved = singularity',
      'negativeUnity.possesses = immanentSimplePrinciple',
      'simplePrinciple = ofDifferentiation',
      'species.determined = byPrinciple',
      'species.connected = byPrinciple',
      'empiricalSpecies.differences = inAccidentality',
      'accidentality = externalPrinciple',
      'accidentality != principle',
      'accidentality != immanentDeterminateness',
      'species.notReciprocallyConnected = accordingToDeterminateness',
    ],
    predicates: [
      { name: 'withoutNecessity', args: ['empiricalDisjunctive'] },
      { name: 'foundBeforehand', args: ['species'] },
      { name: 'subjective', args: ['completeness'] },
      { name: 'negativeUnity', args: ['objectiveUniversal'] },
      { name: 'immanentSimplePrinciple', args: ['negativeUnity.possesses'] },
      { name: 'externalPrinciple', args: ['accidentality'] },
    ],
    relations: [
      { predicate: 'is', from: 'empiricalDisjunctive', to: 'withoutNecessity' },
      { predicate: 'hasNecessity', from: 'totality', to: 'inNegativeUnity' },
      { predicate: 'dissolved', from: 'negativeUnity', to: 'singularity' },
      { predicate: 'possesses', from: 'negativeUnity', to: 'immanentSimplePrinciple' },
      { predicate: 'notReciprocallyConnected', from: 'species', to: 'accordingToDeterminateness' },
    ],
    candidateSummary: 'An empirical disjunctive judgment is without necessity; A is either B or C or D, etc., because the species B, C, D, etc., are found beforehand; strictly speaking, therefore, there is no question here of an "either or," for the completeness of these species is only a subjective one; of course, one species excludes the other, but the "either or" excludes every other species and excludes within itself an entire sphere. This totality has its necessity in the negative unity of the objective universal which has dissolved singularity within itself and possesses, immanent in it, the simple principle of differentiation by which the species are determined and connected. The empirical species, on the contrary, have their differences in some accidentality or other which is a principle external to them and is not, therefore, their principle, and consequently also not the immanent determinateness of the genus; for this reason, they are also not reciprocally connected according to their determinateness.',
    provenance: {
      sourceChunk: 'nec-9-empirical-without-necessity',
      sourceOp: 'nec-op-9-empirical-without-necessity',
    },
};

export const necOp10ContraryContradictory: LogicalOperation = {
  id: 'nec-op-10-contrary-contradictory',
    chunkId: 'nec-10-contrary-contradictory',
    label: 'Contrary and Contradictory Concepts; Unity as Truth',
    clauses: [
      'contraryConcepts.findPlace = inDisjunctiveJudgment',
      'contradictoryConcepts.findPlace = inDisjunctiveJudgment',
      'disjunctiveJudgment = essentialDifference',
      'contraryContradictory.findTruth = differentiated',
      'species.contrary = merelyDiverse',
      'species.contrary = immediateExistence',
      'species.contrary = subsistingInAndForThemselves',
      'species.contradictory = excludeOneAnother',
      'eachDetermination = oneSided',
      'eachDetermination = voidOfTruth',
      'inEitherOr.unityPosited = asTruth',
      'independentSubsistence = principle',
      'independentSubsistence = ofNegativeUnity',
      'species.mutuallyExclude = byPrinciple',
    ],
    predicates: [
      { name: 'essentialDifference', args: ['disjunctiveJudgment'] },
      { name: 'merelyDiverse', args: ['species.contrary'] },
      { name: 'excludeOneAnother', args: ['species.contradictory'] },
      { name: 'oneSided', args: ['eachDetermination'] },
      { name: 'voidOfTruth', args: ['eachDetermination'] },
      { name: 'principle', args: ['independentSubsistence', 'ofNegativeUnity'] },
    ],
    relations: [
      { predicate: 'findPlace', from: 'contraryConcepts', to: 'inDisjunctiveJudgment' },
      { predicate: 'findPlace', from: 'contradictoryConcepts', to: 'inDisjunctiveJudgment' },
      { predicate: 'is', from: 'disjunctiveJudgment', to: 'essentialDifference' },
      { predicate: 'findTruth', from: 'contraryContradictory', to: 'differentiated' },
      { predicate: 'mutuallyExclude', from: 'species', to: 'byPrinciple' },
    ],
    candidateSummary: 'Here is where the so-called contrary and contradictory concepts should find their proper place, for the disjunctive judgment is where the essential difference of the concept is posited; but here they also equally find their truth, namely that contrariness and contradictoriness are themselves differentiated both as contraries and as contradictory. Species are contrary inasmuch as they are merely diverse, that is to say, inasmuch as they possess an immediate existence as subsisting in and for themselves by virtue of the genus which is their nature. They are contradictory, inasmuch as they exclude one another. But each of these determinations is by itself one-sided and void of truth. In the "either or" of the disjunctive judgment, their unity is posited as their truth, which is that the independent subsistence of the species as concrete universality is itself also the principle of the negative unity by which they mutually exclude one another.',
    provenance: {
      sourceChunk: 'nec-10-contrary-contradictory',
      sourceOp: 'nec-op-10-contrary-contradictory',
    },
};

export const necOp11ProximateGenus: LogicalOperation = {
  id: 'nec-op-11-proximate-genus',
    chunkId: 'nec-11-proximate-genus',
    label: 'Proximate Genus; Concrete Essentially Determined Universality',
    clauses: [
      'throughIdentity.genus = determined',
      'genus = proximateGenus',
      'proximateGenus.indicates = quantitativeDifference',
      'proximateGenus.indicates = moreOrLessDeterminations',
      'whichUniversal = trulyProximateGenus',
      'whichUniversal = contingent',
      'if(genus = abstraction)',
      'genus.cannotForm = disjunctiveJudgment',
      'genus = contingentCompleteness',
      'genus.notDisplayed = inSpecies',
      'genus.notDisplayed = accordingToDeterminateness',
      'species = contingentCompleteness',
      'inCategoricalJudgment.genus = abstractForm',
      'inCategoricalJudgment.genus != necessarilyProximate',
      'inCategoricalJudgment.genus = external',
      'when(genus = concrete)',
      'when(genus = essentiallyDetermined)',
      'genus = simpleDeterminateness',
      'genus = unityOfMoments',
      'moments.sublated = inSimplicity',
      'moments.haveRealDifference = inSpecies',
      'genus = proximateGenus',
      'species.possesses = specificDifference',
      'specificDifference = inEssentialDeterminateness',
      'species.haveDetermination = differentiating',
      'differentiating = inNatureOfGenus',
    ],
    predicates: [
      { name: 'proximateGenus', args: ['genus'] },
      { name: 'quantitativeDifference', args: ['proximateGenus.indicates'] },
      { name: 'contingentCompleteness', args: ['genus'] },
      { name: 'concrete', args: ['genus'] },
      { name: 'essentiallyDetermined', args: ['genus'] },
      { name: 'unityOfMoments', args: ['genus'] },
    ],
    relations: [
      { predicate: 'determined', from: 'throughIdentity', to: 'genus' },
      { predicate: 'is', from: 'genus', to: 'proximateGenus' },
      { predicate: 'cannotForm', from: 'genus', to: 'disjunctiveJudgment' },
      { predicate: 'is', from: 'genus', to: 'simpleDeterminateness' },
      { predicate: 'is', from: 'genus', to: 'unityOfMoments' },
    ],
    candidateSummary: 'Through the identity just demonstrated of subject and predicate in accordance with the negative unity, the genus is determined in the disjunctive judgment as the proximate genus. This expression indicates at first the mere quantitative difference of the more or less determinations which a universal contains as contrasted to a particularity coming under it. On this account, which is the truly proximate genus remains contingent. But then, if the genus is taken as a universal arrived at by the mere abstraction of determinations, it cannot strictly speaking form a disjunctive judgment; for it is contingent whether, as it were, there is still left in it the determinateness that constitutes the principle of the "either or"; the genus would not be displayed in the species according to its determinateness, and these would only be capable of contingent completeness. In the categorical judgment, the genus stands at first over against the subject only in this abstract form, is not, therefore, necessarily its proximate genus and, to this extent, is external to it. But when the genus is a concrete, essentially determined universality, then, as simple determinateness, it is the unity of the moments of the concept; moments that, only sublated in that simplicity, have their real difference in the species. Hence the genus is the proximate genus of a species, for the latter possesses its specific difference in the essential determinateness of the genus, and the species have as such the determination differentiating them in the nature of the genus.',
    provenance: {
      sourceChunk: 'nec-11-proximate-genus',
      sourceOp: 'nec-op-11-proximate-genus',
    },
};

export const necOp12IdentityDeterminateness: LogicalOperation = {
  id: 'nec-op-12-identity-determinateness',
    chunkId: 'nec-12-identity-determinateness',
    label: 'Identity from Aspect of Determinateness; Difference of Concept',
    clauses: [
      'identity = fromAspectOfDeterminateness',
      'aspect.posited = byHypotheticalJudgment',
      'necessity = identity(immediate, diverseThings)',
      'necessity = negativeUnity',
      'negativeUnity.separates = subjectPredicate',
      'negativeUnity.posited = asDifferentiated',
      'inSubject = simpleDeterminateness',
      'inPredicate = totality',
      'parting = differenceOfConcept',
      'totalityOfSpecies = thisDifference',
      'reciprocalDetermination = ofDisjunctiveTerms',
      'reciprocalDetermination.given = hereby',
      'reciprocalDetermination.reduces = toDifferenceOfConcept',
      'concept.alone = disjoinsItself',
      'concept.manifests = negativeUnity',
    ],
    predicates: [
      { name: 'fromAspectOfDeterminateness', args: ['identity'] },
      { name: 'negativeUnity', args: ['necessity'] },
      { name: 'differenceOfConcept', args: ['parting'] },
      { name: 'disjoinsItself', args: ['concept.alone'] },
    ],
    relations: [
      { predicate: 'is', from: 'identity', to: 'fromAspectOfDeterminateness' },
      { predicate: 'is', from: 'necessity', to: 'negativeUnity' },
      { predicate: 'separates', from: 'negativeUnity', to: 'subjectPredicate' },
      { predicate: 'is', from: 'parting', to: 'differenceOfConcept' },
      { predicate: 'reduces', from: 'reciprocalDetermination', to: 'toDifferenceOfConcept' },
    ],
    candidateSummary: 'What we have just considered constitutes the identity of subject and predicate from the aspect of determinateness in general. This is an aspect that was posited by the hypothetical judgment, the necessity of which is an identity of immediate and diverse things and is, therefore, essentially a negative unity. It is this negative unity that in principle separates subject and predicate but is now posited as itself differentiated – in the subject, as simple determinateness; in the predicate, as totality. That parting of subject and predicate is the difference of the concept; the totality of the species in the predicate can then be none other than this difference. The reciprocal determination of the disjunctive terms is therefore hereby given. It reduces to the difference of the concept, for it is the concept alone that disjoins itself and manifests in its determination its negative unity.',
    provenance: {
      sourceChunk: 'nec-12-identity-determinateness',
      sourceOp: 'nec-op-12-identity-determinateness',
    },
};

export const necOp13ProgressiveDetermination: LogicalOperation = {
  id: 'nec-op-13-progressive-determination',
    chunkId: 'nec-13-progressive-determination',
    label: 'Concept\'s Own Progressive Determination; Disjunction',
    clauses: [
      'species = simpleConceptualDeterminateness',
      'species.notAccording = toShape',
      'species.notAccording = proceedingFromIdea',
      'species.notAccording = selfSubsistentReality',
      'reality.dropped = inSimplePrinciple',
      'essentialDifferentiation = momentOfConcept',
      'concept.ownProgressiveDetermination = positsDisjunction',
      'concept.determined = inAndForItself',
      'concept.differentiated = intoDeterminateConcepts',
      'concept = universal',
      'concept = positiveTotality',
      'concept = negativeTotality',
      'concept = ofParticulars',
      'concept.immediately = oneOfDisjunctiveMembers',
      'otherMember = universalityResolved',
      'otherMember = intoParticularity',
      'otherMember = determinatenessOfConcept',
      'universality.displays = asTotality',
      'if(disjunction.notAttained = thisForm)',
      'disjunction.notRisen = toDeterminatenessOfConcept',
      'disjunction.notProceeded = fromConcept',
    ],
    predicates: [
      { name: 'simpleConceptualDeterminateness', args: ['species'] },
      { name: 'momentOfConcept', args: ['essentialDifferentiation'] },
      { name: 'positsDisjunction', args: ['concept.ownProgressiveDetermination'] },
      { name: 'oneOfDisjunctiveMembers', args: ['concept.immediately'] },
      { name: 'universalityResolved', args: ['otherMember', 'intoParticularity'] },
    ],
    relations: [
      { predicate: 'is', from: 'species', to: 'simpleConceptualDeterminateness' },
      { predicate: 'is', from: 'essentialDifferentiation', to: 'momentOfConcept' },
      { predicate: 'posits', from: 'concept.ownProgressiveDetermination', to: 'disjunction' },
      { predicate: 'is', from: 'concept', to: 'universal' },
      { predicate: 'is', from: 'concept', to: 'oneOfDisjunctiveMembers' },
    ],
    candidateSummary: 'Of course, the species comes up for consideration here only under the aspect of its simple conceptual determinateness, not according to the shape in which, proceeding from the idea, it steps into a further self-subsistent reality. This reality is of course dropped in the simple principle of the genus; but the essential differentiation must be a moment of the concept. In the judgment here considered, it is really now the concept\'s own progressive determination that itself posits its disjunction, just as was the case for the concept itself, as we saw when it was determined in and for itself and was differentiated into determinate concepts. Now because the concept is the universal, the positive as well as the negative totality of the particulars, for that reason it is immediately itself also one of its disjunctive members; the other member, however, is this universality resolved into its particularity, or the determinateness of the concept as determinateness, in which the very universality displays itself as totality. If the disjunction of a genus into species has not yet attained this form, this is proof that the disjunction has not risen to the determinateness of the concept and has not proceeded from it.',
    provenance: {
      sourceChunk: 'nec-13-progressive-determination',
      sourceOp: 'nec-op-13-progressive-determination',
    },
};

export const necOp14ExampleColor: LogicalOperation = {
  id: 'nec-op-14-example-color',
    chunkId: 'nec-14-example-color',
    label: 'Example: Color Disjunction; Concrete Unity of Light and Darkness',
    clauses: [
      'example = "color is either violet, indigo, blue, green, yellow, orange, or red"',
      'example = confusion',
      'example = impurity',
      'example = barbarism',
      'if(color = concreteUnity(light, darkness))',
      'genus.hasDeterminateness = constitutingPrinciple',
      'genus.hasDeterminateness = ofParticularization',
      'oneSpecies = utterlySimpleColor',
      'oneSpecies.holds = oppositionInBalance',
      'oneSpecies.contained = inColorIntensity',
      'oneSpecies.negated = inColorIntensity',
      'relation = opposition(light, darkness)',
      'relation.takesPlace = overAgainstIt',
      'relation = naturalPhenomenon',
      'indifferentNeutrality = added',
      'takingMixtures = inconsiderateProcedure',
      'takingShades = inconsiderateProcedure',
      'inconsiderateProcedure.shows = tooLittleReflection',
    ],
    predicates: [
      { name: 'concreteUnity', args: ['color', 'light', 'darkness'] },
      { name: 'constitutingPrinciple', args: ['genus.hasDeterminateness', 'ofParticularization'] },
      { name: 'oppositionInBalance', args: ['oneSpecies.holds'] },
      { name: 'inconsiderateProcedure', args: ['takingMixtures'] },
    ],
    relations: [
      { predicate: 'is', from: 'example', to: 'confusion' },
      { predicate: 'is', from: 'example', to: 'impurity' },
      { predicate: 'is', from: 'example', to: 'barbarism' },
      { predicate: 'is', from: 'color', to: 'concreteUnity' },
      { predicate: 'has', from: 'genus', to: 'determinateness' },
    ],
    candidateSummary: 'Color is either violet, indigo, blue, green, yellow, orange, or red; even empirically, the confusion and impurity of such a disjunction are at once apparent; it is a barbarism even from this standpoint. If color is conceived as the concrete unity of light and darkness, then this genus has within it the determinateness that constitutes the principle of its particularization into species. Of these, however, one must be the utterly simple color that holds the opposition in balance, contained and negated in the color\'s intensity; the relation of the opposition of light and darkness must then take its place over against it, and, since this relation is a natural phenomenon, the indifferent neutrality of the opposition must be further added to it. Taking for genus such mixtures as violet, and orange, or shades of difference like indigo blue and light blue, betrays a totally inconsiderate procedure that shows too little reflection even for empiricism.',
    provenance: {
      sourceChunk: 'nec-14-example-color',
      sourceOp: 'nec-op-14-example-color',
    },
};

export const necOp15TransitionConcept: LogicalOperation = {
  id: 'nec-op-15-transition-concept',
    chunkId: 'nec-15-transition-concept',
    label: 'Judgment Itself Disjoined; Transition to Judgment of Concept',
    clauses: [
      'disjunctiveJudgment.has = membersInPredicate',
      'judgment.itself = disjoined',
      'subject.predicate = membersOfDisjunction',
      'subject.predicate = momentsOfConcept',
      'subject.predicate.posited = inDeterminateness',
      'subject.predicate = identical',
      'identical1 = objectiveUniversality',
      'objectiveUniversality.inSubject = simpleGenus',
      'objectiveUniversality.inPredicate = universalSphere',
      'objectiveUniversality.inPredicate = totalityOfMoments',
      'identical2 = negativeUnity',
      'negativeUnity = developedConnectedness',
      'negativeUnity = ofNecessity',
      'simpleDeterminateness.fallenApart = intoDifference',
      'difference = ofSpecies',
      'species.inDifference = haveEssentialConnection',
      'species.inDifference = haveSelfIdentity',
      'unity = copula',
      'unity = conceptItself',
      'unity = conceptAsPosited',
      'judgmentOfNecessity.risen = toJudgmentOfConcept',
    ],
    predicates: [
      { name: 'disjoined', args: ['judgment.itself'] },
      { name: 'momentsOfConcept', args: ['subject.predicate'] },
      { name: 'developedConnectedness', args: ['negativeUnity'] },
      { name: 'conceptItself', args: ['unity'] },
      { name: 'conceptAsPosited', args: ['unity'] },
      { name: 'judgmentOfConcept', args: ['judgmentOfNecessity.risen'] },
    ],
    relations: [
      { predicate: 'is', from: 'judgment.itself', to: 'disjoined' },
      { predicate: 'are', from: 'subject.predicate', to: 'momentsOfConcept' },
      { predicate: 'are', from: 'subject.predicate', to: 'identical' },
      { predicate: 'is', from: 'unity', to: 'copula' },
      { predicate: 'is', from: 'unity', to: 'conceptItself' },
      { predicate: 'risen', from: 'judgmentOfNecessity', to: 'toJudgmentOfConcept' },
    ],
    candidateSummary: 'In the first instance, the disjunctive judgment has the members of the disjunction in the predicate. But the judgment is itself equally disjoined; its subject and predicate are the members of the disjunction; they are the moments of the concept posited in their determinateness but at the same time as identical; identical, (a) in the objective universality which is in the subject as the simple genus, and in the predicate as the universal sphere and totality of the moments of the concept; and (b) in the negative unity, the developed connectedness of necessity, in accordance with which the simple determinateness in the subject has fallen apart into the difference of the species and these, in this very difference, have their essential connection and self-identity. This unity, the copula of this judgment in which the extremes have come together through their identity, is thus the concept itself, indeed the concept as posited; the mere judgment of necessity has thereby risen to the judgment of the concept.',
    provenance: {
      sourceChunk: 'nec-15-transition-concept',
      sourceOp: 'nec-op-15-transition-concept',
    },
};

export const judgmentOfNecessityOperations: LogicalOperation[] = [
  necOp1IntroductionObjective,
  necOp2CategoricalGenusDivides,
  necOp3CategoricalDistinguished,
  necOp4CategoricalPassesHypothetical,
  necOp5HypotheticalIfThen,
  necOp6HypotheticalRelations,
  necOp7DisjunctiveEitherOr,
  necOp8DisjunctivePositiveNegative,
  necOp9EmpiricalWithoutNecessity,
  necOp10ContraryContradictory,
  necOp11ProximateGenus,
  necOp12IdentityDeterminateness,
  necOp13ProgressiveDetermination,
  necOp14ExampleColor,
  necOp15TransitionConcept,
];

