/**
 * Logical Operations: Being-for-itself
 *
 * Being-for-itself - infinity that has sunk into simple being.
 * This is the CPU's movement from existence to being-for-itself,
 * where the subject begins to emerge.
 *
 * Dialectical Movement:
 * - Being-for-itself as such: general concept and representation
 * - Existence and being-for-itself: infinity sunk into simple being
 * - Being-for-one: idealization and unity
 * - The one: simple unity and abstract limit
 */

import type { LogicalOperation } from '../../../../types';

// ============================================================================
// BEING-FOR-ITSELF
// ============================================================================

export const bfSelfOp1GeneralConcept: LogicalOperation = {
  id: 'bf-self-op-1-general-concept',
  chunkId: 'being-for-self-a',
  label: 'A. BEING-FOR-ITSELF AS SUCH — general concept and representation',
  clauses: [
    'theGeneralConcept = ofBeingForItself',
    'theGeneralConcept = hasComeToLight',
    'theJustification = forUsing',
    'theJustification = theExpression',
    'theJustification = beingForItself',
    'theJustification = forThatConcept',
    'theJustification = wouldDepend',
    'theJustification = onShowing',
    'theJustification = thatTheRepresentation',
    'theJustification = associatedWithTheExpression',
    'theJustification = correspondsToTheConcept',
    'something = isForItself',
    'inasmuch = asItSublatesOtherness',
    'inasmuch = sublatesItsConnection',
    'inasmuch = andCommunityWithOther',
    'inasmuch = hasRejectedThem',
    'inasmuch = byAbstractingFromThem',
    'theOther = isInIt',
    'theOther = onlyAsSomethingSublated',
    'theOther = asItsMoment',
    'beingForItself = consistsIn',
    'beingForItself = havingThusTranscended',
    'beingForItself = limitation',
    'beingForItself = itsOtherness',
    'beingForItself = consistsIn',
    'beingForItself = being',
    'beingForItself = asThisNegation',
    'beingForItself = theInfiniteTurningBack',
    'beingForItself = intoItself',
    'consciousness = containsDetermination',
    'consciousness = ofBeingForItself',
    'content = ofObject',
    'content = isIdealization',
    'beingForItself = isPolemical',
    'beingForItself = negativeRelating',
    'beingForItself = toLimitingOther',
    'selfConsciousness = isBeingForItself',
    'selfConsciousness = broughtToCompletion',
    'selfConsciousness = andPosited',
    'it = isTheNearestExample',
    'it = ofThePresence',
    'it = ofInfinity',
  ],
  predicates: [
    { name: 'beingForItself', args: ['something'] },
  ],
  relations: [
    { predicate: 'is', from: 'something', to: 'beingForItself' },
  ],
  candidateSummary: 'The general concept of being-for-itself has come to light. The justification for using the expression "being-for-itself" for that concept would depend on showing that the representation associated with the expression corresponds to the concept. Something is for itself inasmuch as it sublates otherness, sublates its connection and community with other, has rejected them by abstracting from them. The other is in it only as something sublated, as its moment; being-for-itself consists in having thus transcended limitation, its otherness; it consists in being, as this negation, the infinite turning back into itself. Consciousness contains determination of being-for-itself; content of object is idealization. Being-for-itself is polemical, negative relating to limiting other. Self-consciousness is being-for-itself brought to completion and posited; it is the nearest example of the presence of infinity.',
  provenance: {
    sourceChunk: 'being-for-self-a',
    sourceOp: 'bf-self-op-1-general-concept',
  },
};

export const bfSelfOp2ExistenceAndBeingForItself: LogicalOperation = {
  id: 'bf-self-op-2-existence-and-being-for-itself',
  chunkId: 'being-for-self-a-1',
  label: 'a. Existence and being-for-itself — infinity sunk into simple being',
  clauses: [
    'as = alreadyMentioned',
    'beingForItself = isInfinity',
    'beingForItself = thatHasSunk',
    'beingForItself = intoSimpleBeing',
    'it = isExistence',
    'in = soFarAs',
    'in = theNowPositedForm',
    'in = ofTheImmediacy',
    'in = ofBeing',
    'theNegativeNature = ofInfinity',
    'theNegativeNature = whichIs',
    'theNegativeNature = theNegationOfNegation',
    'theNegativeNature = isOnly',
    'theNegativeNature = asNegationInGeneral',
    'theNegativeNature = asInfiniteQualitativeDeterminateness',
    'but = inSuchADeterminateness',
    'wherein = itIsExistence',
    'being = isAtOnce',
    'being = alsoDistinguished',
    'being = fromThisVeryBeingForItself',
    'being = whichIsSuch',
    'being = onlyAsInfiniteQualitativeDeterminateness',
    'nevertheless = existence',
    'nevertheless = isAtTheSameTime',
    'nevertheless = aMoment',
    'nevertheless = ofBeingForItself',
    'for = theLatter',
    'for = certainlyContains',
    'for = beingAffectedByNegation',
    'so = theDeterminateness',
    'so = whichInExistence',
    'so = asSuch',
    'so = isAnOther',
    'so = andABeingForOther',
    'so = isBentBack',
    'so = intoTheInfiniteUnity',
    'so = ofBeingForItself',
    'and = theMoment',
    'and = ofExistence',
    'and = isPresent',
    'and = inTheBeingForItself',
    'and = asBeingForOne',
  ],
  predicates: [
    { name: 'infinitySunkIntoSimpleBeing', args: ['beingForItself'] },
  ],
  relations: [
    { predicate: 'is', from: 'beingForItself', to: 'infinitySunkIntoSimpleBeing' },
  ],
  candidateSummary: 'As already mentioned, being-for-itself is infinity that has sunk into simple being; it is existence in so far as in the now posited form of the immediacy of being the negative nature of infinity, which is the negation of negation, is only as negation in general, as infinite qualitative determinateness. But in such a determinateness, wherein it is existence, being is at once also distinguished from this very being-for-itself which is such only as infinite qualitative determinateness; nevertheless, existence is at the same time a moment of being-for-itself, for the latter certainly contains being affected by negation. So the determinateness which in existence as such is an other, and a being-for-other, is bent back into the infinite unity of being-for-itself, and the moment of existence is present in the being-for-itself as being-for-one.',
  provenance: {
    sourceChunk: 'being-for-self-a-1',
    sourceOp: 'bf-self-op-2-existence-and-being-for-itself',
  },
};

export const bfSelfOp3BeingForOne: LogicalOperation = {
  id: 'bf-self-op-3-being-for-one',
  chunkId: 'being-for-self-b',
  label: 'b. Being-for-one — idealization and unity',
  clauses: [
    'thisMoment = givesExpression',
    'thisMoment = toHow',
    'thisMoment = theFinite',
    'thisMoment = isInItsUnity',
    'thisMoment = withTheInfinite',
    'thisMoment = orAsAnIdealization',
    'beingForItself = doesNotHave',
    'beingForItself = negationInIt',
    'beingForItself = asADeterminateness',
    'beingForItself = orLimit',
    'and = consequently',
    'and = alsoNot',
    'and = asReference',
    'and = toAnExistence',
    'and = otherThanIt',
    'although = thisMoment',
    'although = isNow',
    'although = beingDesignated',
    'although = asBeingForOne',
    'there = isYetNothing',
    'there = atHand',
    'there = forWhich',
    'there = itWouldBe',
    'there = isNot',
    'there = theOne',
    'there = ofWhich',
    'there = itWouldBe',
    'there = theMoment',
    'there = isOnly',
    'there = oneBeingForAnother',
    'and = sinceThis',
    'and = isOnly',
    'and = oneBeingForAnother',
    'and = itIsAlso',
    'and = onlyBeingForOne',
    'there = isOnly',
    'there = theOneIdeality',
    'beingForOne = andBeingForItself',
    'beingForOne = doNotTherefore',
    'beingForOne = constituteTwoGenuine',
    'beingForOne = determinacies',
    'beingForItself = refersItself',
    'beingForItself = toItself',
    'beingForItself = asSublatedOther',
    'beingForItself = isForOne',
    'in = itsOther',
    'it = refersItself',
    'it = onlyToItself',
    'anIdealization = isNecessarily',
    'anIdealization = forOne',
    'but = itIsNot',
    'but = forAnOther',
    'theOne = forWhich',
    'theOne = itIs',
    'theOne = isOnlyItself',
    'theI = therefore',
    'theI = spiritInGeneral',
    'theI = orGod',
    'theI = areIdealizations',
    'theI = becauseTheyAreInfinite',
    'as = existents',
    'as = whichAreForThemselves',
    'however = theyAreNot',
    'however = ideationallyDifferent',
    'however = fromThat',
    'however = whichIsForOne',
    'god = isTherefore',
    'god = forHimself',
    'in = soFar',
    'he = isHimself',
    'he = thatWhich',
    'he = isForHim',
    'beingForItself = andBeingForOne',
    'beingForItself = areNot',
    'beingForItself = therefore',
    'beingForItself = diverseSignifications',
    'beingForItself = ofIdeality',
    'but = essential',
    'but = inseparable',
    'but = moments',
    'but = ofIt',
  ],
  predicates: [
    { name: 'beingForOne', args: ['beingForItself'] },
  ],
  relations: [
    { predicate: 'is', from: 'anIdealization', to: 'beingForOne' },
  ],
  candidateSummary: 'This moment gives expression to how the finite is in its unity with the infinite or as an idealization. Being-for-itself does not have negation in it as a determinateness or limit, and consequently also not as reference to an existence other than it. Although this moment is now being designated as being-for-one, there is yet nothing at hand for which it would be; there is not the one of which it would be the moment. There is only one being-for-another, and since this is only one being-for-another, it is also only being-for-one; there is only the one ideality. Being-for-one and being-for-itself do not therefore constitute two genuine determinacies. Being-for-itself refers itself to itself as sublated other, is for-one; in its other it refers itself only to itself. An idealization is necessarily for-one, but it is not for an other; the one, for which it is, is only itself. The "I," therefore, spirit in general, or God, are idealizations, because they are infinite; as existents which are for-themselves, however, they are not ideationally different from that which is for-one. God is therefore for himself, in so far he is himself that which is for him. Being-for-itself and being-for-one are not, therefore, diverse significations of ideality but essential, inseparable, moments of it.',
  provenance: {
    sourceChunk: 'being-for-self-b',
    sourceOp: 'bf-self-op-3-being-for-one',
  },
};

export const bfSelfOp4TheOne: LogicalOperation = {
  id: 'bf-self-op-4-the-one',
  chunkId: 'being-for-self-c',
  label: 'c. The one — simple unity and abstract limit',
  clauses: [
    'beingForItself = isTheSimpleUnity',
    'beingForItself = ofItself',
    'beingForItself = andItsMoments',
    'beingForItself = ofTheBeingForOne',
    'there = isOnly',
    'there = oneDetermination',
    'there = present',
    'there = theSelfReference',
    'there = itself',
    'there = ofTheSublating',
    'theMoments = ofBeingForItself',
    'theMoments = haveSunk',
    'theMoments = intoAnIndifferentiation',
    'theMoments = whichIsImmediacy',
    'theMoments = orBeing',
    'but = anImmediacy',
    'but = thatIsBased',
    'but = onTheNegating',
    'but = posited',
    'but = asItsDetermination',
    'beingForItself = isThus',
    'beingForItself = anExistentForItself',
    'and = sinceInThisImmediacy',
    'itsInnerMeaning = vanishes',
    'it = isTheTotallyAbstractLimit',
    'it = ofItself',
    'it = theOne',
    'attention = mayBeDrawn',
    'attention = inAdvance',
    'attention = toTheDifficulties',
    'attention = thatLieAhead',
    'attention = inTheExposition',
    'attention = ofTheDevelopment',
    'attention = ofTheOne',
    'and = toTheSource',
    'and = ofTheseDifficulties',
    'theMoments = thatConstitute',
    'theMoments = theConcept',
    'theMoments = ofTheOne',
    'theMoments = asBeingForItself',
    'theMoments = occurInIt',
    'theMoments = oneOutsideTheOther',
    'negation = inGeneral',
    'two = negations',
    'two = thatAre',
    'two = therefore',
    'two = theSame',
    'absolutely = opposed',
    'selfReference = identity',
    'selfReference = asSuch',
    'negative = reference',
    'negative = whichIsNonetheless',
    'negative = selfReference',
    'these = moments',
    'these = occurHere',
    'these = apart',
    'because = theForm',
    'because = ofImmediacy',
    'because = ofBeing',
    'because = entersInto',
    'because = theBeingForItself',
    'because = asExistentForItself',
    'because = ofThisImmediacy',
    'each = moment',
    'each = isPosited',
    'each = asADetermination',
    'each = existentOnItsOwn',
    'and = yet',
    'they = areJustAsInseparable',
    'hence = ofEachDetermination',
    'theOpposite = mustEqually',
    'theOpposite = beSaid',
    'it = isThisContradiction',
    'it = thatCauses',
    'it = theDifficulty',
    'it = thatGoesWith',
    'it = theAbstractNature',
    'it = ofTheMoments',
  ],
  predicates: [
    { name: 'theOne', args: ['beingForItself'] },
  ],
  relations: [
    { predicate: 'is', from: 'beingForItself', to: 'theOne' },
  ],
  candidateSummary: 'Being-for-itself is the simple unity of itself and its moments, of the being-for-one. There is only one determination present, the self-reference itself of the sublating. The moments of being-for-itself have sunk into an indifferentiation which is immediacy or being, but an immediacy that is based on the negating posited as its determination. Being-for-itself is thus an existent-for-itself, and, since in this immediacy its inner meaning vanishes, it is the totally abstract limit of itself: the one. Attention may be drawn in advance to the difficulties that lie ahead in the exposition of the development of the one, and to the source of these difficulties. The moments that constitute the concept of the one as being-for-itself occur in it one outside the other: (1) negation in general; (2) two negations that are, therefore, (3) the same, (4) absolutely opposed; (5) self-reference, identity as such; (6) negative reference which is nonetheless self-reference. These moments occur here apart because the form of immediacy, of being, enters into the being-for-itself as existent-for-itself; because of this immediacy, each moment is posited as a determination existent on its own, and yet they are just as inseparable. Hence, of each determination the opposite must equally be said; it is this contradiction that causes the difficulty that goes with the abstract nature of the moments.',
  provenance: {
    sourceChunk: 'being-for-self-c',
    sourceOp: 'bf-self-op-4-the-one',
  },
};

export const beingForSelfOperations: LogicalOperation[] = [
  bfSelfOp1GeneralConcept,
  bfSelfOp2ExistenceAndBeingForItself,
  bfSelfOp3BeingForOne,
  bfSelfOp4TheOne,
];

