/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  return false
}

switch (platform) {
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          // load musl stub
        } else {
          try {
            nativeBinding = require('./gdsl.linux-x64-gnu.node')
          } catch (e) {
            loadError = e
          }
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
     // Fallback or throw
     console.warn('Platform not explicitly handled in stub loader')
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const {  } = nativeBinding

module.exports = nativeBinding
