//! CollapsePath specification and configuration.
//!
//! Translation source: `org.neo4j.gds.walking.CollapsePathConfig`.

use serde::{Deserialize, Serialize};

/// Configuration for path-collapsing traversal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollapsePathConfig {
    /// Ordered sequences of relationship-type names describing the templates to follow.
    pub path_templates: Vec<Vec<String>>,
    /// Relationship type name to assign to collapsed edges.
    pub mutate_relationship_type: String,
    /// Whether to keep self-loops (source == target) in the collapsed output.
    pub allow_self_loops: bool,
    /// Concurrency hint; currently unused by the sequential runtime.
    pub concurrency: usize,
}

impl Default for CollapsePathConfig {
    fn default() -> Self {
        Self {
            path_templates: Vec::new(),
            mutate_relationship_type: "collapsed".to_string(),
            allow_self_loops: false,
            concurrency: 4,
        }
    }
}

/// Collapsed edges produced by following all templates.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CollapsePathResult {
    /// Relationship type used for the collapsed edges (echoed from the config).
    pub mutate_relationship_type: String,
    /// Unique directed edges (source, target) generated by template traversal.
    pub edges: Vec<(u64, u64)>,
}

/// Marker type for executor catalog integration.
pub struct CollapsePathAlgorithmSpec {
    graph_name: String,
}

impl CollapsePathAlgorithmSpec {
    pub fn new(graph_name: String) -> Self {
        Self { graph_name }
    }

    pub fn graph_name(&self) -> &str {
        &self.graph_name
    }
}
